@startuml{BoardObjStaticDesign.png} "BoardObj Static Design"
  node "PMU microcode" {
    node "Application Layer" {
      node "Module BoardOjects" {
        rectangle "Unit BoardObjGrpMask" as bobjgrpmsk_unit
        rectangle "Unit BoardObjGrp"     as bobjgrp_unit
        rectangle "Unit BoardObj"        as bobj_unit
      }
    }
  }
@enduml