/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2020 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#include "lwriscv/manifest_gh100.h"


const PKC_VERIFICATION_MANIFEST manifest = {
    // Decrytpted part of manifest
    .stage1RSA3KSigProd     = {0, },
    .stage1RSA3KSigDebug    = {0, },
    .magicNumberStage1      = 0x42,
    .bUseDevKey             = TRUE,
    .manifestEncParams      = {
        // MK TODO: check endiannes and if we care about that field on non-fsp
        .encryptionDerivationString = "",
        .iv                 = {0x69, 0xef, 0xd0, 0x27, 0x8a, 0xca, 0xbb, 0xc4,
                               0xcb, 0xc8, 0x37, 0x34, 0x04, 0xfc, 0xb8, 0x8c},

        .authTag            = {0, },
    },

    // Encrypted part of manifest (stage 1)
    .version               = 0x01,
    .ucodeId               = 0x04,  // See https://confluence.lwpu.com/display/GFS/Ucode+ID+Assignment
    .ucodeVersion          = 0x00,  // Post-QS signed
    .bRelaxedVersionCheck  = TRUE,  // Allow >= check for ucode version in BR revocation
    .engineIdMask          = ENGINE_TO_ENGINE_ID_MASK(GSP),    // Base 1
    // This field will be patched during build
    .itcmSizeIn256Bytes    = (LWRISCV_APP_IMEM_LIMIT) / 256,    // NA, incorrect value will not work on boot
    // This field will be patched during build
    .dtcmSizeIn256Bytes    = (LWRISCV_APP_DMEM_LIMIT) / 256,    // NA, incorrect value will not work on boot
    .fmcHashPadInfoBitMask = 0x00000000,            // LSB determines if PDI is pre-pended to the FMC before hashing
    .fmcEncParams          = {
        // NOT AUTOGENERATED! also must be !=0
        // MK TODO: check endiannes
        .encryptionDerivationString = "",
        .iv                 = {0x69, 0xef, 0xd0, 0x27, 0x8a, 0xca, 0xbb, 0xc4,
                               0xcb, 0xc8, 0x37, 0x34, 0x04, 0xfc, 0xb8, 0x8c},
        .authTag            = {0, },
    },
    // Need a checklist that says this cannot be 0
    // This field will be patched by siggen
    .digest                = { 0x00000000, 0x00000000, 0x00000000, 0x00000000,      // NA, patched by siggen when signing
                               0x00000000, 0x00000000, 0x00000000, 0x00000000,
                               0x00000000, 0x00000000, 0x00000000, 0x00000000 },
    .secretMask            = {
        .scpSecretMask     = 0x0000000080000001ULL,                       // SCP 'secret' instruction is not allowed
        .scpSecretMaskLock = 0xFFFFFFFF7FFFFFFEULL,                       // This mask is locked and cannot be changed
    },
    .debugAccessControl    = {
        // See https://confluence.lwpu.com/display/LW/LWWATCH+Debugging+and+Security+-+GA10X+POR for reviewed POR debugging capabilities
        .dbgctl =
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STOP,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RUN,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STEP,   _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_J,      _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_EMASK,  _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RREG,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WREG,   _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RDM,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WDM,    _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RSTAT,  _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_IBRKPT, _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RCSR,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WCSR,   _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RPC,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RFREG,  _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WFREG,  _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _START_IN_ICD,     _FALSE  ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _SINGLE_STEP_MODE, _DISABLE),
        .dbgctlLock = 0xFFFFFFFF,       // DBGCTL cannot be changed by any code running on the core
    },
    .bDICE = FALSE,
    .bKDF  = FALSE,                     // PMU Steady State does not use fuse keys
    .bCertCA = FALSE,
    .bAttester = FALSE,

    .mspm  = {
        .mplm  = (LW_RISCV_CSR_MSPM_MPLM_LEVEL3),
        .msecm = LW_RISCV_CSR_MSPM_MSECM_SEC
    },

    .kdfConstant = { 0 },   // PMU does not use KDF (for decrypt fuse key)

    .deviceMap.deviceMap = {
        DEVICEMAP(_MMODE,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_RISCV_CTL,      _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_PIC,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_TIMER,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_HOSTIF,         _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_DMA,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        // PMB must be unlocked so someone can write LOCKPMB (and then disable/lock it)
        DEVICEMAP(_PMB,            _ENABLE,  _ENABLE,  _UNLOCKED) |
        DEVICEMAP(_DIO,            _ENABLE,  _ENABLE,  _LOCKED  ),

        DEVICEMAP(_KEY,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_DEBUG,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SHA,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_KMEM,           _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_BROM,           _ENABLE,  _DISABLE, _LOCKED  ) | // BROM enforced
        DEVICEMAP(_ROM_PATCH,      _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_IOPMP,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_NOACCESS,       _DISABLE, _DISABLE, _LOCKED  ), // Empty Group

        DEVICEMAP(_SCP,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_FBIF,           _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_FALCON_ONLY,    _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_PRGN_CTL,       _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP0, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP1, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP2, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP3, _ENABLE,  _ENABLE,  _LOCKED  ),

        DEVICEMAP(_PLM,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_HUB_DIO,        _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_RESET,          _ENABLE,  _ENABLE,  _LOCKED  ),
    },

    .corePmp = {
        .cfg = {
            PMP_ENTRY(_DENIED,    _DENIED,    _DENIED,   _NAPOT,  _UNLOCK, 0) | // IMEM FMC, access block for S/U *MUST BE UNLOCKED*
            PMP_ENTRY(_DENIED,    _DENIED,    _DENIED,   _NAPOT,  _UNLOCK, 1) | // DMEM FMC, access blocks for S/U *MUST BE UNLOCKED*
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _NAPOT, _LOCK,   2) | // LOCALIO, RW
            PMP_ENTRY_OFF(3)                                                  | // TOR start for PRI (see next)
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _TOR,   _LOCK,   4),  // TOR - PRI - RW
            [1] = 0, // PMP entry 8..15 -> pmpcfg2 // Hole for partition mapping
            [2] = 0, // PMP entry 16..23 -> extpmp0 // Hole for partition mapping
            [3] = 0 // PMP entry 24-31 -> extpmp2
        },
        .addr = {
            // PMPADDR
            IOPMPADDR_LO_IMEM(IMEM_SK_SIZE - 1), // PMPADDR(0)
            IOPMPADDR_LO_DMEM(DMEM_SK_SIZE - 1), // PMPADDR(1)
            ((LW_RISCV_AMAP_INTIO_START >> 2) | ((LW_RISCV_AMAP_INTIO_SIZE - 1) >> 3)), // LOCALIO
            (LW_RISCV_AMAP_PRIV_START >> 2),   // PRI start
            (LW_RISCV_AMAP_PRIV_END   >> 2),   // PRI end
            0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 8-15 // Hole for partition mapping
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 16-23 // Hole for partition mapping
            0x0, // 24... 31
        },
    },

    // IO_PMP_MODE - NAPOT for all entries as that's the only mode we support
    .ioPmpMode = 0xC0000000000003FF,

    .ioPmp.entry = {
        [0] = { // IOPMPCFG(0) - block IMEM FMC access - All masters
            .cfg     = DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _DISABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER, _ALL_MASTERS_ENABLED) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
            .usercfg = 0x0,
            .addrLo  = IOPMPADDR_LO_IMEM(IMEM_SK_SIZE - 1),
            .addrHi  = 0,
        },
        [1] = { // Permit reading SK
                // WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
                // This is due to bug in FMODEL for SCP bypass. Do not prod sign with this entry.
                // WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING
            .cfg     = DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_FBDMA_DMEM, _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_CPDMA, _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
            .usercfg = 0x0,
                // First page of DMEM
                .addrLo  = IOPMPADDR_LO_DMEM(0x100 - 1),
            .addrHi  = 0,
        },

        [2] = { // IOPMPCFG(1) - block DMEM FMC access - All masters
            .cfg     = DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _DISABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER, _ALL_MASTERS_ENABLED) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
            .usercfg = 0x0,
            .addrLo  = IOPMPADDR_LO_DMEM(DMEM_SK_SIZE - 1),
            .addrHi  = 0,
        },
        [3] = { // Permit DMA to SCP buffer in shared DMEM region
            .cfg     = DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_CPDMA, _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
            .usercfg = 0x0,
                // Shared memory region is right behind SK, we need to map 16 bytes, but IOPMP has 1KiB granularity, so
                // it'll map 1KiB area
            .addrLo  = ((LW_RISCV_AMAP_DMEM_START + DMEM_SK_SIZE) >> 2) | ((1024 - 1) >> 3),
            .addrHi  = 0,
        },
        [4] = { // Permit reading print buffer
            .cfg     = DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
                       DRF_IDX_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_PMB, 0, _ENABLE) |
                       DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
            .usercfg = 0x0,
                // Shared memory region is right behind SK, we need to map 16 bytes, but IOPMP has 1KiB granularity, so
                // it'll map 1KiB area
            .addrLo  = ((LW_RISCV_AMAP_DMEM_START + LWRISCV_DMEM_SIZE - 0x800 ) >> 2) | ((0x800 - 1) >> 3),
            .addrHi  = 0,
        },

        [31] = { // Terminating iopmp entry, block everything
             .cfg     = DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _DISABLE) |
                        DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
                        DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER, _ALL_MASTERS_ENABLED) |
                        DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
            .usercfg = 0x0,
            .addrLo  = 0xFFFFFFFF,
            .addrHi  = 0xFFFFFFFF,
        },
    },

    .numberOfValidPairs      = 1,

    .registerPair.entries    = {
        // Bug 3508044 WAR: set _ST_WAIT_FBIF_ACK_EN
        //  This is NOT sufficient to fully fix the ordering bug, but seems to be
        //  good enough to get past the initial issues/repro w/ GSP-RM.
        //  TODO: This should be removed once a true WAR is implemented (e.g., HUB
        //        encryption disabled by VBIOS).
        [0] = {
            .addr = LW_PRGNLCL_RISCV_LWCONFIG,
            .andMask = 0xFFFFF,
            .orMask = DRF_NUM(_PRGNLCL, _RISCV_LWCONFIG, _ST_WAIT_FBIF_ACK_EN, 1),
        },
    },
};

