# Configuration file for DPFGA per CL sanity in DVS

proc dfpga_get_num_cmds {} {
    return 10
}

proc dfpga_get_cmd { idx } {
    switch $idx {
        0 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom gputest.js -base -no_gold -notest -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1" }
        1 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom gputest.js -base -no_gold  -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1 -test 327 -testargstr 327 DPCFilePath ga10x_qt_dfpga_tmds_b.dpc -testarg 327 Verbose true" }
        2 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom gputest.js -base -no_gold  -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1 -test 327 -testargstr 327 DPCFilePath test_ampere.dpc -testarg 327 Verbose true" }
        3 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41_2head1or_dualsst.rom gputest.js -base -no_gold  -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1 -test 327 -testargstr 327 DPCFilePath ga10x_qt_dfpga_dp_2H1OR.dpc -testarg 327 Verbose true" }
        4 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom gputest.js -base -no_gold  -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1 -test 327 -testargstr 327 DPCFilePath 1024x768_ampere.dpc -testarg 327 Verbose true" }
        5 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41_2head1or_dualsst.rom  gpugen.js -base  -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 0x5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1 -test 304 -testarg 304 Verbose true -testarg 304 UseSmallRaster true -testarg 304 EnableDSCRefMode false" }
        6 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41_2head1or_dualsst.rom  gputest.js -base  -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 0x5000 -rmkey gc6_level_override 2 -only_family ada -suppress_gpio_intr_err_log 0x1 -test 304 -testarg 304 Verbose true -testarg 304 UseSmallRaster true -testarg 304 EnableDSCRefMode false" }
        7 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom rmtest.js -engr -forcetestname CycleLwDisp2 -rmkey RMBandwidthFeature 0x40400 -protocol SINGLE_TMDS_B -headwin 0-0-800-600 -heads 0 -sors 0 -resolution 800x600x32x60 -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -gc6_level_override 2 -onlyConnectedDisplays -only_family ada -suppress_gpio_intr_err_log 0x1" }
        8 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom rmtest.js -engr -forcetestname CycleLwDisp2 -rmkey RMBandwidthFeature 0x40400 -protocol DP_A,DP_B -headwin 1-1-800-600 -heads 1 -sors 1 -resolution 800x600x32x60 -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -gc6_level_override 2 -onlyConnectedDisplays -only_family ada -suppress_gpio_intr_err_log 0x1" }
        9 { return "-chip hwchip2.so -gpubios 0 ga102f_fpga_sddr3_nopll_dcb41.rom rmtest.js -engr -forcetestname CycleLwDisp2 -rmkey RMBandwidthFeature 0x40400 -protocol HDMI_FRL -hdmiFrlLinkRate 3 -hdmiFrlLaneCount 3 -headwin 0-0-800-600 -heads 0 -sors 0 -resolution 800x600x32x60 -devid_check_ignore -force_fb -pmu_instloc_inst vid -pmu_bootstrap_mode 1 -disable_acr -lsfm_disable_mask 0xffffffff -exelwte_rm_devinit_on_pmu 0 -disp_ignore_imp -timeout_ms 5000 -gc6_level_override 2 -onlyConnectedDisplays -only_family ada -suppress_gpio_intr_err_log 0x1 -check_hdcp" }
    }
    return ""
}
