#!/bin/sh

# selwrescrub-config
# just run rmconfig using our config file

# bail on any error
set -e

[ -f selwrescrub-config.cfg ]  ||  cd ../config
[ -f selwrescrub-config.cfg ]  ||  { echo Cannot find selwrescrub-config.cfg >&2; exit 1; }

cd ../src

# NOTE: '--mode acr-config' must be the first argument to rmconfig
exec ${PERL:-perl} ../../../drivers/common/chip-config/chip-config.pl \
                   --mode selwrescrub-config \
                   --config ../config/selwrescrub-config.cfg \
                   --source-root ../src \
                   "$@"
