// This file is automatically generated by {{$name}} - DO NOT EDIT!
//
// HAL stubs, generated by {{$name}}.
//
// Profile:  {{$PROFILE}}
// Template: {{$TEMPLATE_FILE}}
//
// Chips:    {{ CHIP_LIST() }}
//

#ifndef G_{{$XXCFG}}_HAL_STUBS_H
#define G_{{$XXCFG}}_HAL_STUBS_H

// pull in private headers for each engine
{{ ENGINE_INCLUDE_PRIVATE_HEADER(":ALL_ENGINES") }}

#include "{{$HAL_PUBLIC_FILE}}"

// Enable the following code when it start to use dynamic IP_VERSION functions
//
// HACK: a global var unique to the ipVersions _UNASSIGNED routines to ensure this function 
//       is not aliased by link-time-optimizations with a _STUB fn that might actually
//       be assigned to a hal method as that would break the <ENG>_HAL_VERIFY_INTERFACE
//       test.
// {{$STATUS_TYPEDEF}} iGrp_ipVersions_UNIQUIFIER;

// the "_UNASSIGNED" function for all IP_VERSIONS dynamic interfaces
/*
{{$STATUS_TYPEDEF}} iGrp_ipVersions_UNASSIGNED(void)
{
    {{$ASSERT}}(0 && "iGrp_ipVersions_UNASSIGNED");
    return {{$STATUS_ERROR}} +
           iGrp_ipVersions_UNIQUIFIER;    // will be 0
}
*/

//
// generated _STUB functions
//

{{ HAL_STUBS() }}

{{ HAL_SETUP_MISSING_FUNCTION(':ALL_ENGINES',
            '',
            '//',
            '// "missing engine" setup sequences, if any',
            '//',
    ) }}

{{ HAL_SETUP_VGPUSTUB_FUNCTION(':ALL_ENGINES',
            '',
            '//',
            '// _VGPUSTUB setup sequences',
            '//',
    ) }}

#endif  // G_{{$XXCFG}}_HAL_STUBS_H
