/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2010-2014 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */

/**
 * @file  lwwatch.cpp
 * @brief Dummy function linked by MODS so that lwwatch lib is present
 */

#include "gpu/include/lwwatch.h"

void CallAllLwwatch()
{
#define CALL_LW_WATCH(cmd) cmd(0);
    CALL_LW_WATCH(init)
    CALL_LW_WATCH(verbose)
    CALL_LW_WATCH(ptov)
    CALL_LW_WATCH(vtop)
    CALL_LW_WATCH(gvtop)
    CALL_LW_WATCH(gpde)
    CALL_LW_WATCH(gpte)
    CALL_LW_WATCH(rb)
    CALL_LW_WATCH(wb)
    CALL_LW_WATCH(rw)
    CALL_LW_WATCH(ww)
    CALL_LW_WATCH(rd)
    CALL_LW_WATCH(wr)
    CALL_LW_WATCH(tmdsrd)
    CALL_LW_WATCH(tmdswr)
    CALL_LW_WATCH(gvrd)
    CALL_LW_WATCH(gvwr)
    CALL_LW_WATCH(gvdisp)
    CALL_LW_WATCH(cpudisp)
    CALL_LW_WATCH(gvdiss)
    CALL_LW_WATCH(fbrd)
    CALL_LW_WATCH(fbwr)
    CALL_LW_WATCH(heap)
    CALL_LW_WATCH(diag)
    CALL_LW_WATCH(help)
    CALL_LW_WATCH(clocks)
    CALL_LW_WATCH(cntrfreq)
    CALL_LW_WATCH(getcr)
    CALL_LW_WATCH(setcr)
    CALL_LW_WATCH(i2c)
    CALL_LW_WATCH(dcb)
    CALL_LW_WATCH(slivb)
    CALL_LW_WATCH(zbc)
    CALL_LW_WATCH(l2ilwalidate)
    CALL_LW_WATCH(fbmonitor)
    CALL_LW_WATCH(l2state)
    CALL_LW_WATCH(ismemreq)
    CALL_LW_WATCH(fifoinfo)
    CALL_LW_WATCH(pbinfo)
    CALL_LW_WATCH(runlist)
    CALL_LW_WATCH(pb)
    CALL_LW_WATCH(pbch)
    CALL_LW_WATCH(pbdma)
    CALL_LW_WATCH(channelram)
    CALL_LW_WATCH(grinfo)
    CALL_LW_WATCH(gr)
    CALL_LW_WATCH(launchcheck)
    CALL_LW_WATCH(tiling)
    CALL_LW_WATCH(zlwll)
    CALL_LW_WATCH(zlwllram)
    CALL_LW_WATCH(surface)
    CALL_LW_WATCH(limiterror)
    CALL_LW_WATCH(subch)
    CALL_LW_WATCH(grctx)
    CALL_LW_WATCH(grstatus)
    CALL_LW_WATCH(grwarppc)
    CALL_LW_WATCH(ssclass)
    CALL_LW_WATCH(perfmon)
    CALL_LW_WATCH(fifoctx)
    CALL_LW_WATCH(insttochid)
    CALL_LW_WATCH(vic)
    CALL_LW_WATCH(msdec)
    CALL_LW_WATCH(falctrace)
    CALL_LW_WATCH(pcieinfo)
    CALL_LW_WATCH(pcie)
    CALL_LW_WATCH(pd)
    CALL_LW_WATCH(pe)
    CALL_LW_WATCH(dchnstate)
    CALL_LW_WATCH(dchnnum)
    CALL_LW_WATCH(dchnname)
    CALL_LW_WATCH(dgetdbgmode)
    CALL_LW_WATCH(dsetdbgmode)
    CALL_LW_WATCH(dinjectmethod)
    CALL_LW_WATCH(dreadasy)
    CALL_LW_WATCH(dreadarm)
    CALL_LW_WATCH(ddumppb)
    CALL_LW_WATCH(ddispowner)
    CALL_LW_WATCH(dhdorconn)
    CALL_LW_WATCH(dorstate)
    CALL_LW_WATCH(dsetorstate)
    CALL_LW_WATCH(dchnmstate)
    CALL_LW_WATCH(danalyzeblank)
    CALL_LW_WATCH(drdhdmidecoder)
    CALL_LW_WATCH(dwrhdmidecoder)
    CALL_LW_WATCH(dsorpadlinkconn)
    CALL_LW_WATCH(dpinfo)
    CALL_LW_WATCH(dtim)
    CALL_LW_WATCH(sigdump)
    CALL_LW_WATCH(checkprodvals)
    CALL_LW_WATCH(pmudmemrd)
    CALL_LW_WATCH(pmudmemwr)
    CALL_LW_WATCH(pmuimemrd)
    CALL_LW_WATCH(pmuimemwr)
    CALL_LW_WATCH(pmuqueues)
    CALL_LW_WATCH(pmuevtq)
    CALL_LW_WATCH(pmuimblk)
    CALL_LW_WATCH(pmuimtag)
    CALL_LW_WATCH(pmuimmap)
    CALL_LW_WATCH(pmumutex)
    CALL_LW_WATCH(pmutcb)
    CALL_LW_WATCH(pmusym)
    CALL_LW_WATCH(pmusanitytest)
    CALL_LW_WATCH(pmuqboot)
    CALL_LW_WATCH(pmusched)
    CALL_LW_WATCH(msenc)
    CALL_LW_WATCH(smcpartitioninfo)
    CALL_LW_WATCH(smcengineinfo)
}
