/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2006-2007 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */
#ifndef __DISPT_SR_H__
#define __DISPT_SR_H__

/*
 * common C/JavaScript defines for DispTest
 */

#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_PUPC_ALT                    0:0
#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_PDPC                        1:1
#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_PDPC_ALT                    2:2
#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_NORMALSTART                 3:3
#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_SAFESTART                   4:4
#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_NORMALSTATE                 5:5
#define LW_DISPTEST_CONTROL_SET_OR_SEQUENCER_ENABLE_SAFESTATE                   6:6

#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME                              31:0
#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME_XTAL                   0x00000000
#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME_SPPLL0                 0x00000001
#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME_SPPLL1                 0x00000002
#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME_EXT_REF                0x00000003
#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME_QUAL_EXT_REF           0x00000004
#define LW_DISPTEST_CONTROL_SET_VPLL_REF_REF_NAME_EXT_SPREAD             0x00000005

/*
 * LW_DISPTEST_GET_SOR_OP_MODE
 *
 * #define's for DispTest.ControlGetSorOpMode()
 *
 */

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_CATEGORY                            0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_CATEGORY_LVDS                0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_CATEGORY_LWSTOM              0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_0                           0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_1                           1:1
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_2                           2:2
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_3                           3:3
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDA_3_ENABLE             0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_0                           0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_1                           1:1
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_2                           2:2
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_3                           3:3
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDA_3_ENABLE             0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_0                           0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_1                           1:1
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_2                           2:2
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_3                           3:3
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXDB_3_ENABLE             0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_0                           0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_1                           1:1
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_2                           2:2
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_3                           3:3
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXDB_3_ENABLE             0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXCA                             0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXCA_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXCA_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXCA                             0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXCA_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXCA_ENABLE               0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXCB                             0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXCB_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PD_TXCB_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXCB                             0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXCB_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PU_TXCB_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_UPPER                               0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_UPPER_UPPER_RESET            0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_MODE                                0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_MODE_LVDS                    0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_MODE_TMDS                    0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LINKACTA                            0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LINKACTA_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LINKACTA_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LINKACTB                            0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LINKACTB_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LINKACTB_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LVDS_EN                             0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LVDS_EN_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LVDS_EN_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LVDS_DUAL                           0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LVDS_DUAL_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_LVDS_DUAL_ENABLE             0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_DUP_SYNC                            0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_DUP_SYNC_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_DUP_SYNC_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_NEW_MODE                            0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_NEW_MODE_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_NEW_MODE_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_BALANCED                            0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_BALANCED_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_BALANCED_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PLLDIV                              0:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PLLDIV_BY_7                  0x00000000
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_PLLDIV_BY_10                 0x00000001

#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_ROTCLK                              3:0
#define LW_DISPTEST_CONTROL_GET_SOR_OP_MODE_ROTDAT                              2:0

/*
 * LW_DISPTEST_CONTROLSET_SOR_OP
 *
 * #define's for DispTest.ControlSetSorOpModel
 *
 */

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_CATEGORY                            0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_CATEGORY_LVDS                0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_CATEGORY_LWSTOM              0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_0                           0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_1                           1:1
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_2                           2:2
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_3                           3:3
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDA_3_ENABLE             0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_0                           0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_1                           1:1
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_2                           2:2
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_3                           3:3
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDA_3_ENABLE             0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_0                           0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_1                           1:1
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_2                           2:2
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_3                           3:3
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXDB_3_ENABLE             0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_0                           0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_0_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_0_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_1                           1:1
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_1_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_1_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_2                           2:2
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_2_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_2_ENABLE             0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_3                           3:3
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_3_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXDB_3_ENABLE             0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXCA                             0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXCA_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXCA_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXCA                             0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXCA_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXCA_ENABLE               0x00000001

// Remove the PD #defines ASAP.
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXCB                             0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXCB_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PD_TXCB_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXCB                             0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXCB_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PU_TXCB_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_UPPER                               0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_UPPER_UPPER_RESET            0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_MODE                                0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_MODE_LVDS                    0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_MODE_TMDS                    0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LINKACTA                            0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LINKACTA_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LINKACTA_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LINKACTB                            0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LINKACTB_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LINKACTB_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LVDS_EN                             0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LVDS_EN_DISABLE              0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LVDS_EN_ENABLE               0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LVDS_DUAL                           0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LVDS_DUAL_DISABLE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_LVDS_DUAL_ENABLE             0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_DUP_SYNC                            0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_DUP_SYNC_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_DUP_SYNC_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_NEW_MODE                            0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_NEW_MODE_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_NEW_MODE_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_BALANCED                            0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_BALANCED_DISABLE             0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_BALANCED_ENABLE              0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PLLDIV                              0:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PLLDIV_BY_7                  0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_PLLDIV_BY_10                 0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_ROTCLK                              3:0
#define LW_DISPTEST_CONTROL_SET_SOR_OP_MODE_ROTDAT                              2:0

/*
 * LW_DISPTEST_CONTROL_SET_SOR_PWR
 *
 * #define's for DispTest.ControlSetSorOpModel
 *
 */

#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_USE_SPECIFIED_DIV                 0:0
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_USE_SPECIFIED_DIV_NO       0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_USE_SPECIFIED_DIV_YES      0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_DUTY_CYCLE                   1:1
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_DUTY_CYCLE_NO         0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_DUTY_CYCLE_YES        0x00000001
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_FREQ_AND_RANGE               2:2
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_FREQ_AND_RANGE_NO     0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_FREQ_AND_RANGE_YES    0x00000001

/*
 * LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE
 *
 * #define's for DispTest.ControlSetPiorOpMode
 *
 */

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CATEGORY                           2:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CATEGORY_EXT_TMDS           0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CATEGORY_EXT_TV             0x00000001
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CATEGORY_EXT_SDI            0x00000002
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CATEGORY_DRO                0x00000003
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CATEGORY_DRI                0x00000004

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_POLARITY                       0:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_POLARITY_NORMAL         0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_POLARITY_ILW            0x00000001

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_MODE                           0:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_MODE_SDR                0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_MODE_DDR                0x00000001

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_PHS                            1:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_PHS_0                   0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_PHS_1                   0x00000001
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_PHS_2                   0x00000002
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_PHS_3                   0x00000003

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_UNUSED_PINS                        0:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_UNUSED_PINS_LO              0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_UNUSED_PINS_TS              0x00000001

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_H                         0:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_H_NORMAL           0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_H_ILW              0x00000001

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_V                         1:1
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_V_NORMAL           0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_V_ILW              0x00000001

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_DE                        2:2
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_DE_NORMAL          0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_POLARITY_DE_ILW             0x00000001

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING                        3:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING_RGB_0           0x00000000
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING_RGB_1           0x00000001
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING_EXT_SDI         0x00000002
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING_DIST_RNDR       0x00000003
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING_YUV_0           0x00000004
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_MUXING_UYVY            0x00000005

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_CLK_DLY                            2:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DATA_DLY                           2:0

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_DRIVE_PIN_SET                  2:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_DRIVE_PIN_SET_NEITHER          0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_DRIVE_PIN_SET_A                1
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_DRIVE_PIN_SET_B                2

#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_MASTER                         1:0
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_MASTER_YES                     1
#define LW_DISPTEST_CONTROL_SET_PIOR_OP_MODE_DRO_MASTER_NO                      0

/*
 * LW_DISPTEST_CONTROL_SET_SF_BLANK
 *
 * #define's for DispTest.ControlSetSfBlank
 *
 */

#define LW_DISPTEST_CONTROL_SET_SF_BLANK_TRANSITION                             0:0
#define LW_DISPTEST_CONTROL_SET_SF_BLANK_TRANSITION_IMMEDIATE            0x00000000
#define LW_DISPTEST_CONTROL_SET_SF_BLANK_TRANSITION_NEXT_VSYNC           0x00000001

#define LW_DISPTEST_CONTROL_SET_SF_BLANK_STATUS                                 0:0
#define LW_DISPTEST_CONTROL_SET_SF_BLANK_STATUS_UNBLANK                  0x00000000
#define LW_DISPTEST_CONTROL_SET_SF_BLANK_STATUS_BLANK                    0x00000001

/*
 * LW5070_CTRL_CMD_SET_RG_UNDERFLOW_PROP
 *
 * #define's for DispTest.ControlSetRgUnderflowProp
 *
 */

#define LW_DISPTEST_CONTROL_SET_RG_UNDERFLOW_PROP_ENABLE_NO              0x00000000
#define LW_DISPTEST_CONTROL_SET_RG_UNDERFLOW_PROP_ENABLE_YES             0x00000001
#define LW_DISPTEST_CONTROL_SET_RG_UNDERFLOW_PROP_CLEAR_UNDERFLOW_NO     0x00000000
#define LW_DISPTEST_CONTROL_SET_RG_UNDERFLOW_PROP_CLEAR_UNDERFLOW_YES    0x00000001
#define LW_DISPTEST_CONTROL_SET_RG_UNDERFLOW_PROP_MODE_REPEAT            0x00000000
#define LW_DISPTEST_CONTROL_SET_RG_UNDERFLOW_PROP_MODE_RED               0x00000001

/*
 * LW5070_CTRL_CMD_SET_SOR_PWM
 *
 * #define's for DispTest.ControlSetSorPwmMode
 *
 */

#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_USE_SPECIFIED_DIV                 0:0
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_USE_SPECIFIED_DIV_NO       0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_USE_SPECIFIED_DIV_YES      0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_DUTY_CYCLE                   1:1
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_DUTY_CYCLE_NO         0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_DUTY_CYCLE_YES        0x00000001

#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_FREQ_AND_RANGE               2:2
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_FREQ_AND_RANGE_NO     0x00000000
#define LW_DISPTEST_CONTROL_SET_SOR_PWM_FLAGS_PROG_FREQ_AND_RANGE_YES    0x00000001

/*
 * LW5070_CTRL_CMD_SET_DAC_CONFIG
 *
 * #define's for DispTest.ControlSetDacConfig
 *
 */

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC0_SRC                        1:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC0_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC0_SRC_COMPOSITE       0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC0_SRC_SVIDEO_Y        0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC0_SRC_SVIDEO_C        0x00000003

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC1_SRC                        1:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC1_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC1_SRC_COMPOSITE       0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC1_SRC_SVIDEO_Y        0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC1_SRC_SVIDEO_C        0x00000003

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC2_SRC                        1:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC2_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC2_SRC_COMPOSITE       0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC2_SRC_SVIDEO_Y        0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC2_SRC_SVIDEO_C        0x00000003

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC3_SRC                        1:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC3_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC3_SRC_COMPOSITE       0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC3_SRC_SVIDEO_Y        0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_CPST_DAC3_SRC_SVIDEO_C        0x00000003

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC                        2:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC_COMPONENT_G_Y   0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC_COMPONENT_R_PR  0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC_COMPONENT_B_PB  0x00000003
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC_COMPOSITE       0x00000004
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC0_SRC_COMPONENT_Y     0x00000005

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC                        2:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC_COMPONENT_G_Y   0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC_COMPONENT_R_PR  0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC_COMPONENT_B_PB  0x00000003
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC_COMPOSITE       0x00000004
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC1_SRC_COMPONENT_Y     0x00000005

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC                        2:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC_COMPONENT_G_Y   0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC_COMPONENT_R_PR  0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC_COMPONENT_B_PB  0x00000003
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC_COMPOSITE       0x00000004
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC2_SRC_COMPONENT_Y     0x00000005

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC                        2:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC_NONE            0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC_COMPONENT_G_Y   0x00000001
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC_COMPONENT_R_PR  0x00000002
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC_COMPONENT_B_PB  0x00000003
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC_COMPOSITE       0x00000004
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_COMP_DAC3_SRC_COMPONENT_Y     0x00000005

#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_DRIVE_SYNC                           0:0
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_DRIVE_SYNC_NO                 0x00000000
#define LW_DISPTEST_CONTROL_SET_DAC_CONFIG_DRIVE_SYNC_YES                0x00000001

/*
 * LW5070_CTRL_CMD_SET_RG_FLIPLOCK_PROP
 *
 * #define's for DispTest.ControlSetRgFliplockProp
 *
 */
#define LW_DISPTEST_CONTROL_SET_RG_FLIPLOCK_PROP_MAX_SWAP_LOCKOUT_SKEW             9:0
#define LW_DISPTEST_CONTROL_SET_RG_FLIPLOCK_PROP_MAX_SWAP_LOCKOUT_SKEW_INIT 0x00000000

#define LW_DISPTEST_CONTROL_SET_RG_FLIPLOCK_PROP_SWAP_LOCKOUT_START               15:0
#define LW_DISPTEST_CONTROL_SET_RG_FLIPLOCK_PROP_SWAP_LOCKOUT_START_INIT    0x00000000

/*
 * State cache defines
 *
 * Each offset can be used within the LW_PDISP_DSI_CACHE0() or
 * LW_PDISP_DSI_CACHE1() macro depending on which state cache it is
 * accessing to get the BAR0 offset for that register.
 *
 */
#define LW_DISPTEST_DSI_SC_CORE_RASTER_WIDTH_ACTIVE                     0x0
#define LW_DISPTEST_DSI_SC_CORE_RASTER_WIDTH_ACTIVE_ARM                 0x1
#define LW_DISPTEST_DSI_SC_CORE_RASTER_HEIGHT_ACTIVE                    0x2
#define LW_DISPTEST_DSI_SC_CORE_RASTER_HEIGHT_ACTIVE_ARM                0x3
#define LW_DISPTEST_DSI_SC_CORE_USING_BASE_LUT                          0x4
#define LW_DISPTEST_DSI_SC_CORE_USING_OUTPUT_LUT                        0x5
#define LW_DISPTEST_DSI_SC_CORE_USING_SURFACE0                          0x6
#define LW_DISPTEST_DSI_SC_CORE_USING_SURFACE1                          0x7
#define LW_DISPTEST_DSI_SC_CORE_USING_LWRSOR                            0x8
#define LW_DISPTEST_DSI_SC_CORE_USING_SCALER                            0x9
#define LW_DISPTEST_DSI_SC_CORE_VIEWPORT_OUT_FULLY_VISIBLE              0xa
#define LW_DISPTEST_DSI_SC_CORE_VIEWPORT_OUT_FULLY_VISIBLE_ARM          0xb
#define LW_DISPTEST_DSI_SC_GLOBAL_CORE_CONFIGURED                       0xc
#define LW_DISPTEST_DSI_SC_GLOBAL_CORE_CONFIGURED_ARM                   0xd
#define LW_DISPTEST_DSI_SC_GLOBAL_CORE_BASE_ACTIVE                      0xe
#define LW_DISPTEST_DSI_SC_GLOBAL_CORE_BASE_ACTIVE_ARM                  0xf
#define LW_DISPTEST_DSI_SC_GLOBAL_BASE_BASE_ACTIVE                      0x10
#define LW_DISPTEST_DSI_SC_GLOBAL_BASE_BASE_ACTIVE_ARM                  0x11
#define LW_DISPTEST_DSI_SC_GLOBAL_CORE_OUTPUT_PASSTHROUGH               0x12
#define LW_DISPTEST_DSI_SC_GLOBAL_CORE_OUTPUT_PASSTHROUGH_ARM           0x13
#define LW_DISPTEST_DSI_SC_PCALC_SET_BASE_FIRST_LAST_Y                  0x14
#define LW_DISPTEST_DSI_SC_PCALC_SET_BASE_FIRST_LAST_X                  0x15
#define LW_DISPTEST_DSI_SC_PCALC_SET_BASE_START_PHASE_Y                 0x16
#define LW_DISPTEST_DSI_SC_PCALC_SET_BASE_START_PHASE_X                 0x17
#define LW_DISPTEST_DSI_SC_PCALC_SET_BASE_VERT_RATIO                    0x18
#define LW_DISPTEST_DSI_SC_PCALC_SET_BASE_HORIZ_RATIO                   0x19
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_FIRST_LAST_Y                  0x1a
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_FIRST_LAST_X                  0x1b
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_HORIZ_START_PHASE             0x1c
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_HORIZ_RATIO                   0x1d
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_ILW_HORIZ_RATIO               0x1e
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_POINT_OUT                     0x1f
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_FIRST_Y_RAS                   0x20
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_FIRST_X_RAS                   0x21
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_FIRST_Y_B_F                   0x22
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_FIRST_X_B_F                   0x23
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_FIRST_LAST_Y                  0x24
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_FIRST_Y_RAS                   0x25
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_FIRST_Y_B_F                   0x26
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_FIRST_LAST_X                  0x27
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_FIRST_X_RAS                   0x28
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_FIRST_X_B_F                   0x29
#define LW_DISPTEST_DSI_SC_PCALC_SET_LWRS_POINT_OUT                     0x2a
#define LW_DISPTEST_DSI_SC_PCALC_SET_FIELD_FRAME_ID                     0x2b
#define LW_DISPTEST_DSI_SC_PCALC_SET_SHOW_VGA                           0x2c
#define LW_DISPTEST_DSI_SC_PCALC_SET_RAS_POINT_OUT_Y                    0x2d
#define LW_DISPTEST_DSI_SC_PCALC_SET_RAS_POINT_OUT_X                    0x2e
#define LW_DISPTEST_DSI_SC_PCALC_SET_RAS_WIN_OUT_W                      0x2f
#define LW_DISPTEST_DSI_SC_PCALC_SET_RAS_WIN_OUT_H                      0x30
#define LW_DISPTEST_DSI_SC_PCALC_SET_BYPASS_PIXEL                       0x31
#define LW_DISPTEST_DSI_SC_PCALC_SET_OVLY_WIDTH_RAS                     0x32
#define LW_DISPTEST_DSI_SC_BASE_SET_ISO_BASEADR                         0x33
#define LW_DISPTEST_DSI_SC_BASE_SET_ISO_LIMIT                           0x34
#define LW_DISPTEST_DSI_SC_BASE_SET_ISO_TARGET                          0x35
#define LW_DISPTEST_DSI_SC_BASE_NEW_BASE_LUT                            0x36
#define LW_DISPTEST_DSI_SC_BASE_SET_BASE_LUT_LO                         0x37
#define LW_DISPTEST_DSI_SC_BASE_SET_BASE_LUT_LO_ARM                     0x38
#define LW_DISPTEST_DSI_SC_BASE_SET_BASE_LUT_HI                         0x39
#define LW_DISPTEST_DSI_SC_BASE_SET_BASE_LUT_HI_ARM                     0x3a
#define LW_DISPTEST_DSI_SC_BASE_NEW_CONTEXT_DMA_ISO                     0x3b
#define LW_DISPTEST_DSI_SC_BASE_SET_CONTEXT_DMA_ISO                     0x3c
#define LW_DISPTEST_DSI_SC_BASE_SET_CONTEXT_DMA_ISO_ARM                 0x3d
#define LW_DISPTEST_DSI_SC_BASE_NEW_CONTEXT_DMA_NOTIFIER                0x3e
#define LW_DISPTEST_DSI_SC_BASE_SET_CONTEXT_DMA_NOTIFIER                0x3f
#define LW_DISPTEST_DSI_SC_BASE_SET_CONTEXT_DMA_NOTIFIER_ARM            0x40
#define LW_DISPTEST_DSI_SC_BASE_NEW_CONTEXT_DMA_SEMAPHORE               0x41
#define LW_DISPTEST_DSI_SC_BASE_SET_CONTEXT_DMA_SEMAPHORE               0x42
#define LW_DISPTEST_DSI_SC_BASE_SET_CONTEXT_DMA_SEMAPHORE_ARM           0x43
#define LW_DISPTEST_DSI_SC_BASE_SET_COLWERSION                          0x44
#define LW_DISPTEST_DSI_SC_BASE_SET_COLWERSION_ARM                      0x45
#define LW_DISPTEST_DSI_SC_BASE_SET_DIST_RENDER_CONTROL                 0x46
#define LW_DISPTEST_DSI_SC_BASE_SET_DIST_RENDER_CONTROL_ARM             0x47
#define LW_DISPTEST_DSI_SC_BASE_NEW_OFFSET_NOTIFIER                     0x48
#define LW_DISPTEST_DSI_SC_BASE_SET_NOTIFIER_CONTROL                    0x49
#define LW_DISPTEST_DSI_SC_BASE_SET_NOTIFIER_CONTROL_ARM                0x4a
#define LW_DISPTEST_DSI_SC_BASE_NEW_OUTPUT_LUT                          0x4b
#define LW_DISPTEST_DSI_SC_BASE_SET_OUTPUT_LUT_LO                       0x4c
#define LW_DISPTEST_DSI_SC_BASE_SET_OUTPUT_LUT_LO_ARM                   0x4d
#define LW_DISPTEST_DSI_SC_BASE_SET_OUTPUT_LUT_HI                       0x4e
#define LW_DISPTEST_DSI_SC_BASE_SET_OUTPUT_LUT_HI_ARM                   0x4f
#define LW_DISPTEST_DSI_SC_BASE_SET_PROCESSING                          0x50
#define LW_DISPTEST_DSI_SC_BASE_SET_PROCESSING_ARM                      0x51
#define LW_DISPTEST_DSI_SC_BASE_SET_PRESENT_CONTROL                     0x52
#define LW_DISPTEST_DSI_SC_BASE_SET_PRESENT_CONTROL_ARM                 0x53
#define LW_DISPTEST_DSI_SC_BASE_NEW_OFFSET_SEMAPHORE                    0x54
#define LW_DISPTEST_DSI_SC_BASE_SET_SEMAPHORE_CONTROL                   0x55
#define LW_DISPTEST_DSI_SC_BASE_SET_SEMAPHORE_CONTROL_ARM               0x56
#define LW_DISPTEST_DSI_SC_BASE_NEW_VALUE_SEMAPHORE                     0x57
#define LW_DISPTEST_DSI_SC_BASE_SET_SEMAPHORE_ACQUIRE                   0x58
#define LW_DISPTEST_DSI_SC_BASE_SET_SEMAPHORE_ACQUIRE_ARM               0x59
#define LW_DISPTEST_DSI_SC_BASE_SET_SEMAPHORE_RELEASE                   0x5a
#define LW_DISPTEST_DSI_SC_BASE_SET_SEMAPHORE_RELEASE_ARM               0x5b
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_NEW_OFFSET0                    0x5c
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_OFFSET0                    0x5d
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_OFFSET0_ARM                0x5e
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_NEW_OFFSET1                    0x5f
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_OFFSET1                    0x60
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_OFFSET1_ARM                0x61
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_PARAMS                     0x62
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_PARAMS_ARM                 0x63
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_SIZE                       0x64
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_SIZE_ARM                   0x65
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_STORAGE                    0x66
#define LW_DISPTEST_DSI_SC_BASE_SURFACE0_SET_STORAGE_ARM                0x67
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_NEW_OFFSET0                    0x68
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_OFFSET0                    0x69
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_OFFSET0_ARM                0x6a
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_NEW_OFFSET1                    0x6b
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_OFFSET1                    0x6c
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_OFFSET1_ARM                0x6d
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_PARAMS                     0x6e
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_PARAMS_ARM                 0x6f
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_SIZE                       0x70
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_SIZE_ARM                   0x71
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_STORAGE                    0x72
#define LW_DISPTEST_DSI_SC_BASE_SURFACE1_SET_STORAGE_ARM                0x73
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_COMPOSITION_CONTROL              0x74
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_COMPOSITION_CONTROL_ARM          0x75
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_CONTEXT_DMA_ISO                  0x76
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_CONTEXT_DMA_ISO                  0x77
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_CONTEXT_DMA_ISO_ARM              0x78
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_CONTEXT_DMA_NOTIFIER             0x79
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_CONTEXT_DMA_NOTIFIER             0x7a
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_CONTEXT_DMA_NOTIFIER_ARM         0x7b
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_CONTEXT_DMA_SEMAPHORE            0x7c
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_CONTEXT_DMA_SEMAPHORE            0x7d
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_CONTEXT_DMA_SEMAPHORE_ARM        0x7e
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_ISO_BASEADR                      0x7f
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_ISO_LIMIT                        0x80
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_ISO_TARGET                       0x81
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_KEY_COLOR                        0x82
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_KEY_COLOR_ARM                    0x83
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_KEY_MASK                         0x84
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_KEY_MASK_ARM                     0x85
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_OFFSET_NOTIFIER                  0x86
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_NOTIFIER_CONTROL                 0x87
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_NOTIFIER_CONTROL_ARM             0x88
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_PRESENT_CONTROL                  0x89
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_PRESENT_CONTROL_ARM              0x8a
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_POINT_IN                         0x8b
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_POINT_IN_ARM                     0x8c
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_OFFSET_SEMAPHORE                 0x8d
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SEMAPHORE_CONTROL                0x8e
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SEMAPHORE_CONTROL_ARM            0x8f
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_VALUE_SEMAPHORE                  0x90
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SEMAPHORE_ACQUIRE                0x91
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SEMAPHORE_ACQUIRE_ARM            0x92
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SEMAPHORE_RELEASE                0x93
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SEMAPHORE_RELEASE_ARM            0x94
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SIZE_IN                          0x95
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SIZE_IN_ARM                      0x96
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SIZE_OUT                         0x97
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_SIZE_OUT_ARM                     0x98
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_TIMESTAMP_VALUE                  0x99
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_TIMESTAMP_VALUE_ARM              0x9a
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_UPDATE_TIMESTAMP                 0x9b
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_UPDATE_TIMESTAMP                 0x9c
#define LW_DISPTEST_DSI_SC_OVERLAY_SET_UPDATE_TIMESTAMP_ARM             0x9d
#define LW_DISPTEST_DSI_SC_OVERLAY_NEW_OFFSET_ISO                       0x9e
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_OFFSET                  0x9f
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_OFFSET_ARM              0xa0
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_PARAMS                  0xa1
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_PARAMS_ARM              0xa2
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_SIZE                    0xa3
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_SIZE_ARM                0xa4
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_STORAGE                 0xa5
#define LW_DISPTEST_DSI_SC_OVERLAY_SURFACE0_SET_STORAGE_ARM             0xa6
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_BASE_CHANNEL_USAGE_BOUNDS     0xa7
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_BASE_CHANNEL_USAGE_BOUNDS_ARM 0xa8
#define LW_DISPTEST_DSI_SC_CORE_NEW_BASE_LUT                            0xa9
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_BASE_LUT_LO                   0xaa
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_BASE_LUT_LO_ARM               0xab
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_BASE_LUT_HI                   0xac
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_BASE_LUT_HI_ARM               0xad
#define LW_DISPTEST_DSI_SC_CORE_NEW_CONTEXT_DMA_ISO                     0xae
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTEXT_DMA_ISO               0xaf
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTEXT_DMA_ISO_ARM           0xb0
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTEXT_DMA_CRC               0xb1
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTEXT_DMA_CRC_ARM           0xb2
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTROL                       0xb3
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTROL_ARM                   0xb4
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTROL_OUTPUT_SCALER         0xb5
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTROL_OUTPUT_SCALER_ARM     0xb6
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTROL_LWRSOR                0xb7
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CONTROL_LWRSOR_ARM            0xb8
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CRC_CONTROL                   0xb9
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_CRC_CONTROL_ARM               0xba
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_DEFAULT_BASE_COLOR            0xbb
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_DEFAULT_BASE_COLOR_ARM        0xbc
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_DITHER_CONTROL                0xbd
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_DITHER_CONTROL_ARM            0xbe
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_LOCK_OFFSET                   0xbf
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_LOCK_OFFSET_ARM               0xc0
#define LW_DISPTEST_DSI_SC_CORE_NEW_OFFSET_ISO0                         0xc1
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OFFSET0                       0xc2
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OFFSET0_ARM                   0xc3
#define LW_DISPTEST_DSI_SC_CORE_NEW_OFFSET_ISO1                         0xc4
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OFFSET1                       0xc5
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OFFSET1_ARM                   0xc6
#define LW_DISPTEST_DSI_SC_CORE_NEW_OFFSET_LWRSOR                       0xc7
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OFFSET_LWRSOR                 0xc8
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OFFSET_LWRSOR_ARM             0xc9
#define LW_DISPTEST_DSI_SC_CORE_NEW_OUTPUT_LUT                          0xca
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OUTPUT_LUT_LO                 0xcb
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OUTPUT_LUT_LO_ARM             0xcc
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OUTPUT_LUT_HI                 0xcd
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OUTPUT_LUT_HI_ARM             0xce
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OVERLAY_USAGE_BOUNDS          0xcf
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OVERLAY_USAGE_BOUNDS_ARM      0xd0
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OVERSCAN_COLOR                0xd1
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_OVERSCAN_COLOR_ARM            0xd2
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PARAMS                        0xd3
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PARAMS_ARM                    0xd4
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PIXEL_CLOCK                   0xd5
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PIXEL_CLOCK_ARM               0xd6
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PRESENT_CONTROL               0xd7
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PRESENT_CONTROL_ARM           0xd8
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PROCAMP                       0xd9
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_PROCAMP_ARM                   0xda
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_BLANK_END              0xdb
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_BLANK_END_ARM          0xdc
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_BLANK_START            0xdd
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_BLANK_START_ARM        0xde
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_SIZE                   0xdf
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_SIZE_ARM               0xe0
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_SYNC_END               0xe1
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_SYNC_END_ARM           0xe2
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_VERT_BLANK2            0xe3
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_VERT_BLANK2_ARM        0xe4
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_VERT_BLANK_DMI         0xe5
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_RASTER_VERT_BLANK_DMI_ARM     0xe6
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_SIZE                          0xe7
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_SIZE_ARM                      0xe8
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_STORAGE                       0xe9
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_STORAGE_ARM                   0xea
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_POINT_IN0            0xeb
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_POINT_IN0_ARM        0xec
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_POINT_IN1            0xed
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_POINT_IN1_ARM        0xee
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_POINT_OUT_ADJUST     0xef
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_POINT_OUT_ADJUST_ARM 0xf0
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_SIZE_IN              0xf1
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_SIZE_IN_ARM          0xf2
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_SIZE_OUT             0xf3
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_SIZE_OUT_ARM         0xf4
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_SIZE_OUT_MIN         0xf5
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_VIEWPORT_SIZE_OUT_MIN_ARM     0xf6
#define LW_DISPTEST_DSI_SC_CORE_DAC0_SET_CONTROL                        0xf7
#define LW_DISPTEST_DSI_SC_CORE_DAC0_SET_CONTROL_ARM                    0xf8
#define LW_DISPTEST_DSI_SC_CORE_DAC1_SET_CONTROL                        0xf9
#define LW_DISPTEST_DSI_SC_CORE_DAC1_SET_CONTROL_ARM                    0xfa
#define LW_DISPTEST_DSI_SC_CORE_DAC2_SET_CONTROL                        0xfb
#define LW_DISPTEST_DSI_SC_CORE_DAC2_SET_CONTROL_ARM                    0xfc
#define LW_DISPTEST_DSI_SC_CORE_SOR0_SET_CONTROL                        0xfd
#define LW_DISPTEST_DSI_SC_CORE_SOR0_SET_CONTROL_ARM                    0xfe
#define LW_DISPTEST_DSI_SC_CORE_SOR1_SET_CONTROL                        0xff
#define LW_DISPTEST_DSI_SC_CORE_SOR1_SET_CONTROL_ARM                    0x100
#define LW_DISPTEST_DSI_SC_CORE_PIOR0_SET_CONTROL                       0x101
#define LW_DISPTEST_DSI_SC_CORE_PIOR0_SET_CONTROL_ARM                   0x102
#define LW_DISPTEST_DSI_SC_CORE_PIOR1_SET_CONTROL                       0x103
#define LW_DISPTEST_DSI_SC_CORE_PIOR1_SET_CONTROL_ARM                   0x104
#define LW_DISPTEST_DSI_SC_CORE_PIOR2_SET_CONTROL                       0x105
#define LW_DISPTEST_DSI_SC_CORE_PIOR2_SET_CONTROL_ARM                   0x106
#define LW_DISPTEST_DSI_SC_CORE_NEW_CONTEXT_DMA_NOTIFIER                0x107
#define LW_DISPTEST_DSI_SC_CORE_SET_CONTEXT_DMA_NOTIFIER                0x108
#define LW_DISPTEST_DSI_SC_CORE_SET_LWRSOR_BASEADR                      0x109
#define LW_DISPTEST_DSI_SC_CORE_SET_LWRSOR_LIMIT                        0x10a
#define LW_DISPTEST_DSI_SC_CORE_SET_ISO_BASEADR                         0x10b
#define LW_DISPTEST_DSI_SC_CORE_SET_ISO_LIMIT                           0x10c
#define LW_DISPTEST_DSI_SC_CORE_SET_ISO_TARGET                          0x10d
#define LW_DISPTEST_DSI_SC_CORE_NEW_OFFSET_NOTIFIER                     0x10e
#define LW_DISPTEST_DSI_SC_CORE_SET_NOTIFIER_CONTROL                    0x10f
#define LW_DISPTEST_DSI_SC_CORE_SET_VGA_VIEWPORT_SIZE_IN                0x110
#define LW_DISPTEST_DSI_SC_CORE_SET_VGA_VIEWPORT_SIZE_IN_ARM            0x111
#define LW_DISPTEST_DSI_SC_CORE_DAC0_SET_ENCODE_QUALITY                 0x112
#define LW_DISPTEST_DSI_SC_CORE_DAC0_SET_ENCODE_QUALITY_ARM             0x113
#define LW_DISPTEST_DSI_SC_CORE_DAC1_SET_ENCODE_QUALITY                 0x114
#define LW_DISPTEST_DSI_SC_CORE_DAC1_SET_ENCODE_QUALITY_ARM             0x115
#define LW_DISPTEST_DSI_SC_CORE_DAC2_SET_ENCODE_QUALITY                 0x116
#define LW_DISPTEST_DSI_SC_CORE_DAC2_SET_ENCODE_QUALITY_ARM             0x117
#define LW_DISPTEST_DSI_SC_CORE_DAC0_SET_POLARITY                       0x118
#define LW_DISPTEST_DSI_SC_CORE_DAC0_SET_POLARITY_ARM                   0x119
#define LW_DISPTEST_DSI_SC_CORE_DAC1_SET_POLARITY                       0x11a
#define LW_DISPTEST_DSI_SC_CORE_DAC1_SET_POLARITY_ARM                   0x11b
#define LW_DISPTEST_DSI_SC_CORE_DAC2_SET_POLARITY                       0x11c
#define LW_DISPTEST_DSI_SC_CORE_DAC2_SET_POLARITY_ARM                   0x11d
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_LEGACY_CRC_CONTROL            0x11e
#define LW_DISPTEST_DSI_SC_CORE_HEAD0_SET_LEGACY_CRC_CONTROL_ARM        0x11f
#define LW_DISPTEST_DSI_SC_CORE_TMP_DELTA                               0x120
#define LW_DISPTEST_DSI_SC_CORE_TMP_SHORT                               0x121
#define LW_DISPTEST_DSI_SC_CORE_LINE_STORE_SIZE                         0x122
#define LW_DISPTEST_DSI_SC_CORE_MODE_SWITCH_CHECKS_REQUIRED             0x123
#define LW_DISPTEST_DSI_SC_CORE_BLOCK_HEIGHT                            0x124
#define LW_DISPTEST_DSI_SC_CORE_BLOCK_HEIGHT_MASK                       0x125
#define LW_DISPTEST_DSI_SC_CORE_PIXEL_SHIFT                             0x126
#define LW_DISPTEST_DSI_SC_CORE_WIDTH_BYTES                             0x127
#define LW_DISPTEST_DSI_SC_CORE_HEIGHT_LINES                            0x128
#define LW_DISPTEST_DSI_SC_CORE_HEIGHT_GOBS                             0x129
#define LW_DISPTEST_DSI_SC_CORE_BUFFER_SIZE_GOBS                        0x12a
#define LW_DISPTEST_DSI_SC_CORE_LWRSOR_SIZE_GOBS                        0x12b
#define LW_DISPTEST_DSI_SC_CORE_FILTER_MODE444                          0x12c
#define LW_DISPTEST_DSI_SC_CORE_TMP_OFFSET                              0x12d
#define LW_DISPTEST_DSI_SC_CORE_FORCE_INTERRUPT_RM                      0x12e
#define LW_DISPTEST_DSI_SC_CORE_MODE_NOT_DRIVER                         0x12f
#define LW_DISPTEST_DSI_SC_BASE_PIXEL_DEPTH                             0x130
#define LW_DISPTEST_DSI_SC_BASE_PIXEL_SHIFT                             0x131
#define LW_DISPTEST_DSI_SC_BASE_BLOCK_HEIGHT                            0x132
#define LW_DISPTEST_DSI_SC_BASE_BLOCK_HEIGHT_MASK                       0x133
#define LW_DISPTEST_DSI_SC_BASE_CHECK_SECOND_SURFACE                    0x134
#define LW_DISPTEST_DSI_SC_BASE_RESET_SPEC_FLIP_SEQ                     0x135
#define LW_DISPTEST_DSI_SC_BASE_USING_SURFACE0                          0x136
#define LW_DISPTEST_DSI_SC_BASE_USING_SURFACE1                          0x137
#define LW_DISPTEST_DSI_SC_BASE_USING_BASE_LUT                          0x138
#define LW_DISPTEST_DSI_SC_BASE_USING_OUTPUT_LUT                        0x139
#define LW_DISPTEST_DSI_SC_BASE_CHECK_SUB_SURFACE                       0x13a
#define LW_DISPTEST_DSI_SC_BASE_WIDTH_BYTES                             0x13b
#define LW_DISPTEST_DSI_SC_BASE_HEIGHT_LINES                            0x13c
#define LW_DISPTEST_DSI_SC_BASE_HEIGHT_GOBS                             0x13d
#define LW_DISPTEST_DSI_SC_BASE_BUFFER_SIZE_GOBS                        0x13e
#define LW_DISPTEST_DSI_SC_BASE_TMP_OFFSET                              0x13f
#define LW_DISPTEST_DSI_SC_OVERLAY_PIXEL_DEPTH                          0x140
#define LW_DISPTEST_DSI_SC_OVERLAY_PIXEL_SHIFT                          0x141
#define LW_DISPTEST_DSI_SC_OVERLAY_BLOCK_HEIGHT                         0x142
#define LW_DISPTEST_DSI_SC_OVERLAY_BLOCK_HEIGHT_MASK                    0x143
#define LW_DISPTEST_DSI_SC_OVERLAY_WIDTH_BYTES                          0x144
#define LW_DISPTEST_DSI_SC_OVERLAY_HEIGHT_LINES                         0x145
#define LW_DISPTEST_DSI_SC_OVERLAY_HEIGHT_GOBS                          0x146
#define LW_DISPTEST_DSI_SC_OVERLAY_BUFFER_SIZE_GOBS                     0x147
#define LW_DISPTEST_DSI_SC_OVERLAY_OVERLAY_ACTIVE                       0x148

/*
 * LW5070_CTRL_CMD_SET_ERRMASK
 *
 * #define's for DispTest.ControlSetErrorMask
 *
 */

#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_DISABLE                   (0x00000000)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_ALL                       (0x00000001)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_ALL_ARG                   (0x00000002)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_ALL_STATE                 (0x00000003)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_METHOD_ARG                (0x00000004)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_METHOD_STATE              (0x00000005)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_MODE_STATE_CODE                (0x00000006)

#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_NONE                                        (0x00000000)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507A_ILWALID_01                             (0x00000001)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507A_ILWALID_CHECK                          (0x00000002)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507A_ILWALID_ENUM_RANGE                     (0x00000003)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507B_ILWALID_CHECK                          (0x00000004)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507B_ILWALID_ENUM_RANGE                     (0x00000005)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_CHECK                          (0x00000006)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_CORE_CONSISTENCY               (0x00000007)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_ENUM_RANGE                     (0x00000008)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_IMPROPER_SURFACE_SPECIFICATION (0x00000009)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_IMPROPER_USAGE                 (0x0000000A)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_INTERNAL                       (0x0000000B)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_LUT_VIOLATION                  (0x0000000C)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_NOTIFIER_VIOLATION             (0x0000000D)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_SEMAPHORE_VIOLATION            (0x0000000E)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507C_ILWALID_SURFACE_VIOLATES_CONTEXT_DMA   (0x0000000F)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_BLOCKING_VIOLATION             (0x00000010)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_CHECK                          (0x00000011)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_CONFIGURATION                  (0x00000012)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_LWRSOR_VIOLATION               (0x00000013)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_ENUM_RANGE                     (0x00000014)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_IMPROPER_SURFACE_SPECIFICATION (0x00000015)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_INTERNAL                       (0x00000016)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_ILWALID_RASTER                 (0x00000017)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_ISO_VIOLATION                  (0x00000018)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_LOCKING_VIOLATION              (0x00000019)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_LUT_VIOLATION                  (0x0000001A)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_NOTIFIER_VIOLATION             (0x0000001B)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_SCALING_VIOLATION              (0x0000001C)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_SURFACE_VIOLATES_CONTEXT_DMA   (0x0000001D)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507D_ILWALID_VIEWPORT_VIOLATION             (0x0000001E)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_CHECK                          (0x0000001F)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_CORE_CONSISTENCY               (0x00000020)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_ENUM_RANGE                     (0x00000021)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_IMPROPER_SURFACE_SPECIFICATION (0x00000022)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_IMPROPER_USAGE                 (0x00000023)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_INTERNAL                       (0x00000024)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_NOTIFIER_VIOLATION             (0x00000025)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_SEMAPHORE_VIOLATION            (0x00000026)
#define LW_DISPTEST_CONTROL_SET_ERRMASK_ERRCODE_507E_ILWALID_SURFACE_VIOLATES_CONTEXT_DMA   (0x00000027)

/*
 * LW5070_CTRL_CMD_GET_DAC_PWR
 *
 * #define's for DispTest.ControlGetDacPwrMode
 *
 */
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_HSYNC                            1:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_HSYNC_ENABLE            (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_HSYNC_LO                (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_HSYNC_HI                (0x00000002)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_VSYNC                            1:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_VSYNC_ENABLE            (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_VSYNC_LO                (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_VSYNC_HI                (0x00000002)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_DATA                             1:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_DATA_ENABLE             (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_DATA_LO                 (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_DATA_HI                 (0x00000002)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_PWR                              0:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_PWR_OFF                 (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_NORMAL_PWR_ON                  (0x00000001)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_HSYNC                              1:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_HSYNC_ENABLE              (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_HSYNC_LO                  (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_HSYNC_HI                  (0x00000002)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_VSYNC                              1:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_VSYNC_ENABLE              (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_VSYNC_LO                  (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_VSYNC_HI                  (0x00000002)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_DATA                               1:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_DATA_ENABLE               (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_DATA_LO                   (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_DATA_HI                   (0x00000002)

#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_PWR                                0:0
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_PWR_OFF                   (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_PWR_SAFE_PWR_ON                    (0x00000001)

/*
 * LW5070_CTRL_CMD_SET_DAC_PWR
 *
 * #define's for DispTest.ControlSetDacPwrMode
 *
 */

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_HSYNC                            1:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_HSYNC_ENABLE            (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_HSYNC_LO                (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_HSYNC_HI                (0x00000002)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_VSYNC                            1:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_VSYNC_ENABLE            (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_VSYNC_LO                (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_VSYNC_HI                (0x00000002)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_DATA                             1:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_DATA_ENABLE             (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_DATA_LO                 (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_DATA_HI                 (0x00000002)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_PWR                              0:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_PWR_OFF                 (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_NORMAL_PWR_ON                  (0x00000001)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_HSYNC                              1:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_HSYNC_ENABLE              (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_HSYNC_LO                  (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_HSYNC_HI                  (0x00000002)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_VSYNC                              1:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_VSYNC_ENABLE              (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_VSYNC_LO                  (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_VSYNC_HI                  (0x00000002)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_DATA                               1:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_DATA_ENABLE               (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_DATA_LO                   (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_DATA_HI                   (0x00000002)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_PWR                                0:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_PWR_OFF                   (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_SAFE_PWR_ON                    (0x00000001)

#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_SPECIFIED_NORMAL                  0:0
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_SPECIFIED_NORMAL_NO      (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_SPECIFIED_NORMAL_YES     (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_SPECIFIED_SAFE                    1:1
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_SPECIFIED_SAFE_NO        (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_SPECIFIED_SAFE_YES       (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_FORCE_SWITCH                      2:2
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_FORCE_SWITCH_NO          (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_PWR_FLAGS_FORCE_SWITCH_YES         (0x00000001)

#define LW_DISPTEST_SV_RESTART_MODE_WHICH_SV_ONE            (0x00000000)
#define LW_DISPTEST_SV_RESTART_MODE_WHICH_SV_TWO            (0x00000001)
#define LW_DISPTEST_SV_RESTART_MODE_WHICH_SV_THREE          (0x00000002)

/*
 * LW5070_CTRL_CMD_GET_PREV_MODESWITCH_FLAGS
 *
 * #define's for DispTest.ControlGetPrevModeSwitchFlags
 *
 */
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_BLANK_HEAD0_NO     (0x00000000)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_BLANK_HEAD0_YES    (0x00000001)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_BLANK_HEAD1_NO     (0x00000000)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_BLANK_HEAD1_YES    (0x00000001)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_SHUTDOWN_HEAD0_NO  (0x00000000)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_SHUTDOWN_HEAD0_YES (0x00000001)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_SHUTDOWN_HEAD1_NO  (0x00000000)
#define LW_DISPTEST_CONTROL_GET_PREV_MODESWITCH_FLAGS_SHUTDOWN_HEAD1_YES (0x00000001)

/*
 * LW5070_CTRL_CMD_GET_DAC_LOAD
 *
 * #define's for DispTest.ControlGetDacLoad
 *
 */
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE                               2:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE_INIT                 (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE_OFF                  (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE_CONT_DC              (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE_CONT_AC              (0x00000002)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE_AUTO_DC              (0x00000003)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_MODE_AUTO_AC              (0x00000004)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_VAL_DC                             9:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_VAL_DC_INIT               (0x00000000)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_VAL_AC                             9:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_VAL_AC_INIT               (0x00000000)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_AUTO                           0:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_AUTO_INIT             (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_AUTO_100MS            (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_AUTO_1000MS           (0x00000001)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_DC                             9:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_DC_INIT               (0x00000000)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_SAMPLE                         9:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_PER_SAMPLE_INIT           (0x00000000)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_0                                  0:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_0_LOAD                    (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_0_NO_LOAD                 (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_1                                  1:1
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_1_LOAD                    (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_1_NO_LOAD                 (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_2                                  2:2
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_2_LOAD                    (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_2_NO_LOAD                 (0x00000001)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_3                                  3:3
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_3_LOAD                    (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_3_NO_LOAD                 (0x00000001)

#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_STATUS                             0:0
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_STATUS_INIT               (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_STATUS_ILWALID            (0x00000000)
#define LW_DISPTEST_CONTROL_GET_DAC_LOAD_STATUS_VALID              (0x00000001)

/*
 * LW5070_CTRL_CMD_SET_DAC_LOAD
 *
 * #define's for DispTest.ControlSetDacLoad
 *
 */
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE                                   2:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE_INIT                     (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE_OFF                      (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE_CONT_DC                  (0x00000001)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE_CONT_AC                  (0x00000002)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE_AUTO_DC                  (0x00000003)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_MODE_AUTO_AC                  (0x00000004)

#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_VAL_DC                                 9:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_VAL_DC_INIT                   (0x00000000)

#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_VAL_AC                                 9:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_VAL_AC_INIT                   (0x00000000)

#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_AUTO                               0:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_AUTO_INIT                 (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_AUTO_100MS                (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_AUTO_1000MS               (0x00000001)

#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_DC                                 9:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_DC_INIT                   (0x00000000)

#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_SAMPLE                             9:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_PER_SAMPLE_INIT               (0x00000000)

#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_FLAGS_SKIP_WAIT_FOR_VALID              0:0
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_FLAGS_SKIP_WAIT_FOR_VALID_NO  (0x00000000)
#define LW_DISPTEST_CONTROL_SET_DAC_LOAD_FLAGS_SKIP_WAIT_FOR_VALID_YES (0x00000001)

/*
 * LW_DISPTEST_GET_OVERLAY_FLIPCOUNT
 *
 * #define's for DispTest.ControlGetOverlayFlipCount()
 *
 */
#define LW_DISPTEST_CONTROL_GET_OVERLAY_FLIPCOUNT_VALUE                    11:0

/*
 * LW_DISPTEST_SET_OVERLAY_FLIPCOUNT
 *
 * #define's for DispTest.ControlSetOverlayFlipCount()
 *
 */
#define LW_DISPTEST_CONTROL_SET_OVERLAY_FLIPCOUNT_FORCECOUNT                    0:0
#define LW_DISPTEST_CONTROL_SET_OVERLAY_FLIPCOUNT_FORCECOUNT_INIT      (0x00000000)
#define LW_DISPTEST_CONTROL_SET_OVERLAY_FLIPCOUNT_FORCECOUNT_DISABLE   (0x00000000)
#define LW_DISPTEST_CONTROL_SET_OVERLAY_FLIPCOUNT_FORCECOUNT_ENABLE    (0x00000001)

/*
 * LW_DISPTEST_SET_DMI_ELV
 *
 * #define's for DispTest.ControlSetDmiElv()
 *
 */
#define LW_DISPTEST_CONTROL_SET_DMI_ELV_ADVANCE                         1
#define LW_DISPTEST_CONTROL_SET_DMI_ELV_MIN_DELAY                       2

/*
 * LW_DISPTEST_CONTROL_SET_ACTIVE_SUBDEVICE
 *
 * #define's for DispTest.ControlSetActiveSubdevice()
 *
 */
#define LW_DISPTEST_CONTROL_SET_ACTIVE_SUBDEVICE_BROADCAST                  0
#define LW_DISPTEST_CONTROL_SET_ACTIVE_SUBDEVICE_GPU(x)                     x+1

/*
 * LW_DISPTEST_LOOKUP_DISPLAY_ID
 *
 * #define's for DispTest.LookupDisplayId()
 * NOTE: these are copies of LW0073_CTRL_SPECIFIC_OR_TYPE_*, so
 * hopefully those do not change!
 *
 */
#define LW_DISPTEST_LOOKUP_DISPLAY_ID_OR_TYPE_NONE                     0x00000000
#define LW_DISPTEST_LOOKUP_DISPLAY_ID_OR_TYPE_DAC                      0x00000001
#define LW_DISPTEST_LOOKUP_DISPLAY_ID_OR_TYPE_SOR                      0x00000002
#define LW_DISPTEST_LOOKUP_DISPLAY_ID_OR_TYPE_PIOR                     0x00000003
#define LW_DISPTEST_LOOKUP_DISPLAY_ID_OR_TYPE_WBOR                     0x00000004

#endif
