#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2016-2021 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

pvs_release_files += $(PVS_STAT_DIR)/ausvrl8775.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8723.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8752.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8767.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8786.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8755.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8784.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8785.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8782.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8783.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8761.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8728.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8729.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8762.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8609.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8720.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8605.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8666.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8602.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8726.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8727.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8604.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8725.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8660.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8741.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8747.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8667.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8709.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8745.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8773.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8758.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8722.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8739.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8610.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8736.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8734.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8715.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8714.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8717.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8716.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8711.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8659.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8713.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8712.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8654.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8657.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8719.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8718.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8781.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8742.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8763.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8614.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8733.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8740.js


#Coverage EVs
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8614_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8654_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8655_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8656_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8657_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8658_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8661_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8662_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8663_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8666_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8668_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8669_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8670_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8671_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8672_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8673_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8674_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8678_cov.js
pvs_release_files += $(PVS_STAT_DIR)/ausvrl8682_cov.js

