#!/bin/sh

# pmu-config
# just run rmconfig using our config file

# bail on any error
set -e

[ -f pmu-config.cfg ]  ||  cd ../config
[ -f pmu-config.cfg ]  ||  { echo Cannot find pmu-config.cfg >&2; exit 1; }

cd ../prod_app

# NOTE: '--mode pmu-config' must be the first argument to rmconfig
exec ${PERL:-perl} ../../drivers/common/chip-config/chip-config.pl \
                   --mode pmu-config \
                   --config ../config/pmu-config.cfg \
                   --source-root ../prod_app \
                   "$@"
