/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2020-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#include "lwriscv/manifest_gh100.h"


const PKC_VERIFICATION_MANIFEST manifest = {
    // Decrytpted part of manifest
    .stage1RSA3KSigProd     = {0, },
    .stage1RSA3KSigDebug    = {0, },
    .magicNumberStage1      = 0x42,
    .bUseDevKey             = TRUE,
    .manifestEncParams      = {
        // MK TODO: check endiannes and if we care about that field on non-fsp
        .encryptionDerivationString = "",
        .iv                 = {0x69, 0xef, 0xd0, 0x27, 0x8a, 0xca, 0xbb, 0xc4,
                               0xcb, 0xc8, 0x37, 0x34, 0x04, 0xfc, 0xb8, 0x8c},

        .authTag            = {0, },
    },

    // Encrypted part of manifest (stage 1)
    .version               = 0x01,
    .ucodeId               = 0x04,  // See https://confluence.lwpu.com/display/GFS/Ucode+ID+Assignment
    .ucodeVersion          = 0x00,  // Post-QS signed
    .bRelaxedVersionCheck  = TRUE,  // Allow >= check for ucode version in BR revocation
    .engineIdMask          = ENGINE_TO_ENGINE_ID_MASK(SEC),    // Base 1
    // This field will be patched during build
    .itcmSizeIn256Bytes    = (LWRISCV_APP_IMEM_LIMIT) / 256,    // NA, incorrect value will not work on boot
    // This field will be patched during build
    .dtcmSizeIn256Bytes    = (LWRISCV_APP_DMEM_LIMIT) / 256,    // NA, incorrect value will not work on boot
    .fmcHashPadInfoBitMask = 0x00000000,            // LSB determines if PDI is pre-pended to the FMC before hashing
    .fmcEncParams          = {
        // NOT AUTOGENERATED! also must be !=0
        // MK TODO: check endiannes
        .encryptionDerivationString = "",
        .iv                 = {0x69, 0xef, 0xd0, 0x27, 0x8a, 0xca, 0xbb, 0xc4,
                               0xcb, 0xc8, 0x37, 0x34, 0x04, 0xfc, 0xb8, 0x8c},
        .authTag            = {0, },
    },
    // Need a checklist that says this cannot be 0
    // This field will be patched by siggen
    .digest                = { 0x00000000, 0x00000000, 0x00000000, 0x00000000,      // NA, patched by siggen when signing
                               0x00000000, 0x00000000, 0x00000000, 0x00000000,
                               0x00000000, 0x00000000, 0x00000000, 0x00000000 },
    .secretMask            = {
        .scpSecretMask     = 0x0,                       // SCP 'secret' instrlwtion is not allowed
        .scpSecretMaskLock = 0xFFFFFFFFFFFFFFFFULL,     // This mask is locked and cannot be changed
    },
    .debugAccessControl    = {
        .dbgctl =
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STOP,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RUN,    _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STEP,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_J,      _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_EMASK,  _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RREG,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WREG,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RDM,    _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WDM,    _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RSTAT,  _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_IBRKPT, _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RCSR,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WCSR,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RPC,    _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RFREG,  _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WFREG,  _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _START_IN_ICD,     _FALSE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _SINGLE_STEP_MODE, _DISABLE),
        .dbgctlLock = 0,
    },
    .bDICE = FALSE,
    .bKDF  = FALSE,                     // PMU Steady State does not use fuse keys
    .bCertCA = FALSE,
    .bAttester = FALSE,

    .mspm  = {
        .mplm  = (LW_RISCV_CSR_MSPM_MPLM_LEVEL3),
        .msecm = LW_RISCV_CSR_MSPM_MSECM_SEC
    },

    .kdfConstant = { 0 },   // PMU does not use KDF (for decrypt fuse key)

    .deviceMap.deviceMap = {
        DEVICEMAP(_MMODE,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_RISCV_CTL,      _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_PIC,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_TIMER,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_HOSTIF,         _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_DMA,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        // PMB must be unlocked so someone can write LOCKPMB (and then disable/lock it)
        DEVICEMAP(_PMB,            _ENABLE,  _ENABLE,  _UNLOCKED) |
        DEVICEMAP(_DIO,            _ENABLE,  _ENABLE,  _LOCKED  ),

        DEVICEMAP(_KEY,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_DEBUG,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SHA,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_KMEM,           _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_BROM,           _ENABLE,  _DISABLE, _LOCKED  ) | // BROM enforced
        DEVICEMAP(_ROM_PATCH,      _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_IOPMP,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_NOACCESS,       _DISABLE, _DISABLE, _LOCKED  ), // Empty Group

        DEVICEMAP(_SCP,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_FBIF,           _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_FALCON_ONLY,    _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_PRGN_CTL,       _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP0, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP1, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP2, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP3, _ENABLE,  _ENABLE,  _LOCKED  ),

        DEVICEMAP(_PLM,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_HUB_DIO,        _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_RESET,          _ENABLE,  _ENABLE,  _LOCKED  ),
    },

    .corePmp = {
        .cfg = {
            [0] = // PMP entry 0..7 -> pmpcfg0
            PMP_ENTRY(_DENIED, _DENIED, _DENIED, _NAPOT, _UNLOCK, 0)        | // IMEM FMC, access block for S/U *MUST BE UNLOCKED*
            PMP_ENTRY(_DENIED, _DENIED, _DENIED, _NAPOT, _UNLOCK, 1)        | // DMEM FMC, access blocks for S/U *MUST BE UNLOCKED*
            PMP_ENTRY(_PERMITTED, _DENIED, _PERMITTED, _NAPOT, _LOCK, 2)    | // IMEM FMC, write block for ALL *MUST BE LOCKED*
            PMP_ENTRY(_PERMITTED, _PERMITTED, _PERMITTED, _NAPOT, _LOCK, 3) | // IMEM, R *W* X
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _NAPOT, _LOCK, 4) | // DMEM, RW
            PMP_ENTRY(_PERMITTED, _PERMITTED, _PERMITTED, _NAPOT, _LOCK, 5) | // EMEM, RW
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _NAPOT, _LOCK, 6) | // LOCALIO, RW
            PMP_ENTRY_OFF(7), // TOR start for PRI (se next)
            [1] = // PMP entry 8..15 -> pmpcfg2
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _TOR,   _LOCK, 0) | // TOR - PRI - RW
            PMP_ENTRY(_PERMITTED, _PERMITTED, _PERMITTED, _TOR,   _LOCK, 1)    | // TOR - FBGPA - RWX
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED, _TOR,   _LOCK, 2),     // TOR - GVA/SYSGPA - RWX (X for inst_in_sys)
            [2] = 0, // PMP entry 16..23 -> extpmp0
            [3] = 0, // PMP entry 24-31 -> extpmp2
        },
        .addr = {
            // PMPADDR
            IOPMPADDR_LO_IMEM(SEPKERN_IMEM_LIMIT - 1), // PMPADDR(0)
            IOPMPADDR_LO_DMEM(SEPKERN_DMEM_LIMIT - 1), // PMPADDR(1)
            IOPMPADDR_LO_IMEM(SEPKERN_IMEM_LIMIT - 1), // PMPADDR(2)
            0x000000000004FFFF, // IMEM (why are we not using IMEM START/END? Should probably write NAPOT macros, if thats a thing)
            0x000000000006FFFF, // DMEM (Need to double check the start/end, can someone who know NAPOT do this without looking at Lily's code?)
            0x000000000048FFFF, // EMEM
            ((LW_RISCV_AMAP_INTIO_START >> 2) | ((LW_RISCV_AMAP_INTIO_SIZE - 1) >> 3)), // LOCALIO
            (LW_RISCV_AMAP_PRIV_START >> 2),   // PRI start
            (LW_RISCV_AMAP_PRIV_END   >> 2),   // PRI end
            (LW_RISCV_AMAP_FBGPA_END  >> 2),   // FBGPA end, do we not want to mark the address hole (between PRIV End and GPA start as all denined)?
            (LW_RISCV_AMAP_GVA_END    >> 2),   // End of GVA (think we should have separate GVA and SYSGPA entries?)
            0x0, 0x0, 0x0, 0x0, 0x0,      // 11-15
            // NEXTPMPADDR
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 16-23
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 24-31
        },
    },

    // IO_PMP_MODE - NAPOT for all entries as that's the only mode we support
    .ioPmpMode = 0xffffffffffffffff,

    .ioPmp.entry = {
    },

    .numberOfValidPairs      = 2,

    .registerPair.entries    = {
        [0] = {
            .addr    = LW_PRGNLCL_RISCV_BR_PRIV_LOCKDOWN,
            .andMask = 0,
            .orMask  = DRF_DEF(_PRGNLCL, _RISCV_BR_PRIV_LOCKDOWN, _LOCK, _UNLOCKED),
        },
        [1] = {
            .addr    = LW_PRGNLCL_RISCV_TRACECTL,
            .andMask = 0,
            .orMask  = DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _MODE, _REDUCED)      |
                       DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _MMODE_ENABLE, _TRUE) |
                       DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _SMODE_ENABLE, _TRUE) |
                       DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _UMODE_ENABLE, _TRUE),
        },
    },
};

