# https://wiki.lwpu.com/engwiki/index.php/Resman/Resman_Components/Clocks/UniversalClockTest

# If this test fails, please file a bug or contact sw-gpu-rm-clocks-dev.

# Partial P-State for gpc2clk
name=gpc2clk
gpc2clk.freq = 3400MHz:-FORCE_BYPASS:+FORCE_PLL, 1400MHz:-FORCE_BYPASS:+FORCE_PLL, 540MHz:-FORCE_BYPASS:+FORCE_PLL, 1800MHz:-FORCE_BYPASS:+FORCE_PLL, 2397MHz:-FORCE_BYPASS:+FORCE_PLL, 1700MHz:-FORCE_BYPASS:+FORCE_PLL, 2450MHz:-FORCE_BYPASS:+FORCE_PLL, 955MHz:-FORCE_BYPASS:+FORCE_PLL, 1850MHz:-FORCE_BYPASS:+FORCE_PLL, 731MHZ:-FORCE_BYPASS:+FORCE_PLL

# Partial P-State for ltc2clk
name=ltc2clk
ltc2clk.freq = 3400MHz:-FORCE_BYPASS:+FORCE_PLL, 2680MHz:-FORCE_BYPASS:+FORCE_PLL, 1700MHz:-FORCE_BYPASS:+FORCE_PLL, 540MHz:-FORCE_BYPASS:+FORCE_PLL, 2800MHz:-FORCE_BYPASS:+FORCE_PLL, 967MHz:-FORCE_BYPASS:+FORCE_PLL, 1080MHz:-FORCE_BYPASS:+FORCE_PLL, 3115MHz:-FORCE_BYPASS:+FORCE_PLL, 976MHz:-FORCE_BYPASS:+FORCE_PLL, 2231MHz:-FORCE_BYPASS:+FORCE_PLL

# Partial P-State for xbar2clk
name=xbar2clk
xbar2clk.freq = 3400MHz:-FORCE_BYPASS:+FORCE_PLL, 540MHz:-FORCE_BYPASS:+FORCE_PLL, 2457MHz:-FORCE_BYPASS:+FORCE_PLL, 1700MHz:-FORCE_BYPASS:+FORCE_PLL, 2761MHz:-FORCE_BYPASS:+FORCE_PLL, 671MHz:-FORCE_BYPASS:+FORCE_PLL, 1080MHz:-FORCE_BYPASS:+FORCE_PLL, 2917MHz:-FORCE_BYPASS:+FORCE_PLL, 3222MHz:-FORCE_BYPASS:+FORCE_PLL, 976MHz:-FORCE_BYPASS:+FORCE_PLL

# Partial P-State for sys2clk
name=sys2clk
sys2clk.freq = 3400MHz:-FORCE_BYPASS:+FORCE_PLL, 2317MHz:-FORCE_BYPASS:+FORCE_PLL, 540MHz:-FORCE_BYPASS:+FORCE_PLL, 1900MHz:-FORCE_BYPASS:+FORCE_PLL, 869MHZ:-FORCE_BYPASS:+FORCE_PLL, 1700MHz:-FORCE_BYPASS:+FORCE_PLL,  1080MHz:-FORCE_BYPASS:+FORCE_PLL, 1376MHz:-FORCE_BYPASS:+FORCE_PLL, 2900MHz:-FORCE_BYPASS:+FORCE_PLL, 850MHz:-FORCE_BYPASS:+FORCE_PLL

# Trial specification for pldiv sliding and dynramping test
name       = PldivSlidingTest
test       = initPstate:gpc2clk, initPstate:ltc2clk, initPstate:xbar2clk, initPstate:sys2clk
rmapi      = clk
order      = sequence
tolerance  = 0.02, 0.02
