/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2016-2019 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#ifndef FBFLCN_REVOCATION_H
#define FBFLCN_REVOCATION_H

#include <lwtypes.h>
#include "lwuproc.h"
#include "config/fbfalcon-config.h"


#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU102
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU102   0x1e00
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU102
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU102     0x1e3f
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU102_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU102_B 0x1e40
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU102_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU102_B   0x1e7f
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU104
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU104   0x1e80
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU104
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU104     0x1ebf
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU104_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU104_B 0x1ec0
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU104_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU104_B   0x1eff
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU106
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU106   0x1f00
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU106
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU106     0x1f3f
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU106_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU106_B 0x1f40
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU106_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU106_B   0x1f7f
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU108
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU108   0x2000
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU108
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU108     0x203f
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU108_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU108_B 0x2040
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU108_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU108_B   0x207f
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU116
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU116   0x2180
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU116
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU116     0x21bf
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU116_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU116_B 0x21c0
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU116_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU116_B   0x21ff
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU117
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU117   0x1f80
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU117
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU117     0x1fbf
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_TU117_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_TU117_B 0x1fc0
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_TU117_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_TU117_B   0x1fff
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_GA100
#define LW_PCI_DEV_ID_RANGE_START_VGA_GA100   0x2080
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_GA100
#define LW_PCI_DEV_ID_RANGE_END_VGA_GA100     0x20bf
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_GA100_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_GA100_B 0x20c0
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_GA100_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_GA100_B   0x20ff
#endif

#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_GA102
#define LW_PCI_DEV_ID_RANGE_START_VGA_GA102   0x2200
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_GA102
#define LW_PCI_DEV_ID_RANGE_END_VGA_GA102     0x223f
#endif
#ifndef LW_PCI_DEV_ID_RANGE_START_VGA_GA102_B
#define LW_PCI_DEV_ID_RANGE_START_VGA_GA102_B 0x2240
#endif
#ifndef LW_PCI_DEV_ID_RANGE_END_VGA_GA102_B
#define LW_PCI_DEV_ID_RANGE_END_VGA_GA102_B   0x227f
#endif

// fbflcn ucode revision for each get
#define FBFLCN_UCODE_BUILD_VERSION_TU102 0x1
#define FBFLCN_UCODE_BUILD_VERSION_TU104 0x1
#define FBFLCN_UCODE_BUILD_VERSION_TU106 0x1
#define FBFLCN_UCODE_BUILD_VERSION_TU116 0x1
#define FBFLCN_UCODE_BUILD_VERSION_TU117 0x1
#define FBFLCN_UCODE_BUILD_VERSION_GA100 0x0

#define FBFLCN_UCODE_BUILD_VERSION_GA102 0x2
#define FBFLCN_UCODE_BUILD_VERSION_GA103 0x2
#define FBFLCN_UCODE_BUILD_VERSION_GA104 0x2
#define FBFLCN_UCODE_BUILD_VERSION_GA106 0x2
#define FBFLCN_UCODE_BUILD_VERSION_GA107 0x2
#define FBFLCN_UCODE_BUILD_VERSION_GA114 0x0

#define FBFLCN_UCODE_BUILD_VERSION_AD102 0x0
#define FBFLCN_UCODE_BUILD_VERSION_AD103 0x0
#define FBFLCN_UCODE_BUILD_VERSION_AD104 0x0
#define FBFLCN_UCODE_BUILD_VERSION_AD106 0x0
#define FBFLCN_UCODE_BUILD_VERSION_AD107 0x0

#define FBFLCN_UCODE_BUILD_VERSION_GH100 0x1

#define FBFLCN_UCODE_BUILD_VERSION_GH202 0x0

#define FBFLCN_BOOT_UCODE_BUILD_VERSION_TU102 0x1
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_TU104 0x1
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_TU106 0x1
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_TU116 0x1
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_TU117 0x1

#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA100 0x0

#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GH100 0x1

// Fuse defines for Ampere, the FPF fuse can only be burnt its value will increase
// in a bar like fashion like 1,3,7...
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA102 0x2
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA102_FPF 0x3
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA103 0x2
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA103_FPF 0x3
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA104 0x2
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA104_FPF 0x3
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA106 0x2
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA106_FPF 0x3
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA107 0x2
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA107_FPF 0x3
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA114 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GA114_FPF 0x0

#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD102 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD102_FPF 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD103 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD103_FPF 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD104 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD104_FPF 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD106 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD106_FPF 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD107 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_AD107_FPF 0x0

#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GH100 0x1
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GH100_FPF 0x1
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GH202 0x0
#define FBFLCN_BOOT_UCODE_BUILD_VERSION_GH202_FPF 0x0

// fbflcn device id's for each target
#define FBFLCN_DEVICE_ID_TU102   0x1
#define FBFLCN_DEVICE_ID_TU104   0x2
#define FBFLCN_DEVICE_ID_TU106   0x3
#define FBFLCN_DEVICE_ID_TU116   0x4
#define FBFLCN_DEVICE_ID_TU117   0x5

#define CHECK_RANGE(ab,target,id) \
        do { \
            if ((devId##ab >= LW_PCI_DEV_ID_RANGE_START_##target) && (devId##ab <= LW_PCI_DEV_ID_RANGE_END_##target)) { device##ab = FBFLCN_DEVICE_ID_##id; } \
        } while (LW_FALSE);


#endif  // FBFLCN_REVOCATION_H
