# Unique profile so (Seemingly) the same configurations don't overlap
LIBLWRISCV_PROFILE := sec2-rtos-gh100

# Chip family we want to compile to
include $(LIBLWRISCV_CONFIGS)/gh100.mk

# Extra configuration
include $(LIBLWRISCV_CONFIGS)/lwriscv_s.mk

# Engine we want to compile to
include $(LIBLWRISCV_CONFIGS)/sec.mk

LWRISCV_FEATURE_START := n
LWRISCV_FEATURE_EXCEPTION := n

LWRISCV_CONFIG_DEBUG_PRINT_LEVEL := 10
LWRISCV_CONFIG_DEBUG_PRINT_METADATA_IN_BUFFER := y
LWRISCV_CONFIG_DEBUG_PRINT_USES_SWGEN := y
LWRISCV_CONFIG_DEBUG_PRINT_USES_QUEUES := y

LWRISCV_CONFIG_USE_STATUS := lwstatus

LWRISCV_APP_IMEM_LIMIT := LWRISCV_IMEM_SIZE - 0x1000
LWRISCV_APP_DMEM_LIMIT := LWRISCV_DMEM_SIZE - 0x1000

LWRISCV_FEATURE_SSP := y
LWRISCV_FEATURE_SCP := y
LWRISCV_FEATURE_DIO := y
LWRISCV_FEATURE_SHA := y
