#
# _LWRM_COPYRIGHT_BEGIN_
#
# Copyright 2011-2018 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# _LWRM_COPYRIGHT_END_
#

#
# Top-level makefile. This makefile is responsible for building the test
# binary including projects it depends on (bootloader, etc ...) across
# all config-profiles.
#

TEST_NAME := rvbl_mpu_manual

include $(LW_SOURCE)/uproc/lwriscv/bootloader_tests/common/makefile.lwmk
