#pragma once

#if LIBOS_LWRISCV < 0x200
#   define LW_PRGNLCL_FALCON_IRQSTAT                 LW_PGSP_FALCON_IRQSTAT
#   define LW_PRGNLCL_FALCON_IRQSTAT_MEMERR          LW_PGSP_FALCON_IRQSTAT_MEMERR

#   define LW_PRGNLCL_RISCV_PRIV_ERR_STAT             LW_PRISCV_RISCV_PRIV_ERR_STAT
#   define LW_PRGNLCL_RISCV_PRIV_ERR_STAT_VALID       LW_PRISCV_RISCV_PRIV_ERR_STAT_VALID
#   define LW_PRGNLCL_RISCV_PRIV_ERR_STAT_VALID_FALSE LW_PRISCV_RISCV_PRIV_ERR_STAT_VALID_FALSE

#   define LW_PRGNLCL_RISCV_HUB_ERR_STAT              LW_PRISCV_RISCV_HUB_ERR_STAT
#   define LW_PRGNLCL_RISCV_HUB_ERR_STAT_VALID        LW_PRISCV_RISCV_HUB_ERR_STAT_VALID
#   define LW_PRGNLCL_RISCV_HUB_ERR_STAT_VALID_FALSE  LW_PRISCV_RISCV_HUB_ERR_STAT_VALID_FALSE

#   define LW_PRGNLCL_FALCON_IRQSCLR                 LW_PFALCON_FALCON_IRQSCLR
#   define LW_PRGNLCL_FALCON_IRQSCLR_MEMERR          LW_PFALCON_FALCON_IRQSCLR_MEMERR
#   define LW_PRGNLCL_FALCON_IRQSCLR_MEMERR_SET      LW_PFALCON_FALCON_IRQSCLR_MEMERR_SET

#   define LW_PRGNLCL_RISCV_IRQMSET                   LW_PRISCV_RISCV_IRQMSET
#   define LW_PRGNLCL_RISCV_IRQMSET_MEMERR            LW_PRISCV_RISCV_IRQMSET_MEMERR
#   define LW_PRGNLCL_RISCV_IRQMSET_MEMERR_SET        LW_PRISCV_RISCV_IRQMSET_MEMERR_SET

#   define LW_PRGNLCL_RISCV_IRQMCLR                   LW_PRISCV_RISCV_IRQMCLR
#   define LW_PRGNLCL_RISCV_IRQMCLR_MEMERR            LW_PRISCV_RISCV_IRQMCLR_MEMERR
#   define LW_PRGNLCL_RISCV_IRQMCLR_MEMERR_SET        LW_PRISCV_RISCV_IRQMCLR_MEMERR_SET

#   define LW_PRGNLCL_RISCV_PRIV_ERR_INFO             LW_PRISCV_RISCV_PRIV_ERR_INFO
#   define LW_PRGNLCL_RISCV_PRIV_ERR_ADDR             LW_PRISCV_RISCV_PRIV_ERR_ADDR
#endif
