all: 
	gcc -Od -m64 -g -I$(LIBOS_SOURCE)/include $(LIBOS_SOURCE)/manifest-compiler/libosmc.c $(LIBOS_SOURCE)/lib/libelf.c $(LIBOS_SOURCE)/lib/libdwarf.c -I$(LW_ENGINE_MANUALS) -I$(LW_SDK_INC) -o $(OUT_DIR)/libosmc
