/**@@@+++@@@@******************************************************************
**
** Microsoft (r) PlayReady (r)
** Copyright (c) Microsoft Corporation. All rights reserved.
**
***@@@---@@@@******************************************************************
*/

#ifndef _DRMTEESUPPORTED_H_
#define _DRMTEESUPPORTED_H_ 1

#include <drmteetypes.h>
#include <oemteetypes.h>

ENTER_PK_NAMESPACE;

DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_AES128CBC_IsAES128CBCSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_AES128CTR_IsAES128CTRSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_DECRYPT_IsDECRYPTSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_DOM_IsDOMSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_H264_IsH264Supported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_LICGEN_IsLICGENSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_LICPREP_IsLICPREPSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_LPROV_IsLPROVSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_RPROV_IsRPROVSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_REVOCATION_IsREVOCATIONSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_SAMPLEPROT_IsSAMPLEPROTSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_SELWRESTOP_IsSELWRESTOPSupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_SELWRESTOP2_IsSELWRESTOP2Supported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_SELWRETIME_IsSELWRETIMESupported( DRM_VOID );
DRM_NO_INLINE DRM_API DRM_BOOL DRM_CALL DRM_TEE_IMPL_SIGN_IsSIGNSupported( DRM_VOID );

EXIT_PK_NAMESPACE;

#endif /* _DRMTEESUPPORTED_H_ */

