/*
 * Copyright 2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/*!
 * @file   soediscovery.c
 * @brief  Read the bases addresses from PTOP
 *
 * Store the Base addresses of various engines.
 */
/* ------------------------- System Includes -------------------------------- */
#include "soesw.h"
#include "dev_soe_csb.h"
#include "dev_lws_top.h"
#include "soe_bar0.h"
#include "lwlinkip_discovery.h"
#include "npgip_discovery.h"
#include "nxbar_discovery.h"

/* ------------------------- Application Includes --------------------------- */
#include "soe_objsoe.h"
#include "soe_objdiscovery.h"
#include "config/g_soe_private.h"

/* ------------------------- Type Definitions ------------------------------- */
typedef struct
{
    void (*parseEntry)(LwU32 entry, LwU32 *entryType, LwBool *entryChain);
    void (*parseEnum)(LwU32 entry, LwU32 *entryDevice, LwU32 *entryId, LwU32 *entryVersion);
    void (*handleData1)(LwU32 entry, struct OBJENGINELIST *engine, LwU32 entryDevice, LwU32 *discoveryListSize);
    void (*handleData2)(LwU32 entry, struct OBJENGINELIST *engine, LwU32 entryDevice);
}
SOE_DISCOVERY_HANDLERS_LR10;

/* ------------------------- External Definitions --------------------------- */
/* ------------------------- Static Variables ------------------------------- */
// Level1 PTOP table
static struct ENGINE_TABLE engineLookUp_LS10 [] =
{
    { LW_SWPTOP_ENUM_DEVICE_SAW, LW_DISCOVERY_ENGINE_NAME_SAW, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_GIN, LW_DISCOVERY_ENGINE_NAME_GIN, INSTANCE0},      /* NEW */
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE1 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE2 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE3 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE4 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE5 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE6 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE7 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE8 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE9 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE10 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE11 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE12 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE13 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE14 },
    { LW_SWPTOP_ENUM_DEVICE_LWLW, LW_DISCOVERY_ENGINE_NAME_LWLW_PTOP, INSTANCE15 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE1 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE2 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE3 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE4 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE5 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE6 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE7 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE8 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE9 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE10 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE11 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE12 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE13 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE14 },
    { LW_SWPTOP_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_PTOP, INSTANCE15 },
    { LW_SWPTOP_ENUM_DEVICE_NPG_BCAST, LW_DISCOVERY_ENGINE_NAME_NPG_BCAST_PTOP, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR_PTOP, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR_PTOP, INSTANCE1 },
    { LW_SWPTOP_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR_PTOP, INSTANCE2 },
    { LW_SWPTOP_ENUM_DEVICE_NXBAR_BCAST, LW_DISCOVERY_ENGINE_NAME_NXBAR_BCAST_PTOP, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_XAL, LW_DISCOVERY_ENGINE_NAME_XAL, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_SYS_PRI_HUB, LW_DISCOVERY_ENGINE_NAME_SYS_PRI_HUB, INSTANCE0 },
    { LW_SWPTOP_ENUM_DEVICE_PRI_MASTER_RS, LW_DISCOVERY_ENGINE_NAME_PRI_MASTER_RS, INSTANCE0 },
};

static struct ENGINE_TABLE engineLwlwLookUp_LS10 [] =
{
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLTLC, LW_DISCOVERY_ENGINE_NAME_LWLTLC, INSTANCE0 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLTLC, LW_DISCOVERY_ENGINE_NAME_LWLTLC, INSTANCE1 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLTLC, LW_DISCOVERY_ENGINE_NAME_LWLTLC, INSTANCE2 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLTLC, LW_DISCOVERY_ENGINE_NAME_LWLTLC, INSTANCE3 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLIPT_LNK, LW_DISCOVERY_ENGINE_NAME_LWLIPT_LINK, INSTANCE0 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLIPT_LNK, LW_DISCOVERY_ENGINE_NAME_LWLIPT_LINK, INSTANCE1 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLIPT_LNK, LW_DISCOVERY_ENGINE_NAME_LWLIPT_LINK, INSTANCE2 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_LWLIPT_LNK, LW_DISCOVERY_ENGINE_NAME_LWLIPT_LINK, INSTANCE3 },
    { LW_LWLINKIP_DISCOVERY_COMMON_DEVICE_MINION, LW_DISCOVERY_ENGINE_NAME_MINION, INSTANCE0},
};

static struct ENGINE_TABLE engineNportLookUp_LS10 [] =
{
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPORT, LW_DISCOVERY_ENGINE_NAME_NPORT, INSTANCE0 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPORT, LW_DISCOVERY_ENGINE_NAME_NPORT, INSTANCE1 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPORT, LW_DISCOVERY_ENGINE_NAME_NPORT, INSTANCE2 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPORT, LW_DISCOVERY_ENGINE_NAME_NPORT, INSTANCE3 },
};

static struct ENGINE_TABLE engineNpgBcastLookUp_LS10 [] =
{
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPORT_MULTICAST, LW_DISCOVERY_ENGINE_NAME_NPORT_MULTICAST, INSTANCE0 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG_BCAST, INSTANCE0 },
};

static struct ENGINE_TABLE engineNpgLookUp_LS10 [] =
{
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE0 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE1 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE2 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE3 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE4 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE5 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE6 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE7 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE8 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE9 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE10 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE11 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE12 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE13 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE14 },
    { LW_NPG_DISCOVERY_ENUM_DEVICE_NPG, LW_DISCOVERY_ENGINE_NAME_NPG, INSTANCE15 },
};

static struct ENGINE_TABLE engineNxbarLookUp_LS10 [] =
{
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR, INSTANCE0 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR, INSTANCE1 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR, INSTANCE2 },
};

static struct ENGINE_TABLE engineTileLookUp_LS10 [] =
{
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE0 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE1 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE2 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE3 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE4 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE5 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE6 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE7 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE8 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE9 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE10 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE, LW_DISCOVERY_ENGINE_NAME_TILE, INSTANCE11 },
};

static struct ENGINE_TABLE engineNxbarBcastLookUp_LS10 [] =
{
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_TILE_MULTICAST, LW_DISCOVERY_ENGINE_NAME_TILE_MULTICAST, INSTANCE0 },
    { LW_NXBAR_DISCOVERY_ENUM_DEVICE_NXBAR, LW_DISCOVERY_ENGINE_NAME_NXBAR_BCAST, INSTANCE0 },
};

static ENGINE_TABLES engineTables_LS10 = {
    .engineLookUp=engineLookUp_LS10,
    .sizeEngineLookUp=sizeof(engineLookUp_LS10)/sizeof((engineLookUp_LS10)[0]),
    .engineLwlwLookUp=engineLwlwLookUp_LS10,
    .sizeEngineLwlwLookUp=sizeof(engineLwlwLookUp_LS10)/sizeof((engineLwlwLookUp_LS10)[0]),
    .engineNportLookUp=engineNportLookUp_LS10,
    .sizeEngineNportLookUp=sizeof(engineNportLookUp_LS10)/sizeof((engineNportLookUp_LS10)[0]),
    .engineNpgBcastLookUp=engineNpgBcastLookUp_LS10,
    .sizeEngineNpgBcastLookUp=sizeof(engineNpgBcastLookUp_LS10)/sizeof((engineNpgBcastLookUp_LS10)[0]),
    .engineNpgLookUp=engineNpgLookUp_LS10,
    .sizeEngineNpgLookUp=sizeof(engineNpgLookUp_LS10)/sizeof((engineNpgLookUp_LS10)[0]),
    .engineNxbarLookUp=engineNxbarLookUp_LS10,
    .sizeEngineNxbarLookUp=sizeof(engineNxbarLookUp_LS10)/sizeof((engineNxbarLookUp_LS10)[0]),
    .engineTileLookUp=engineTileLookUp_LS10,
    .sizeEngineTileLookUp=sizeof(engineTileLookUp_LS10)/sizeof((engineTileLookUp_LS10)[0]),
    .engineNxbarBcastLookUp=engineNxbarBcastLookUp_LS10,
    .sizeEngineNxbarBcastLookUp=sizeof(engineNxbarBcastLookUp_LS10)/sizeof((engineNxbarBcastLookUp_LS10)[0]),
};

/*
 * Returns the chip specific engine lookup tables.
 *
 *  return ENGINE_TABLES*           Returns the chip specific engine lookup tables.
 */
PENGINE_TABLES
soeGetEngineLookup_LS10(void)
{
    return &engineTables_LS10;
}
