/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2011-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */
#include "MultiTexReg.h"
#include "notpll_test_kepler.h"
#include "power_common_kepler.h"
#include "unalmem_kepler.h"
#include "check_connect.h"
#include "check_clamp.h"
#include "check_dedicated_overt_gk110.h"
#include "check_tach_count_gk110.h"
#include "check_gsp2host_status_idle.h"
#include "check_lce2host_status_idle.h"
#include "deepL1_gen3.h"
#include "elpg_powergv_kepler.h"
#include "memsys_island.h"
#include "gc6plus_maxwell.h"
#include "gc6plus_misc.h"
#include "gc6plus.h"
#include "goodn_rst_reinit.h"
#include "dvco_sanity.h"
#include "idle_flipped.h"
#include "ad10x_hotrst_reinit.h"
#include "hotrst_reinit.h"
#include "ad10x_jtag_reg_reset_check.h"
#include "jtag_reg_reset_check.h"
#include "failsafe_overt.h"
#include "therm_overt_legacy.h"
#include "therm_overt_latch.h"
#include "xbashlwvdd_overt.h"
#include "i2cslave_fermi.h"
#include "jtag2icd_lwdec.h"
#include "jtag2icd_lwenc.h"
#include "jtag2icd_pwr.h"
#include "l1_substate.h"
#include "powerCtrlTest_maxwell.h"
#include "smartfan_sci.h"
#include "stop_clocks.h"
#include "thermal_shutdown_latch.h"
#include "pwr_tsense.h"
#include "fb_util.h"
#include "thermalctrl_maxwell.h"
#include "uart2icd_pwr.h"
#include "vgaBase.h"
#include "vid_pwm.h"
#include "wsp2pwr_conn.h"
#include "RegTestGpu.h"
#include "fbpa_cattrip.h"
#include "VR.h"
#include "t_vr_input_side_sensing.h"
//#include "blcg_mapping.h"
//#include "pascal_rtl_clocks.h"
