LWRISCV_IS_VERSION_MAJOR := 1
LWRISCV_IS_VERSION_MINOR := 1
LWRISCV_HAS_ABI := lp64
LWRISCV_HAS_ARCH := rv64im

LWRISCV64_MANUAL_CSR=dev_$(LWRISCV_IS_ENGINE)_riscv_csr_64.h
LWRISCV64_MANUAL_ADDRESS_MAP=lw_$(LWRISCV_IS_ENGINE)_riscv_address_map.h
LWRISCV64_MANUAL_LOCAL_IO=dev_$(LWRISCV_IS_ENGINE)_prgnlcl.h
