LWRISCV_IS_VERSION_MAJOR := 3
LWRISCV_IS_VERSION_MINOR := 0
LWRISCV_HAS_ABI := ilp32
LWRISCV_HAS_ARCH := rv32imc

LWRISCV32_MANUAL_CSR=dev_$(LWRISCV_IS_ENGINE)_riscv_csr_32.h
LWRISCV32_MANUAL_ADDRESS_MAP=lw_$(LWRISCV_IS_ENGINE)_riscv_address_map.h
LWRISCV32_MANUAL_LOCAL_IO=dev_$(LWRISCV_IS_ENGINE)_prgnlcl.h
