/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2020-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#include "lwriscv/manifest_t23x.h"

// IOPMP ADDR_LO entry - config bits
// This should just be 1 macro? And also needs documentation on what its doing
#define IOPMPADDR_LO_ALL_IMEM IOPMPADDR_LO_IMEM(LW_RISCV_AMAP_IMEM_SIZE - 1)
#define IOPMPADDR_LO_ALL_DMEM IOPMPADDR_LO_DMEM(LW_RISCV_AMAP_DMEM_SIZE - 1)

const PKC_VERIFICATION_MANIFEST manifest = {
    .version               = 0x1,
    .ucodeId               = 0x1,
    .ucodeVersion          = 0x2,
    .bRelaxedVersionCheck  = TRUE,
    .engineIdMask          = ENGINE_TO_ENGINE_ID_MASK(GSP),
    // This field will be patched during build
    .itcmSizeIn256Bytes    = (LWRISCV_IMEM_SIZE) / 256,
    // This field will be patched during build
    .dtcmSizeIn256Bytes    = (LWRISCV_DMEM_SIZE) / 256,
    .fmcHashPadInfoBitMask = 0x00000000,
    // NOT AUTOGENERATED! also must be !=0
    .CbcIv                 = { 0x27d0ef69, 0xc4bbca8a, 0x3437c8cb, 0x8cb8fc04 },
    // This field will be patched by siggen
    .digest                = { 0x00000000, 0x00000000, 0x00000000, 0x00000000,
                               0x00000000, 0x00000000, 0x00000000, 0x00000000 },
    .secretMask            = {
        // Enable SecretMask to access SCP when SCP Sec lockdown is enabled
        .scpSecretMask     = 0x0000000000000001ULL,
        .scpSecretMaskLock = 0xFFFFFFFFFFFFFFFFULL,
    },
    .debugAccessControl    = {
        // Enable debugging for now, let Separation Kernel disable it if needed. It will be disabled in production.
        .dbgctl =
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STOP,   _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RUN,    _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STEP,   _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_J,      _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_EMASK,  _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RREG,   _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WREG,   _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RDM,    _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WDM,    _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RSTAT,  _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_IBRKPT, _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RCSR,   _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WCSR,   _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RPC,    _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RFREG,  _DISABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WFREG,  _DISABLE ) |

            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _START_IN_ICD,     _FALSE  ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _SINGLE_STEP_MODE, _DISABLE),

        .dbgctlLock = 0xFFFFFFFF,
    },
    .bDICE = FALSE,
    .bKDF  = FALSE,
    .mspm         = {
        .mplm  = (LW_RISCV_CSR_MSPM_MPLM_LEVEL3),
        .msecm = LW_RISCV_CSR_MSPM_MSECM_SEC
    },

    .kdfConstant = { 0 },
// Locking everything in Device Map. It will be unlocked with justification.
    .deviceMap.deviceMap = {
        DEVICEMAP(_MMODE,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_RISCV_CTL,      _DISABLE, _DISABLE,  _LOCKED ) |
        DEVICEMAP(_PIC,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_TIMER,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_HOSTIF,         _DISABLE, _DISABLE,  _LOCKED ) |
        DEVICEMAP(_DMA,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        // PMB must be unlocked so someone can write LOCKPMB (and then disable/lock it)
        DEVICEMAP(_PMB,            _ENABLE,  _ENABLE,  _UNLOCKED) |
        DEVICEMAP(_DIO,            _ENABLE,  _ENABLE,  _UNLOCKED) ,

        DEVICEMAP(_KEY,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_DEBUG,          _DISABLE, _DISABLE, _LOCKED  ) |
        DEVICEMAP(_SHA,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_KMEM,           _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_BROM,           _ENABLE,  _DISABLE, _LOCKED  ) | // BROM enforced
        DEVICEMAP(_ROM_PATCH,      _DISABLE, _DISABLE,  _LOCKED ) |
        DEVICEMAP(_IOPMP,          _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_NOACCESS,       _DISABLE, _DISABLE, _LOCKED  ), // Empty Group

        DEVICEMAP(_SCP,            _ENABLE,  _ENABLE,  _LOCKED  ) |
// LWDEC has no FBIF
#if (! defined SAMPLE_PROFILE_lwdec) && (! defined SAMPLE_PROFILE_tsec)
        DEVICEMAP(_FBIF,           _ENABLE,  _ENABLE,  _LOCKED  ) |
#endif
        DEVICEMAP(_FALCON_ONLY,    _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_PRGN_CTL,       _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP0, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP1, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP2, _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP3, _ENABLE,  _ENABLE,  _LOCKED  ),

        DEVICEMAP(_PLM,            _ENABLE,  _ENABLE,  _LOCKED  ) |
        DEVICEMAP(_HUB_DIO,        _ENABLE,  _ENABLE,  _LOCKED  ),  // Secure Bus - needed for HDCP
    },

    .corePmp = {
        .pmpcfg = {
            // PMPCFG

            PMP_ENTRY(_PERMITTED, _DENIED, _PERMITTED, _NAPOT, _LOCK), // IMEM X
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _NAPOT, _LOCK), // DMEM, RW
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _NAPOT, _LOCK), // LOCAL IO, RW
            PMP_ENTRY_OFF, // TOR start for PRI (se next)
            PMP_ENTRY(_PERMITTED, _PERMITTED, _DENIED,    _TOR,   _LOCK), // TOR - PRI - RW
        },
        .pmpaddr = {
            // PMPADDR
            0x000000000004FFFF, // IMEM (why are we not using IMEM START/END? Should probably write NAPOT macros, if thats a thing)
            0x000000000006FFFF, // DMEM (Need to double check the start/end, can someone who know NAPOT do this without looking at Lily's code?)
            ((LW_RISCV_AMAP_INTIO_START >> 2) | ((LW_RISCV_AMAP_INTIO_SIZE - 1) >> 3)), // LOCALIO
            (LW_RISCV_AMAP_PRIV_START >> 2),   // PRI start
            (LW_RISCV_AMAP_PRIV_END   >> 2),   // PRI end
        },
    },

    // IO_PMP_MODE - NAPOT for all entries as that's the only mode we support
    .ioPmpMode = 0xf,

    .ioPmp = {
        .iopmpcfg = {
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER, _ALL_MASTERS_ENABLED) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),

            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_FBDMA, _ENABLE) |
	        DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_SHA, _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER, _CPDMA_ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),

            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER_FBDMA, _ENABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),

            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _READ,   _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _WRITE,  _DISABLE) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _MASTER, _ALL_MASTERS_ENABLED) |
            DRF_DEF(_PRGNLCL, _RISCV_IOPMP_CFG, _LOCK,   _LOCKED),
        },
        .iopmpaddrlo = {
            IOPMPADDR_LO_ALL_IMEM,  // IOPMPADDR(2) - Map whole IMEM aperture
            IOPMPADDR_LO_ALL_DMEM,  // IOPMPADDR(3) - Map whole DMEM aperture
	    0xFFFFFFFF,
	    0xFFFFFFFF,
        },
        .iopmpaddrhi = { // Must be always 0 for IMEM and DMEM
            0x0,
            0x0,
	    0xFFFFFFFF,
	    0xFFFFFFFF,
        },
    },

    .numberOfValidPairs = 0x0,
    .registerPair       = {
        .addr    = { },
        .andMask = { },
        .orMask  = { },
    },
};
