@startuml "Module Locking Sub-Arch Diagram"
    node "PMU microcode" {
        node "Core Firmware Layer" {
            node "Module Locking" {
                rectangle "Unit Locks"  as lock_unit
            }
        }
    }
@enduml