/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2015-2022 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#ifndef CLK_DOMAIN_3X_H
#define CLK_DOMAIN_3X_H

/*!
 * @file clk_domain_3x.h
 * @brief @copydoc clk_domain_3x.c
 */

/* ------------------------ Includes --------------------------------------- */
#include "clk/clk_domain.h"
#include "clk/clk_domain_prog.h"

/* ------------------------ Macros ----------------------------------------- */
/* ------------------------ Datatypes -------------------------------------- */
/*!
 * Clock domain info 3X structure.  Contains CLK_DOMAIN state that is specific
 * to the pstates 3.0 implemenation of CLK_DOMAINS.
 */
//! https://wiki.lwpu.com/engwiki/index.php/Resman/PState/Data_Tables/Clocks_Table/1.0_Spec
typedef struct
{
    /*!
     * CLK_DOMAIN super class.  Must always be first object in the
     * structure.
     */
    CLK_DOMAIN super;

    /*!
     * Boolean specifying whether a CLK_DOMAIN is capable of being generated by
     * a voltage-noise-aware generator such as NAFLL.
     */
    LwBool bNoiseAwareCapable;
} CLK_DOMAIN_3X;

/* ------------------------ External Definitions --------------------------- */
/* ------------------------ Function Prototypes ---------------------------- */
// BOARDOBJ interfaces
BoardObjGrpIfaceModel10ObjSet (clkDomainGrpIfaceModel10ObjSet_3X)
    GCC_ATTRIB_SECTION("imem_libClkConstruct", "clkDomainGrpIfaceModel10ObjSet_3X");

// CLK_DOMAIN_PROG interfaces
ClkDomainProgIsNoiseAware (clkDomainProgIsNoiseAware_3X)
    GCC_ATTRIB_SECTION("imem_perfVf", "clkDomainProgIsNoiseAware_3X");

/* ------------------------ Include Derived Types -------------------------- */
#include "clk/clk_domain_3x_fixed.h"
#include "clk/clk_domain_3x_prog.h"
#include "clk/clk_domain_40_prog.h"

#endif // CLK_DOMAIN_3X_H
