/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2009-2019 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/*!
 * @file   pmu_objtimer.c
 * @brief  Top-level timer object for timer functionality and HAL infrastructure.
 */

/* ------------------------- System Includes -------------------------------- */
#include "pmusw.h"

/* ------------------------- Application Includes --------------------------- */
#include "main_init_api.h"
#include "pmu_objhal.h"
#include "pmu_objtimer.h"

#include "config/g_timer_private.h"
// Pull in mock functions, if any were generated by rmconfig,
// due to --emit-mock-functions
#if(TIMER_MOCK_FUNCTIONS_GENERATED)
#include "config/g_timer_mock.c"
#endif

/* ------------------------- Application Includes --------------------------- */
/* ------------------------- Type Definitions ------------------------------- */
/* ------------------------- External Definitions --------------------------- */
/* ------------------------- Static Variables ------------------------------- */
/* ------------------------- Global Variables ------------------------------- */
OBJTIMER Timer;

/* ------------------------- Macros and Defines ----------------------------- */
/* ------------------------- Private Functions ------------------------------ */
/* ------------------------- Public Functions ------------------------------- */
/*!
 * Construct the TIMER object.  This sets up the HAL interface used by the
 * TIMER module.
 *
 * @return  FLCN_OK     On success
 * @return  Others      Error return value from failing child function
 */
FLCN_STATUS
constructTimer_IMPL(void)
{
    return FLCN_OK;
}
