/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2020 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#include "lwriscv/manifest_ga10x.h"

const PKC_VERIFICATION_MANIFEST manifest = {
    .version               = 0x7,
    .ucodeId               = 0x4,
    .ucodeVersion          = 0x7,
    .bRelaxedVersionCheck  = TRUE,
    .engineIdMask          = 0xFFFFFFFF,
    // This field will be patched during build
    .itcmSizeIn256Bytes    = (LWRISCV_APP_IMEM_LIMIT) / 256,
    // This field will be patched during build
    .dtcmSizeIn256Bytes    = (LWRISCV_APP_DMEM_LIMIT) / 256,
    .fmcHashPadInfoBitMask = 0x00000000,
    // NOT AUTOGENERATED! also must be !=0
    .CbcIv                 = { 0x27d0ef69, 0xc4bbca8a, 0x3437c8cb, 0x8cb8fc04 },
    // This field will be patched by siggen
    .digest                = { 0x00000000, 0x00000000, 0x00000000, 0x00000000,
                               0x00000000, 0x00000000, 0x00000000, 0x00000000 },
    .secretMask            = {
        .scpSecretMask     = 0x0000000000000000ULL,
        .scpSecretMaskLock = 0xFFFFFFFFFFFFFFFFULL,
    },
    .debugAccessControl    = {
        // Enable debugging for now, let Separation Kernel disable it if needed.
        .dbgctl =
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STOP,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RUN,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_STEP,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_J,      _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_EMASK,  _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RREG,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WREG,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RDM,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WDM,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RSTAT,  _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_IBRKPT, _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RCSR,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WCSR,   _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RPC,    _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_RFREG,  _ENABLE ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _ICD_CMDWL_WFREG,  _ENABLE ) |

            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _START_IN_ICD,     _FALSE  ) |
            DRF_DEF(_PRGNLCL, _RISCV_DBGCTL, _SINGLE_STEP_MODE, _DISABLE),

        .dbgctlLock = 0x0,
    },
    .bDecFuseKeys = FALSE,
    .mspm         = {
        .mplm  = (LW_RISCV_CSR_MSPM_MPLM_LEVEL2 | LW_RISCV_CSR_MSPM_MPLM_LEVEL1),
        .msecm = 0x0
    },

    .kdfConstant = { 0 },

    .deviceMap.deviceMap = {
        DEVICEMAP(_MMODE,          _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_RISCV_CTL,      _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_PIC,            _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_TIMER,          _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_HOSTIF,         _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_DMA,            _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        // PMB must be unlocked so someone can write LOCKPMB (and then disable/lock it)
        DEVICEMAP(_PMB,            _ENABLE,  _ENABLE,  _UNLOCKED) |
        DEVICEMAP(_DIO,            _DISABLE, _DISABLE, _UNLOCKED  ),

        DEVICEMAP(_KEY,            _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_DEBUG,          _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_SHA,            _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_KMEM,           _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_BROM,           _ENABLE,  _DISABLE, _LOCKED    ) | // BROM enforced
        DEVICEMAP(_ROM_PATCH,      _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_IOPMP,          _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_NOACCESS,       _DISABLE, _DISABLE, _UNLOCKED  ), // Empty Group

        DEVICEMAP(_SCP,            _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_FBIF,           _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_FALCON_ONLY,    _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_PRGN_CTL,       _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP0, _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP1, _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP2, _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_SCRATCH_GROUP3, _ENABLE,  _ENABLE,  _UNLOCKED  ),

        DEVICEMAP(_PLM,            _ENABLE,  _ENABLE,  _UNLOCKED  ) |
        DEVICEMAP(_HUB_DIO,        _ENABLE,  _ENABLE,  _UNLOCKED  ),  // Secure Bus - needed for HDCP
    },

    .corePmp = {
        .pmpcfg = {
            // PMPCFG
            PMP_ENTRY_OFF,
            PMP_ENTRY(_PERMITTED, _PERMITTED, _PERMITTED, _TOR, _LOCK),    // IMEM FMC, write blocked for ALL *MUST BE LOCKED*
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
        },

        .pmpaddr = {
            // PMPADDR
            0x0,
            0xFFFFFFFFFFFFFFFF, // Entire PA
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0,
        },
    },

    // IO_PMP_MODE - NAPOT for all entries as that's the only mode we support
    .ioPmpMode = 0xffffffffffffffff,

    .ioPmp = {
        .iopmpcfg = {
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 0-7
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 8-15
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 16-23
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 24-31
        },
        .iopmpaddrlo = {
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 0-7
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 8-15
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 16-23
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 24-31
        },
        .iopmpaddrhi = { // Must be always 0 for IMEM and DMEM
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 0-7
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 8-15
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 16-23
            0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, // 24-31
        },
    },

    .numberOfValidPairs = 1,
    // Below is only to help with debugging
    .registerPair       = {
        .addr    = { LW_PRGNLCL_RISCV_TRACECTL },
        .andMask = { 0x0 },
        .orMask  = {
            DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _MODE, _FULL)         |
            DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _MMODE_ENABLE, _TRUE) |
            DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _SMODE_ENABLE, _TRUE) |
            DRF_DEF(_PRGNLCL, _RISCV_TRACECTL, _UMODE_ENABLE, _TRUE),
        },
    },
};
