/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2015-2016 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */

//!
//!
//! \file lw_disp_cap_compare_regs.h
//! \Defines the sw and hw display capability registers to compare
//!

#define SW_CAP_REGISTER_OFFSET            0
#define HW_CAP_REGISTER_OFFSET            1
struct
{
    char *regs[2];
} capability_reg_fields[] =
{
    {"LW_PDISP_FE_SW_HEAD_CLK_CAP(0)","LW_PDISP_RG_HEAD_CLK_CAP(0)"},
    {"LW_PDISP_FE_SW_HEAD_CLK_CAP(1)","LW_PDISP_RG_HEAD_CLK_CAP(1)"},
    {"LW_PDISP_FE_SW_HEAD_CLK_CAP(2)","LW_PDISP_RG_HEAD_CLK_CAP(2)"},
    {"LW_PDISP_FE_SW_HEAD_CLK_CAP(3)","LW_PDISP_RG_HEAD_CLK_CAP(3)"},
    {"LW_PDISP_FE_SW_SYS_CAPB","LW_PDISP_FE_HW_SYS_CAPB"},
    {"LW_PDISP_FE_SW_IHUB_COMMON_CAPA","LW_PDISP_IHUB_COMMON_CAPA"},
    {"LW_PDISP_FE_SW_IHUB_COMMON_CAPC","LW_PDISP_IHUB_COMMON_CAPC"},
    {"LW_PDISP_FE_SW_IHUB_COMMON_CAPB","LW_PDISP_IHUB_COMMON_CAPB"},
    {"LW_PDISP_FE_SW_IHUB_COMMON_CAPD","LW_PDISP_IHUB_COMMON_CAPD"},
    {"LW_PDISP_FE_SW_SOR_CLK_CAP(0)","LW_PDISP_SOR_CLK_CAP(0)"},
    {"LW_PDISP_FE_SW_SOR_CLK_CAP(1)","LW_PDISP_SOR_CLK_CAP(1)"},
    {"LW_PDISP_FE_SW_SOR_CLK_CAP(2)","LW_PDISP_SOR_CLK_CAP(2)"},
    {"LW_PDISP_FE_SW_SOR_CLK_CAP(3)","LW_PDISP_SOR_CLK_CAP(3)"},
    {"LW_PDISP_FE_SW_SOR_CAP(0)","LW_PDISP_SOR_CAP(0)"},
    {"LW_PDISP_FE_SW_SOR_CAP(1)","LW_PDISP_SOR_CAP(1)"},
    {"LW_PDISP_FE_SW_SOR_CAP(2)","LW_PDISP_SOR_CAP(2)"},
    {"LW_PDISP_FE_SW_SOR_CAP(3)","LW_PDISP_SOR_CAP(3)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPF(0)","LW_PDISP_PRECOMP_WIN_PIPE_CAPF(0)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPF(1)","LW_PDISP_PRECOMP_WIN_PIPE_CAPF(1)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPD(0)","LW_PDISP_PRECOMP_WIN_PIPE_CAPD(0)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPD(1)","LW_PDISP_PRECOMP_WIN_PIPE_CAPD(1)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPE(0)","LW_PDISP_PRECOMP_WIN_PIPE_CAPE(0)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPE(1)","LW_PDISP_PRECOMP_WIN_PIPE_CAPE(1)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPB(0)","LW_PDISP_PRECOMP_WIN_PIPE_CAPB(0)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPB(1)","LW_PDISP_PRECOMP_WIN_PIPE_CAPB(1)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPC(0)","LW_PDISP_PRECOMP_WIN_PIPE_CAPC(0)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPC(1)","LW_PDISP_PRECOMP_WIN_PIPE_CAPC(1)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPA(0)","LW_PDISP_PRECOMP_WIN_PIPE_CAPA(0)"},
    {"LW_PDISP_FE_SW_PRECOMP_WIN_PIPE_CAPA(1)","LW_PDISP_PRECOMP_WIN_PIPE_CAPA(1)"},
    {"LW_PDISP_FE_SW_SYS_CAP","LW_PDISP_FE_HW_SYS_CAP"},
    {"LW_PDISP_FE_SW_MISC_CAPA","LW_PDISP_FE_HW_MISC_CAPA"},
    {"LW_PDISP_FE_SW_HEAD_CAPD(0)","LW_PDISP_POSTCOMP_HEAD_CAPD(0)"},
    {"LW_PDISP_FE_SW_HEAD_CAPD(1)","LW_PDISP_POSTCOMP_HEAD_CAPD(1)"},
    {"LW_PDISP_FE_SW_HEAD_CAPD(2)","LW_PDISP_POSTCOMP_HEAD_CAPD(2)"},
    {"LW_PDISP_FE_SW_HEAD_CAPD(3)","LW_PDISP_POSTCOMP_HEAD_CAPD(3)"},
    {"LW_PDISP_FE_SW_HEAD_CAPE(0)","LW_PDISP_POSTCOMP_HEAD_CAPE(0)"},
    {"LW_PDISP_FE_SW_HEAD_CAPE(1)","LW_PDISP_POSTCOMP_HEAD_CAPE(1)"},
    {"LW_PDISP_FE_SW_HEAD_CAPE(2)","LW_PDISP_POSTCOMP_HEAD_CAPE(2)"},
    {"LW_PDISP_FE_SW_HEAD_CAPE(3)","LW_PDISP_POSTCOMP_HEAD_CAPE(3)"},
    {"LW_PDISP_FE_SW_HEAD_CAPF(0)","LW_PDISP_POSTCOMP_HEAD_CAPF(0)"},
    {"LW_PDISP_FE_SW_HEAD_CAPF(1)","LW_PDISP_POSTCOMP_HEAD_CAPF(1)"},
    {"LW_PDISP_FE_SW_HEAD_CAPF(2)","LW_PDISP_POSTCOMP_HEAD_CAPF(2)"},
    {"LW_PDISP_FE_SW_HEAD_CAPF(3)","LW_PDISP_POSTCOMP_HEAD_CAPF(3)"},
    {"LW_PDISP_FE_SW_HEAD_CAPA(0)","LW_PDISP_POSTCOMP_HEAD_CAPA(0)"},
    {"LW_PDISP_FE_SW_HEAD_CAPA(1)","LW_PDISP_POSTCOMP_HEAD_CAPA(1)"},
    {"LW_PDISP_FE_SW_HEAD_CAPA(2)","LW_PDISP_POSTCOMP_HEAD_CAPA(2)"},
    {"LW_PDISP_FE_SW_HEAD_CAPA(3)","LW_PDISP_POSTCOMP_HEAD_CAPA(3)"},
    {"LW_PDISP_FE_SW_HEAD_CAPB(0)","LW_PDISP_POSTCOMP_HEAD_CAPB(0)"},
    {"LW_PDISP_FE_SW_HEAD_CAPB(1)","LW_PDISP_POSTCOMP_HEAD_CAPB(1)"},
    {"LW_PDISP_FE_SW_HEAD_CAPB(2)","LW_PDISP_POSTCOMP_HEAD_CAPB(2)"},
    {"LW_PDISP_FE_SW_HEAD_CAPB(3)","LW_PDISP_POSTCOMP_HEAD_CAPB(3)"},
    {"LW_PDISP_FE_SW_HEAD_CAPC(0)","LW_PDISP_POSTCOMP_HEAD_CAPC(0)"},
    {"LW_PDISP_FE_SW_HEAD_CAPC(1)","LW_PDISP_POSTCOMP_HEAD_CAPC(1)"},
    {"LW_PDISP_FE_SW_HEAD_CAPC(2)","LW_PDISP_POSTCOMP_HEAD_CAPC(2)"},
    {"LW_PDISP_FE_SW_HEAD_CAPC(3)","LW_PDISP_POSTCOMP_HEAD_CAPC(3)"},
    {"LW_PDISP_FE_SW_CLK_CAP","LW_PDISP_FE_HW_CLK_CAP"},
    {"LW_PDISP_FE_SW_LOCK_PIN_CAP","LW_PDISP_FE_HW_LOCK_PIN_CAP"},
    {"LW_PDISP_FE_SW_HEAD_RG_CAPA(0)","LW_PDISP_RG_HEAD_CAPA(0)"},
    {"LW_PDISP_FE_SW_HEAD_RG_CAPA(1)","LW_PDISP_RG_HEAD_CAPA(1)"},
    {"LW_PDISP_FE_SW_HEAD_RG_CAPA(2)","LW_PDISP_RG_HEAD_CAPA(2)"},
    {"LW_PDISP_FE_SW_HEAD_RG_CAPA(3)","LW_PDISP_RG_HEAD_CAPA(3)"},
};

