/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2016-2020 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/*!
 * @file  hdcp_cmn.h
 * @brief Master header file defining types that may be used in the hdcp
 *        application. This file defines all hdcp library related macros
 *        for different falcons
 */

#ifndef HDCP_CMN_H
#define HDCP_CMN_H
/* --------------------------- System includes ----------------------------- */
#include "flcncmn.h"

/* ------------------------ Application includes --------------------------- */
#include "lib_intfchdcp.h"
#include "displayport.h"
#include "hdcp_objhdcp.h"
/* ------------------------- Macros and Defines ---------------------------- */
#ifdef DPU_RTOS
#include "hdcp_pvtbus.h"
#include "rmdpucmdif.h"
#define RM_FLCN_UNIT_HDCP                           RM_DPU_UNIT_HDCP

// Private bus related mappings
#define LW_PDISP_HDCP_STATUS_SOR_REP                LW_PDISP_PRIVATE_HDCP_STATUS_SOR_REP
#define LW_PDISP_HDCP_STATUS_SOR_REP_ILWALID        LW_PDISP_PRIVATE_HDCP_STATUS_SOR_REP_ILWALID
#define LW_PDISP_HDCP_STATUS_SOR_REP_VALID          LW_PDISP_PRIVATE_HDCP_STATUS_SOR_REP_VALID
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT             LW_PDISP_PRIVATE_HDCP_STATUS_SOR_UNPROT
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT_VALID       LW_PDISP_PRIVATE_HDCP_STATUS_SOR_UNPROT_VALID
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT_ILWALID     LW_PDISP_PRIVATE_HDCP_STATUS_SOR_UNPROT_ILWALID
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE              LW_PDISP_PRIVATE_HDCP_STATUS_SOR_SCOPE
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE_FAILED       LW_PDISP_PRIVATE_HDCP_STATUS_SOR_SCOPE_FAILED
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE_PASSED       LW_PDISP_PRIVATE_HDCP_STATUS_SOR_SCOPE_PASSED
#define LW_PDISP_HDCP_STATUS_SOR_MASK               LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MASK
#define LW_PDISP_HDCP_STATUS_SOR_MASK_NOT_READY     LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MASK_NOT_READY
#define LW_PDISP_HDCP_STATUS_SOR_MASK_READY         LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MASK_READY

#define HDCP_STATUS_SOR_MAX                         LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MAX

#elif defined(GSPLITE_RTOS)

#include "rmdpucmdif.h"

#ifndef HDCP_TEGRA_BUILD

#include "hdcp_secbus.h"

// Secure bus related mappings
#define LW_PDISP_HDCP_STATUS_SOR_REP                LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_REP
#define LW_PDISP_HDCP_STATUS_SOR_REP_ILWALID        LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_REP_ILWALID
#define LW_PDISP_HDCP_STATUS_SOR_REP_VALID          LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_REP_VALID
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT             LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_UNPROT
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT_VALID       LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_UNPROT_VALID
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT_ILWALID     LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_UNPROT_ILWALID
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE              LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_SCOPE
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE_FAILED       LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_SCOPE_FAILED
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE_PASSED       LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_SCOPE_PASSED
#define LW_PDISP_HDCP_STATUS_SOR_MASK               LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_MASK
#define LW_PDISP_HDCP_STATUS_SOR_MASK_NOT_READY     LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_MASK_NOT_READY
#define LW_PDISP_HDCP_STATUS_SOR_MASK_READY         LW_SSE_SE_SWITCH_DISP_UPSTREAM_HDCP_STATUS_SOR_STATUS_MASK_READY

#define HDCP_STATUS_SOR_MAX                         LW_PDISP_SELWRE_HDCP_STATUS_SOR_MAX

#else
//TODO: 200586859 Map appropriate CHEETAH Display Registers
#include "hdcp_pvtbus.h"
#define LW_PDISP_HDCP_STATUS_SOR_REP                LW_PDISP_PRIVATE_HDCP_STATUS_SOR_REP
#define LW_PDISP_HDCP_STATUS_SOR_REP_ILWALID        LW_PDISP_PRIVATE_HDCP_STATUS_SOR_REP_ILWALID
#define LW_PDISP_HDCP_STATUS_SOR_REP_VALID          LW_PDISP_PRIVATE_HDCP_STATUS_SOR_REP_VALID
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT             LW_PDISP_PRIVATE_HDCP_STATUS_SOR_UNPROT
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT_VALID       LW_PDISP_PRIVATE_HDCP_STATUS_SOR_UNPROT_VALID
#define LW_PDISP_HDCP_STATUS_SOR_UNPROT_ILWALID     LW_PDISP_PRIVATE_HDCP_STATUS_SOR_UNPROT_ILWALID
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE              LW_PDISP_PRIVATE_HDCP_STATUS_SOR_SCOPE
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE_FAILED       LW_PDISP_PRIVATE_HDCP_STATUS_SOR_SCOPE_FAILED
#define LW_PDISP_HDCP_STATUS_SOR_SCOPE_PASSED       LW_PDISP_PRIVATE_HDCP_STATUS_SOR_SCOPE_PASSED
#define LW_PDISP_HDCP_STATUS_SOR_MASK               LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MASK
#define LW_PDISP_HDCP_STATUS_SOR_MASK_NOT_READY     LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MASK_NOT_READY
#define LW_PDISP_HDCP_STATUS_SOR_MASK_READY         LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MASK_READY

#define HDCP_STATUS_SOR_MAX                         LW_PDISP_PRIVATE_HDCP_STATUS_SOR_MAX

#endif // HDCP_TEGRA_BUILD

#define RM_FLCN_UNIT_HDCP                           RM_DPU_UNIT_HDCP

#endif

#endif // HDCP_CMN_H
