/** GENERATED FILE **/
#define LIBOS_CONFIG_GDMA_SUPPORT 0
#define LIBOS_CONFIG_MPU_INDEX_COUNT 128
#define LIBOS_FEATURE_PARTITION_SWITCH 1
#define LIBOS_CONFIG_RISCV_COMPRESSED 1
#define LIBOS_CONFIG_PAGETABLE_ENTRIES (LIBOS_CONFIG_PAGESIZE >> LIBOS_CONFIG_PAGETABLE_ENTRY_LOG2)
#define LIBOS_CONFIG_DMEM_FIRST 0x181000
#define LIBOS_CONFIG_MAX_TABLE_DISPLACEMENT 2
#define LIBOS_CONFIG_LTO 0
#define LIBOS_CONFIG_PRI_MAPPING_BASE 0x300000000
#define LIBOS_CONFIG_KERNEL_STACK_SIZE 1024
#define LIBOS_FEATURE_TIMERS 1
#define LIBOS_CONFIG_TIME_TO_NS(time) time
#define LIBOS_CONFIG_PRI_MAPPING_RANGE 0x2000000
#define LIBOS_CONFIG_DMEM_SIZE 0x27000
#define LIBOS_CONFIG_PRINTF_UNICODE 0
#define LIBOS_DEBUG 0
#define LIBOS_TINY 1
#define LIBOS_CONFIG_HAS_FBIO 1
#define LIBOS_CONFIG_VIRTUAL_ADDRESS_SIZE (4 * LIBOS_CONFIG_PAGESIZE_LOG2 - 3 * LIBOS_CONFIG_PAGETABLE_ENTRY_LOG2)
#define LIBOS_CONFIG_PAGESIZE_MEDIUM LIBOS_CONFIG_PAGESIZE
#define LIBOS_CONFIG_EXTERNAL_INTERRUPT 1
#define LIBOS_CONFIG_PROFILER 0
#define LIBOS_CONFIG_TIME_NS(time) time
#define LIBOS_CONFIG_IMEM_FIRST 0x101000
#define LIBOS_FEATURE_PAGING 0
#define LIBOS_CONFIG_PAGESIZE_HUGE LIBOS_CONFIG_PAGESIZE
#define LIBOS_TIMESLICE 5000000
#define LIBOS_CONFIG_KERNEL_LOG 0
#define LIBOS_LWRISCV 200
#define LIBOS_FEATURE_USERSPACE_TRAPS 0
#define LIBOS_CONFIG_INTEGRITY_MEMERR 0
#define LIBOS_CONFIG_PAGESIZE_MEDIUM_LOG2 (2 * LIBOS_CONFIG_PAGESIZE_LOG2 - LIBOS_CONFIG_PAGETABLE_ENTRY_LOG2)
#define LIBOS_CONFIG_MPU_PAGESIZE 1024
#define LIBOS_CONFIG_MPU_BOOTSTRAP 3
#define LIBOS_CONFIG_ID_SIZE 1
#define LIBOS_CONFIG_MPU_TEXT 1
#define LIBOS_CONFIG_PAGESIZE_HUGE_LOG2 (3 * LIBOS_CONFIG_PAGESIZE_LOG2 - 2 * LIBOS_CONFIG_PAGETABLE_ENTRY_LOG2)
#define LIBOS_FEATURE_PRIORITY_SCHEDULER 1
#define LIBOS_CONFIG_PROFILER_SAVE_ON_SUSPEND 0
#define LIBOS_CONFIG_KERNEL_TRACE 0
#define LIBOS_CONFIG_MPU_INDEX_FIRST 0
#define LIBOS_FEATURE_SHUTDOWN 1
#define LIBOS_CONFIG_MPU_HASHED 0
#define LIBOS_CONFIG_MPU_IDENTITY 0
#define LIBOS_CONFIG_FLOAT 0
#define LIBOS_CONFIG_PRINTF_TINY 1
#define LIBOS_CONFIG_RISCV_S_MODE 1
#define LIBOS_CONFIG_IMEM_SIZE 0x37000
#define LIBOS_CONFIG_MPU_DATA 2
#define LIBOS_CONFIG_PAGETABLE_ENTRY_LOG2 3
