// This file is automatically generated by chip-config - DO NOT EDIT!
//
// Profile:  {{$PROFILE}}
// Template: {{$TEMPLATE_FILE}}
//
// Chips:    {{ CHIP_LIST() }}
//

#ifndef G_{{$XXCFG}}_PRIVATE_H
#define G_{{$XXCFG}}_PRIVATE_H

//
// Macros to help with enabling or disabling code based on whether
// a feature (or chip or engine or ...) is enabled or not.
// Also have RISCVLIBCFG_CHIP_ENABLED(), RISCVLIBCFG_FEATURE_ENABLED(), etc
// from {{$XXCONFIG_H_FILE}}.
//
// NOTE: these definitions are "flat" (ie they don't use some more general
//       RISCVLIBCFG_ENABLED(CHIP,X) form because the pre-processor would re-evaluate
//       the expansion of the item (gpu, feature, class, api).  For classes,
//       at least, this is a problem since we would end up with class number
//       instead of its name...

// hack: MSVC is not C99 compliant
#ifdef LW_WINDOWS
#define __func__ __FUNCTION__
#endif

// CHIP's
#define {{$XXCFG}}_CHIP_ENABLED_STATUS(W)   ({{$XXCFG}}_CHIP_##W ? {{$STATUS_OK}} : {{$STATUS_ERROR}})
#define {{$XXCFG}}_CHIP_ENABLED_OR_BAIL(W)                \
     do {                                           \
         if ( ! {{$XXCFG}}_CHIP_##W)                      \
         {                                          \
             DBG_PRINTF((DBG_MODULE_GLOBAL, DBG_LEVEL_ERRORS, "RISCVLIB: %s: CHIP " #W " not enabled, bailing\n", __func__)); \
             return {{$STATUS_ERROR}};           \
         }                                          \
     } while (LW_FALSE)
#define {{$XXCFG}}_CHIP_ENABLED_OR_ASSERT_AND_BAIL(W)     \
     do {                                           \
         if ( ! {{$XXCFG}}_CHIP_##W)                      \
         {                                          \
             DBG_PRINTF((DBG_MODULE_GLOBAL, DBG_LEVEL_ERRORS, "RISCVLIB: %s: CHIP " #W " not enabled, assert and bail\n", __func__)); \
             {{$ASSERT}}({{$XXCFG}}_CHIP_##W);                        \
             return {{$STATUS_ERROR}};           \
         }                                          \
     } while (LW_FALSE)
#define {{$XXCFG}}_CHIP_ENABLED_OR_GOTO(W,L)  \
    do {                                 \
        if (! {{$XXCFG}}_CHIP_##W)            \
        {                                \
            goto L;                      \
        }                                \
    } while (LW_FALSE)
#define {{$XXCFG}}_CHIP_ENABLED_OR_BREAK(W)   \
    {                                    \
        if (! {{$XXCFG}}_CHIP_##W)            \
        {                                \
            break;                       \
        }                                \
    }

// FEATURE's
#define {{$XXCFG}}_FEATURE_ENABLED_STATUS(W)   ({{$XXCFG}}_FEATURE_##W ? {{$STATUS_OK}} : {{$STATUS_ERROR}})
#define {{$XXCFG}}_FEATURE_ENABLED_OR_BAIL(W)            \
     do {                                           \
         if ( ! {{$XXCFG}}_FEATURE_##W)                  \
         {                                          \
             DBG_PRINTF((DBG_MODULE_GLOBAL, DBG_LEVEL_ERRORS, "RISCVLIB: %s: FEATURE " #W " not enabled, bailing\n", __func__)); \
             return {{$STATUS_ERROR}};           \
         }                                          \
     } while (LW_FALSE)
#define {{$XXCFG}}_FEATURE_ENABLED_OR_ASSERT_AND_BAIL(W) \
     do {                                           \
         if ( ! {{$XXCFG}}_FEATURE_##W)                  \
         {                                          \
             DBG_PRINTF((DBG_MODULE_GLOBAL, DBG_LEVEL_ERRORS, "RISCVLIB: %s: FEATURE " #W " not enabled, assert and bail\n", __func__)); \
             {{$ASSERT}}({{$XXCFG}}_FEATURE_##W);          \
             return {{$STATUS_ERROR}};           \
         }                                          \
     } while (LW_FALSE)
#define {{$XXCFG}}_FEATURE_ENABLED_OR_GOTO(W,L)  \
    do {                                     \
        if (! {{$XXCFG}}_FEATURE_##W)            \
        {                                    \
            goto L;                          \
        }                                    \
    } while (LW_FALSE)
#define {{$XXCFG}}_FEATURE_ENABLED_OR_BREAK(W)   \
    {                                        \
        if (! {{$XXCFG}}_FEATURE_##W)            \
        {                                    \
            break;                           \
        }                                    \
    }

// ENGINE's
#define {{$XXCFG}}_ENGINE_ENABLED_STATUS(W)   ({{$XXCFG}}_ENGINE_##W ? {{$STATUS_OK}} : {{$STATUS_ERROR}})
#define {{$XXCFG}}_ENGINE_ENABLED_OR_BAIL(W)             \
     do {                                           \
         if ( ! {{$XXCFG}}_ENGINE_##W)                   \
         {                                          \
             DBG_PRINTF((DBG_MODULE_GLOBAL, DBG_LEVEL_ERRORS, "RISCVLIB: %s: ENGINE " #W " not enabled, bailing\n", __func__)); \
             return {{$STATUS_ERROR}};           \
         }                                          \
     } while (LW_FALSE)
#define {{$XXCFG}}_ENGINE_ENABLED_OR_ASSERT_AND_BAIL(W)  \
     do {                                           \
         if ( ! {{$XXCFG}}_ENGINE_##W)                   \
         {                                          \
             DBG_PRINTF((DBG_MODULE_GLOBAL, DBG_LEVEL_ERRORS, "RISCVLIB: %s: ENGINE " #W " not enabled, assert and bail\n", __func__)); \
             {{$ASSERT}}({{$XXCFG}}_ENGINE_##W);           \
             return {{$STATUS_ERROR}};           \
         }                                          \
     } while (LW_FALSE)
#define {{$XXCFG}}_ENGINE_ENABLED_OR_GOTO(W,L)  \
    do {                                    \
        if (! {{$XXCFG}}_ENGINE_##W)            \
        {                                   \
            goto L;                         \
        }                                   \
    } while (LW_FALSE)
#define {{$XXCFG}}_ENGINE_ENABLED_OR_BREAK(W)   \
    {                                       \
        if (! {{$XXCFG}}_ENGINE_##W)            \
        {                                   \
            break;                          \
        }                                   \
    }


#endif  // G_{{$XXCFG}}_PRIVATE_H
