/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2017-2022 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/*!
 * @file clk_vf_point_30_freq.c
 *
 * @brief Module managing all state related to the CLK_VF_POINT_FREQ structure.
 * This structure defines a point on the VF lwrve for which frequency is the
 * independent variable (i.e. fixed for this VF point) and voltage is the
 * dependent variable (i.e. varies with process, temperature, etc.).
 *
 * The CLK_VF_POINT_FREQ class supplies the frequency value from the CLK_VF_POINT
 * super-class (@ref CLK_VF_POINT::freqMHz) to the specified VFE Equation
 * (@ref CLK_PROG_3X_PRIMARY::pVfEntries[railIdx]->vfeIdx) and stores the resulting
 * voltage in the CLK_VF_POINT super-class (@ref CLK_VF_POINT::voltageuV).
 *
 * The CLK_VF_POINT_FREQ class is intended to be used to describe frequency
 * regions which are generated by the fixed-frequency generators (PLL,
 * OneSource) which generate a given frequency for which a minimum required
 * voltage must be determined.
 */

/* ------------------------ Includes --------------------------------------- */
#include "pmu_objclk.h"
#include "perf/3x/vfe.h"
#include "volt/objvolt.h"

/* ------------------------ Static Function Prototypes ---------------------- */
static BoardObjVirtualTableDynamicCast (s_vfeVarDynamicCast_30_FREQ)
    GCC_ATTRIB_SECTION("imem_perf", "s_vfeVarDynamicCast_30_FREQ")
    GCC_ATTRIB_USED();

/* ------------------------ Global Variables ------------------------------- */
/*!
 * Virtual table for CLK_VF_POINT_30_FREQ object interfaces.
 */
BOARDOBJ_VIRTUAL_TABLE ClkVfPoint30FreqVirtualTable =
{
    BOARDOBJ_VIRTUAL_TABLE_ASSIGN_DYNAMIC_CAST(s_vfeVarDynamicCast_30_FREQ)
};

/* ------------------------ Static Function Prototypes --------------------- */
/* ------------------------ Macros ----------------------------------------- */
/* ------------------------ Public Functions ------------------------------- */
/*!
 * CLK_VF_POINT_30_FREQ class constructor.
 *
 * @copydoc BoardObjGrpIfaceModel10ObjSet
 */
FLCN_STATUS
clkVfPointGrpIfaceModel10ObjSet_30_FREQ
(
    BOARDOBJGRP_IFACE_MODEL_10        *pModel10,
    BOARDOBJ          **ppBoardObj,
    LwLength            size,
    RM_PMU_BOARDOBJ    *pBoardObjSet
)
{
    RM_PMU_CLK_CLK_VF_POINT_30_FREQ_BOARDOBJ_SET *pSet =
        (RM_PMU_CLK_CLK_VF_POINT_30_FREQ_BOARDOBJ_SET *)pBoardObjSet;
    CLK_VF_POINT_30_FREQ   *pVfPoint30Freq;
    FLCN_STATUS             status;


    // Call into CLK_VF_POINT_30 super-constructor
    status = clkVfPointGrpIfaceModel10ObjSet_SUPER(pModel10, ppBoardObj, size, pBoardObjSet);
    if (status != FLCN_OK)
    {
        PMU_BREAKPOINT();
        goto clkVfPointGrpIfaceModel10ObjSet_30_FREQ_exit;
    }

    BOARDOBJ_DYNAMIC_CAST_OR_GOTO(pVfPoint30Freq, *ppBoardObj, CLK, CLK_VF_POINT, 30_FREQ,
                                  &status, clkVfPointGrpIfaceModel10ObjSet_30_FREQ_exit);

    // Copy the CLK_VF_POINT-specific data.
    clkVfPoint30FreqMHzSet(&pVfPoint30Freq->super, pSet->freqMHz);

    // Copy the CLK_VF_POINT_30_FREQ-specific data.
    pVfPoint30Freq->voltDeltauV = pSet->voltDeltauV;

clkVfPointGrpIfaceModel10ObjSet_30_FREQ_exit:
    return status;
}

/*!
 * _FREQ implemenation.
 *
 * @copydoc ClkVfPoint30Cache
 */
FLCN_STATUS
clkVfPoint30Cache_FREQ
(
    CLK_VF_POINT_30            *pVfPoint30,
    CLK_DOMAIN_30_PRIMARY       *pDomain30Primary,
    CLK_PROG_30_PRIMARY         *pProg30Primary,
    LwU8                        voltRailIdx,
    LW2080_CTRL_CLK_VF_PAIR    *pVfPairLast,
    LW2080_CTRL_CLK_VF_PAIR    *pBaseVFPairLast,
    LW2080_CTRL_CLK_VF_PAIR    *pBaseVFPairLwrr
)
{
    CLK_VF_POINT_30_FREQ       *pVfPoint30Freq;
    VOLT_RAIL                  *pVoltRail;
    RM_PMU_PERF_VFE_VAR_VALUE   vfeVarVal;
    RM_PMU_PERF_VFE_EQU_RESULT  result;
    FLCN_STATUS                 status;
    LwU32                       voltageuV;

    BOARDOBJ_DYNAMIC_CAST_OR_GOTO(pVfPoint30Freq, &pVfPoint30->super.super,
                                  CLK, CLK_VF_POINT, 30_FREQ, &status,
                                  clkVfPoint30Cache_FREQ_exit);

    // 1. Compute voltage for the frequency.
    vfeVarVal.frequency.varType      = LW2080_CTRL_PERF_VFE_VAR_TYPE_SINGLE_FREQUENCY;
    vfeVarVal.frequency.varValue     = clkVfPoint30FreqMHzGet(&pVfPoint30Freq->super);
    vfeVarVal.frequency.clkDomainIdx = LW2080_CTRL_CLK_CLK_DOMAIN_INDEX_ILWALID;
    status = vfeEquEvaluate(
        clkProg3XPrimaryVfeIdxGet(&pProg30Primary->primary, voltRailIdx),
        &vfeVarVal,
        1,
        LW2080_CTRL_PERF_VFE_EQU_OUTPUT_TYPE_VOLT_UV,
        &result);
    if (status != FLCN_OK)
    {
        PMU_BREAKPOINT();
        goto clkVfPoint30Cache_FREQ_exit;
    }
    voltageuV = result.voltuV;

    // 2. Adjust by the voltage delta.
    voltageuV = clkVoltDeltaAdjust(voltageuV, pVfPoint30Freq->voltDeltauV);

    // 3. Round voltage to closest step supported by voltage rail.
    pVoltRail = VOLT_RAIL_GET(voltRailIdx);
    if (pVoltRail != NULL)
    {
        status = voltRailRoundVoltage(pVoltRail,
                    (LwS32*)&voltageuV, LW_TRUE, LW_TRUE);
        if (status != FLCN_OK)
        {
            PMU_BREAKPOINT();
            goto clkVfPoint30Cache_FREQ_exit;
        }
    }

    // Store the voltage value in the CLK_VF_POINT
    clkVfPoint30VoltageuVSet(pVfPoint30, voltageuV);

clkVfPoint30Cache_FREQ_exit:
    return status;
}


/* ------------------------- Private Functions ------------------------------ */
/*!
 * @brief   CLK_VF_POINT_30_FREQ implementation of
 *          @ref BoardObjVirtualTableDynamicCast()
 *
 * @copydoc BoardObjVirtualTableDynamicCast()
 */
static void *
s_vfeVarDynamicCast_30_FREQ
(
    BOARDOBJ   *pBoardObj,
    LwU8        requestedType
)
{
    void                 *pObject     = NULL;
    CLK_VF_POINT_30_FREQ *pVfPt30Freq = (CLK_VF_POINT_30_FREQ *)pBoardObj;

    if (BOARDOBJ_GET_TYPE(pBoardObj) !=
        LW2080_CTRL_BOARDOBJ_TYPE(CLK, CLK_VF_POINT, 30_FREQ))
    {
        PMU_BREAKPOINT();
        goto s_vfeVarDynamicCast_30_FREQ_exit;
    }

    switch (requestedType)
    {
        case LW2080_CTRL_BOARDOBJ_TYPE(CLK, CLK_VF_POINT, BASE):
        {
            CLK_VF_POINT *pVfPt = &pVfPt30Freq->super.super;
            pObject = (void *)pVfPt;
            break;
        }
        case LW2080_CTRL_BOARDOBJ_TYPE(CLK, CLK_VF_POINT, 30):
        {
            CLK_VF_POINT_30 *pVfPt30 = &pVfPt30Freq->super;
            pObject = (void *)pVfPt30;
            break;
        }
        case LW2080_CTRL_BOARDOBJ_TYPE(CLK, CLK_VF_POINT, 30_FREQ):
        {
            pObject = (void *)pVfPt30Freq;
            break;
        }
        default:
        {
            PMU_BREAKPOINT();
            break;
        }
    }

s_vfeVarDynamicCast_30_FREQ_exit:
    return pObject;
}
