// This file is automatically generated by {{$name}} - DO NOT EDIT!
//
// HAL support for use in HAL setup
//
// Profile:  {{$PROFILE}}
// Template: {{$TEMPLATE_FILE}}
//

#ifndef G_{{$XXCFG}}_HAL_H
#define G_{{$XXCFG}}_HAL_H

#define HAL_IMPL_NAME_LIST \
    {{ HAL_IMPL_NAMES() }}

#endif  // G_{{$XXCFG}}_HAL_H
