/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2010-2014 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */

/**
 * @file  lwwatch.h
 * @brief Lwwatch API
 */

#ifndef INCLUDED_LWWATCH_H
#define INCLUDED_LWWATCH_H

#define LW_WATCH_API(cmd) extern "C" void cmd(char *Args);
LW_WATCH_API(init)
LW_WATCH_API(verbose)
LW_WATCH_API(ptov)
LW_WATCH_API(vtop)
LW_WATCH_API(gvtop)
LW_WATCH_API(gpde)
LW_WATCH_API(gpte)
LW_WATCH_API(rb)
LW_WATCH_API(wb)
LW_WATCH_API(rw)
LW_WATCH_API(ww)
LW_WATCH_API(rd)
LW_WATCH_API(wr)
LW_WATCH_API(tmdsrd)
LW_WATCH_API(tmdswr)
LW_WATCH_API(gvrd)
LW_WATCH_API(gvwr)
LW_WATCH_API(gvdisp)
LW_WATCH_API(cpudisp)
LW_WATCH_API(gvdiss)
LW_WATCH_API(fbrd)
LW_WATCH_API(fbwr)
LW_WATCH_API(heap)
LW_WATCH_API(diag)
LW_WATCH_API(help)
LW_WATCH_API(clocks)
LW_WATCH_API(cntrfreq)
LW_WATCH_API(getcr)
LW_WATCH_API(setcr)
LW_WATCH_API(i2c)
LW_WATCH_API(dcb)
LW_WATCH_API(slivb)
LW_WATCH_API(zbc)
LW_WATCH_API(l2ilwalidate)
LW_WATCH_API(fbmonitor)
LW_WATCH_API(l2state)
LW_WATCH_API(ismemreq)
LW_WATCH_API(fifoinfo)
LW_WATCH_API(pbinfo)
LW_WATCH_API(runlist)
LW_WATCH_API(pb)
LW_WATCH_API(pbch)
LW_WATCH_API(pbdma)
LW_WATCH_API(channelram)
LW_WATCH_API(grinfo)
LW_WATCH_API(gr)
LW_WATCH_API(launchcheck)
LW_WATCH_API(tiling)
LW_WATCH_API(zlwll)
LW_WATCH_API(zlwllram)
LW_WATCH_API(surface)
LW_WATCH_API(limiterror)
LW_WATCH_API(subch)
LW_WATCH_API(grctx)
LW_WATCH_API(grstatus)
LW_WATCH_API(grwarppc)
LW_WATCH_API(ssclass)
LW_WATCH_API(perfmon)
LW_WATCH_API(fifoctx)
LW_WATCH_API(insttochid)
LW_WATCH_API(vic)
LW_WATCH_API(msdec)
LW_WATCH_API(falctrace)
LW_WATCH_API(pcieinfo)
LW_WATCH_API(pcie)
LW_WATCH_API(pd)
LW_WATCH_API(pe)
LW_WATCH_API(dchnstate)
LW_WATCH_API(dchnnum)
LW_WATCH_API(dchnname)
LW_WATCH_API(dgetdbgmode)
LW_WATCH_API(dsetdbgmode)
LW_WATCH_API(dinjectmethod)
LW_WATCH_API(dreadasy)
LW_WATCH_API(dreadarm)
LW_WATCH_API(ddumppb)
LW_WATCH_API(ddispowner)
LW_WATCH_API(dhdorconn)
LW_WATCH_API(dorstate)
LW_WATCH_API(dsetorstate)
LW_WATCH_API(dchnmstate)
LW_WATCH_API(danalyzeblank)
LW_WATCH_API(danalyzehang)
LW_WATCH_API(drdhdmidecoder)
LW_WATCH_API(dwrhdmidecoder)
LW_WATCH_API(dsorpadlinkconn)
LW_WATCH_API(dpinfo)
LW_WATCH_API(dtim)
LW_WATCH_API(sigdump)
LW_WATCH_API(checkprodvals)
LW_WATCH_API(pmudmemrd)
LW_WATCH_API(pmudmemwr)
LW_WATCH_API(pmuimemrd)
LW_WATCH_API(pmuimemwr)
LW_WATCH_API(pmuqueues)
LW_WATCH_API(pmuevtq)
LW_WATCH_API(pmuimblk)
LW_WATCH_API(pmuimtag)
LW_WATCH_API(pmuimmap)
LW_WATCH_API(pmumutex)
LW_WATCH_API(pmutcb)
LW_WATCH_API(pmusym)
LW_WATCH_API(pmusanitytest)
LW_WATCH_API(pmuqboot)
LW_WATCH_API(pmusched)
LW_WATCH_API(msenc)
LW_WATCH_API(smcpartitioninfo)
LW_WATCH_API(smcengineinfo)
extern "C" void exitLwWatch();

#endif // INCLUDED_LWWATCH_H
