#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2012-2016 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

include gpu/embedded/dev/display/makesrc.inc

basic_release_files += gpu/embedded/js/embeddedgpu.js
