#define IN_ADA_BODY
#include "lw_types_intrinsic.h"

typedef unsigned_8 lw_types_intrinsic__lwu1_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu2_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu3_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu4_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu5_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu6_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu7_wrap;
typedef unsigned_8 lw_types_intrinsic__lwu8_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu9_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu10_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu11_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu12_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu13_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu14_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu15_wrap;
typedef unsigned_16 lw_types_intrinsic__lwu16_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu17_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu18_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu19_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu20_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu21_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu22_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu23_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu24_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu25_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu26_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu27_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu28_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu29_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu30_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu31_wrap;
typedef unsigned_32 lw_types_intrinsic__lwu32_wrap;
typedef unsigned_64 lw_types_intrinsic__lwu64_wrap;
