#
# _LWRM_COPYRIGHT_BEGIN_
#
# Copyright 2021 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# _LWRM_COPYRIGHT_END_
#

#
# This is just a wrapper for lwmk files so that running lwmake on the common
# libSPDM source "just-works", and provides compatibility with submake. See the
# comments at the top of makefile.lwmk for additional information on the build.
#

.SILENT:

.PHONY: all build clean clobber

all: build

build:
	$(MAKE) build

clean:
	$(MAKE) clean

clobber:
	$(MAKE) clobber

