/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2012-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */

// DO NOT INCLUDE FILE DIRECTLY
GLINFERNO_OPTS(FsMode,                  UINT32,    0,    "FsMode 0-1smid 1-8smid 2-16smid 3-32smid")
GLINFERNO_OPTS(ScreenWidth,             UINT32, 1280,    "ScreenWidth")
GLINFERNO_OPTS(ScreenHeight,            UINT32, 1024,    "ScreenHeight")
GLINFERNO_OPTS(TexWidth,                UINT32,   32,    "TexWidth")
GLINFERNO_OPTS(TexHeight,               UINT32,   32,    "TexHeight")
GLINFERNO_OPTS(FullscreenPrimCount,     UINT32,  100,    "Number of fullscreen prims per loop")
GLINFERNO_OPTS(FrustumLwllPrimCount,    UINT32,    0,    "Number of prims to lwll with frustnum per loop")
GLINFERNO_OPTS(BackfaceLwllPrimCount,   UINT32,    1,    "Number of prims to lwll with backface per loop")
GLINFERNO_OPTS(ZlwllPrimCount,          UINT32,   10,    "Zlwll Prim Count")
GLINFERNO_OPTS(ZlwllStripPeriod,        UINT32,    0,    "Zlwll Strip Period")
GLINFERNO_OPTS(ZlwllStripWidth,         UINT32,    0,    "Zlwll Strip Width")
GLINFERNO_OPTS(PsKernelTex,             UINT32,    4,    "Tex Instructions")
GLINFERNO_OPTS(PsKernelRep,             UINT32,   20,    "kernel rep count")
GLINFERNO_OPTS(PsKernelType,            UINT32,    1,    "Type of kernel")
GLINFERNO_OPTS(PsKernelFmadRatio,       FLOAT64, 4.0,    "Weight of fmad.")
GLINFERNO_OPTS(PsKernelDmadRatio,       FLOAT64, 4.0,    "Weight of dmad.")
GLINFERNO_OPTS(PsKernelMemRatio,        FLOAT64, 4.0,    "Weight of memops.")
GLINFERNO_OPTS(PsKernelAluRatio,        FLOAT64, 2.0,    "Weight of ALUops.")
GLINFERNO_OPTS(RandomSeed,              UINT32,  222,    "random seed" )
GLINFERNO_OPTS(Multisample,             UINT32,    4,    "multisample" )
GLINFERNO_OPTS(DeltaZ,                  FLOAT64,0.01,    "Delta Z")
GLINFERNO_OPTS(TexAniso,                FLOAT64, 1.0,    "Aniso Level")
GLINFERNO_OPTS(TexIterOffsetS,          FLOAT64, 0.1,    "Tex iter Offset S")
GLINFERNO_OPTS(TexIterOffsetT,          FLOAT64, 0.1,    "Tex iter Offset T")
GLINFERNO_OPTS(TexCoeffA,               FLOAT64, 0.0,    "Tex Coeff A")
GLINFERNO_OPTS(TexCoeffB,               FLOAT64, 0.0,    "Tex Coeff A")
GLINFERNO_OPTS(TexCoeffC,               FLOAT64, 1.0,    "Tex Coeff A")
GLINFERNO_OPTS(SampleMaskEnable,        UINT32,    0,    "Sample Mask")
GLINFERNO_OPTS(SampleMask0,             UINT32,    0,    "Sample Mask")
GLINFERNO_OPTS(SampleMask1,             UINT32,    0,    "Sample Mask")
GLINFERNO_OPTS(SampleMaskScissorWidth,  UINT32,    0,    "Sample Mask")
GLINFERNO_OPTS(SampleMaskScissorHeight, UINT32,    0,    "Sample Mask")
GLINFERNO_OPTS(BlendLevel,              UINT32,    2,    "Blend Level")
GLINFERNO_OPTS(BlendR,                  FLOAT64, 0.3,    "Blend ratio R")
GLINFERNO_OPTS(BlendG,                  FLOAT64, 0.4,    "Blend ratio G")
GLINFERNO_OPTS(BlendB,                  FLOAT64, 0.5,    "Blend ratio B")
GLINFERNO_OPTS(BlendA,                  FLOAT64, 0.6,    "Blend ratio A")
GLINFERNO_OPTS(WFILevel,                UINT32,    0,    "")
GLINFERNO_OPTS(ColorBuffer,             UINT32,    0,    "")
GLINFERNO_OPTS(DepthBuffer,             UINT32,    1,    "")
GLINFERNO_OPTS(TexBuffer,               UINT32,    2,    "")
GLINFERNO_OPTS(EndLoopPeriodMs,         UINT32,10000,    "")
GLINFERNO_OPTS(LoopMs,                  UINT32,20000,    "")
GLINFERNO_OPTS(Watts,                   FLOAT64, 0.0,    "")
GLINFERNO_OPTS(HysterisisPct,           FLOAT64, 1.0,    "")
GLINFERNO_OPTS(ErrorCheck,                bool,false,    "Compare every other frame for consistency")
GLINFERNO_OPTS(ErrorCheckInterval,      UINT32,    2,    "The interval at which to CRC the frames. Must be an even number.")
GLINFERNO_OPTS(DumpFrames,              UINT32,    0,    "Number of frames to dump images of (default 0).")
GLINFERNO_OPTS(PulseMode,               UINT32,    0,    "Pulse Mode")
GLINFERNO_OPTS(TileMask,                UINT32,    0,    "User or GPC tile bitmask")
GLINFERNO_OPTS(NumActiveGPCs,           UINT32,    0,    "Number of active GPCs in GPC shuffle mode")
//GLOBALS
GLINFERNO_GLOBALS(ECPrg,         UINT32,         0, "" )
GLINFERNO_GLOBALS(ECPs,          UINT32,         0, "" )
GLINFERNO_GLOBALS(ECQuery,       GLuint,         0, "" )
GLINFERNO_GLOBALS(ECColorid,     GLuint,         0, "" )
GLINFERNO_GLOBALS(ECDepthid,     GLuint,         0, "" )
GLINFERNO_GLOBALS(ECFboid,       GLuint,         0, "" )
GLINFERNO_GLOBALS(DumpColorid,   GLuint,         0, "" )
GLINFERNO_GLOBALS(DumpFboid,     GLuint,         0, "" )
GLINFERNO_GLOBALS(Colorid,       GLuint,         0, "" )
GLINFERNO_GLOBALS(Depthid,       GLuint,         0, "" )
GLINFERNO_GLOBALS(Texid,         GLuint,         0, "" )
GLINFERNO_GLOBALS(Fboid,         GLuint,         0, "" )
GLINFERNO_GLOBALS(Vboid,         GLuint,         0, "" )
GLINFERNO_GLOBALS(Idxid,         GLuint,         0, "" )
GLINFERNO_GLOBALS(Vaoid,         GLuint,         0, "" )
GLINFERNO_GLOBALS(Ps,            UINT32,         0, "" )
GLINFERNO_GLOBALS(Vs,            UINT32,         0, "" )
GLINFERNO_GLOBALS(Prg,           UINT32,         0, "" )
GLINFERNO_GLOBALS(StartTime,     UINT32,         0, "" )
GLINFERNO_GLOBALS(Tframes,       UINT32,         0, "" )
GLINFERNO_GLOBALS(Ftime,         UINT32,         0, "" )
GLINFERNO_GLOBALS(Ftsum,         UINT32,         0, "" )
GLINFERNO_GLOBALS(KeepRunning,   UINT32,         0, "" )
GLINFERNO_GLOBALS(RecompileFlag,   bool,     false, "" )

