/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */
#include "pascal/gp108/dev_ism.h"
    //--------------------------------------------------------------------------
    // 2021-07-23 13:35:39.491447
    // This table was auto generated by:/sw/dev/gpu_drv/chips_a/diag/mods/gpu/ism/parse_dev_ism.py
    // Source file:/sw/dev/gpu_drv/chips_a/drivers/common/inc/hwref/pascal/gp108/dev_ism.h
    // Do not modify contents
    //--------------------------------------------------------------------------
    //ISM Chains:25
    //Max ISMs in a single chain:    30
    //LW_ISM_MINI_1clk_no_ext_ro_dbg:0
    //LW_ISM_MINI_1clk_no_ext_ro:0
    //LW_ISM_MINI_1clk_dbg:0
    //LW_ISM_MINI_1clk:0
    //LW_ISM_MINI_2clk_no_ext_ro:0
    //LW_ISM_MINI_2clk_dbg_v3:0
    //LW_ISM_MINI_2clk_dbg_v2:1
    //LW_ISM_MINI_2clk_dbg:0
    //LW_ISM_MINI_2clk_v2:103
    //LW_ISM_MINI_2clk:20
    //LW_ISM_ROSC_bin_metal:3
    //LW_ISM_ROSC_bin_aging_v1:0
    //LW_ISM_ROSC_bin_aging:8
    //LW_ISM_ROSC_bin_v3:0
    //LW_ISM_ROSC_bin_v2:0
    //LW_ISM_ROSC_bin_v1:0
    //LW_ISM_ROSC_bin:0
    //LW_ISM_ROSC_comp_v1:0
    //LW_ISM_ROSC_comp:1
    //LW_ISM_VNSENSE_ddly:0
    //LW_ISM_TSOSC_a4:0
    //LW_ISM_TSOSC_a3:0
    //LW_ISM_TSOSC_a2:6
    //LW_ISM_TSOSC_a:0
    //LW_ISM_NMEAS_lite_v9:0
    //LW_ISM_NMEAS_lite_v8:0
    //LW_ISM_NMEAS_lite_v7:0
    //LW_ISM_NMEAS_lite_v6:0
    //LW_ISM_NMEAS_lite_v5:0
    //LW_ISM_NMEAS_lite_v4:0
    //LW_ISM_NMEAS_lite_v3:0
    //LW_ISM_NMEAS_lite_v2:0
    //LW_ISM_NMEAS_lite:0
    //LW_ISM_NMEAS_v4:0
    //LW_ISM_NMEAS_v3:28
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_HOLD:0
    //LW_ISM_aging_v4:0
    //LW_ISM_aging_v3:0
    //LW_ISM_aging_v2:0
    //LW_ISM_aging_v1:0
    //LW_ISM_aging:1
    //LW_ISM_cpm_v5:0
    //LW_ISM_cpm_v4:0
    //LW_ISM_cpm_v3:0
    //LW_ISM_cpm_v2:0
    //LW_ISM_cpm_v1:0
    //LW_ISM_cpm:0
    //LW_ISM_imon:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_ctrl_v4:0
    //LW_ISM_ctrl_v3:1
    //LW_ISM_ctrl_v2:0
    //LW_ISM_ctrl:0
    //--------------------------------------------------------------------------
    // GP107 ISM TABLE
    //--------------------------------------------------------------------------
vector<GpuIsm::IsmChain> GP107SpeedoChains;
void InitializeGP107SpeedoChains()
{
    GP107SpeedoChains.clear();
    GP107SpeedoChains.reserve(25);
    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ID,  //InstrId=0xB5//$
        LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_WIDTH,  //Size=506(in bits)//$
        LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_CHIPLET_SEL,  //Chiplet=4//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[0].ISMs.reserve(10);
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_F0_0GPYF0CR0GPY0FBP0ISM_OTHERC_GPYF0CR0_LTCCLK_NOBG__)); //$= 3
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_8_F0_0GPYF0ZR0GPY0FBP0ISM_OTHERC_GPYF0ZR0_LTCCLK_NOEGXBARCLK_NOBG)); //$= 53
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_F0_0GPYF0LTS0GPY0FBP0ISM_OTHERC_GPYF0LTS0_LTCCLK_LTS0_NOEG__)); //$= 103
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_F0_0GPYF0LTS1GPY0FBP0ISM_OTHERC_GPYF0LTS1_LTCCLK_LTS1_NOEG__)); //$= 153
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_6_F0_0GPYF0PAL0GPY0FBP0ISM_OTHERC_GPYF0PAL0_LTCCLK_NOEGLTCCLK_FBLTC_PA0)); //$= 203
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_7_F0_0GPYF0PAF0GPY0FBP0ISM_OTHERC_GPYF0PAF0_LTCCLK_NOEGLTCCLK_NOBG)); //$= 253
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_F0_0GPYF0LTS3GPY0FBP0ISM_OTHERC_GPYF0LTS3_LTCCLK_LTS3_NOEG__)); //$= 303
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_F0_0GPYF0LTS2GPY0FBP0ISM_OTHERC_GPYF0LTS2_LTCCLK_LTS2_NOEG__)); //$= 353
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_9_F0_0GPYF0ZR1GPY0FBP0ISM_OTHERC_GPYF0ZR1_LTCCLK_NOEGXBARCLK_NOBG)); //$= 403
        GP107SpeedoChains[0].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_5_F0_0GPYF0CR1GPY0FBP0ISM_OTHERC_GPYF0CR1_LTCCLK_NOBG__)); //$= 453

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_F0_0_ISM_ROSC_BIN_METAL_GP107_ID,  //InstrId=0xB9//$
        LW_ISM_CHAIN_F0_0_ISM_ROSC_BIN_METAL_GP107_WIDTH,  //Size=60(in bits)//$
        LW_ISM_CHAIN_F0_0_ISM_ROSC_BIN_METAL_GP107_CHIPLET_SEL,  //Chiplet=4//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[1].ISMs.reserve(1);
        GP107SpeedoChains[1].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_metal,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F0_0_ISM_ROSC_BIN_METAL_GP107_ISM_ROSC_BIN_METAL_0_F0_0GPYF0PAL0GPY0FBP0ISM_BIN_METALC_GPYF0PAL0)); //$= 7

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ID,  //InstrId=0xB5//$
        LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_WIDTH,  //Size=506(in bits)//$
        LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_CHIPLET_SEL,  //Chiplet=2//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[2].ISMs.reserve(10);
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_F1_0GPYF1LTS0GPY1FBP0ISM_OTHERC_GPYF1LTS0_LTCCLK_LTS0_NOEG__)); //$= 5
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_F1_0GPYF1CR0GPY1FBP0ISM_OTHERC_GPYF1CR0_LTCCLK_NOBG__)); //$= 55
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_8_F1_0GPYF1ZR0GPY1FBP0ISM_OTHERC_GPYF1ZR0_LTCCLK_NOEGXBARCLK_NOBG)); //$= 105
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_F1_0GPYF1LTS1GPY1FBP0ISM_OTHERC_GPYF1LTS1_LTCCLK_LTS1_NOEG__)); //$= 155
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_6_F1_0GPYF1PAL0GPY1FBP0ISM_OTHERC_GPYF1PAL0_LTCCLK_NOEGLTCCLK_FBLTC_PA0)); //$= 205
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_7_F1_0GPYF1PAF0GPY1FBP0ISM_OTHERC_GPYF1PAF0_LTCCLK_NOEGLTCCLK_NOBG)); //$= 255
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_F1_0GPYF1LTS3GPY1FBP0ISM_OTHERC_GPYF1LTS3_LTCCLK_LTS3_NOEG__)); //$= 305
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_F1_0GPYF1LTS2GPY1FBP0ISM_OTHERC_GPYF1LTS2_LTCCLK_LTS2_NOEG__)); //$= 355
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_5_F1_0GPYF1CR1GPY1FBP0ISM_OTHERC_GPYF1CR1_LTCCLK_NOBG__)); //$= 405
        GP107SpeedoChains[2].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_9_F1_0GPYF1ZR1GPY1FBP0ISM_OTHERC_GPYF1ZR1_LTCCLK_NOEGXBARCLK_NOBG)); //$= 455

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_F1_0_ISM_ROSC_BIN_METAL_GP107_ID,  //InstrId=0xB9//$
        LW_ISM_CHAIN_F1_0_ISM_ROSC_BIN_METAL_GP107_WIDTH,  //Size=60(in bits)//$
        LW_ISM_CHAIN_F1_0_ISM_ROSC_BIN_METAL_GP107_CHIPLET_SEL,  //Chiplet=2//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[3].ISMs.reserve(1);
        GP107SpeedoChains[3].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_metal,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_F1_0_ISM_ROSC_BIN_METAL_GP107_ISM_ROSC_BIN_METAL_0_F1_0GPYF1PAL0GPY1FBP0ISM_BIN_METALC_GPYF1PAL0)); //$= 9

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ID,  //InstrId=0xB5//$
        LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_WIDTH,  //Size=1512(in bits)//$
        LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[4].ISMs.reserve(30);
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_0GPY0STPC0GPYT0PEGPY0TPC0ISM_OTHERC_GPYT0PE_GPCCLK_NOBG__)); //$= 4
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_1ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 55
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_1ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 105
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_0ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 156
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_0ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 206
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_ALLC_GPYSM0SMIO_GPCCLK_NOBG__)); //$= 256
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_0GPY0STPC0GPYT0TX0GPY0TPC0ISM_OTHERC_GPYT0TX0_GPCCLK_NOBG__)); //$= 306
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPY0STPC0GPYT0TX1GPY0TPC0ISM_OTHERC_GPYT0TX1_GPCCLK_NOBG__)); //$= 356
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_0GPY0STPC1GPYT0PEGPY0TPC0ISM_OTHERC_GPYT0PE_GPCCLK_NOBG__)); //$= 406
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_1ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 457
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_1ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 507
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_0ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 558
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_0ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 608
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_ALLC_GPYSM0SMIO_GPCCLK_NOBG__)); //$= 658
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_0GPY0STPC1GPYT0TX0GPY0TPC0ISM_OTHERC_GPYT0TX0_GPCCLK_NOBG__)); //$= 708
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPY0STPC1GPYT0TX1GPY0TPC0ISM_OTHERC_GPYT0TX1_GPCCLK_NOBG__)); //$= 758
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_0GPY0STPC2GPYT0PEGPY0TPC0ISM_OTHERC_GPYT0PE_GPCCLK_NOBG__)); //$= 808
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_1ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 859
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_1ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 909
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_0ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 960
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_0ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 1010
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_ALLC_GPYSM0SMIO_GPCCLK_NOBG__)); //$= 1060
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_0GPY0STPC2GPYT0TX0GPY0TPC0ISM_OTHERC_GPYT0TX0_GPCCLK_NOBG__)); //$= 1110
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPY0STPC2GPYT0TX1GPY0TPC0ISM_OTHERC_GPYT0TX1_GPCCLK_NOBG__)); //$= 1160
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_0GPYG0SCGPY0GPC0ISM_ALLC_GPYG0SC_GPCCLK_NOBG__)); //$= 1210
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_0GPYG0ZFGPY0GPC0ISM_ALLC_GPYG0ZF_GPCCLK_NOBG__)); //$= 1260
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPYP0PESGPY0PPC0ISM_ALLC_GPYP0PES_GPCCLK_NOBG__)); //$= 1310
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_0GPYG0GPGPY0GPC0ISM_ALLC_GPYG0GP_GPCCLK_NOEG__)); //$= 1360
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_0GPYG0ROGPY0GPC0ISM_ALLC_GPYG0RO_GPCCLK_NOBG__)); //$= 1410
        GP107SpeedoChains[4].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_0GPYG0XBGGPY0GPC0ISM_ALLC_GPYG0XBG_GPCCLK_NOEGXBARCLK_NOBG)); //$= 1460

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_0_ISM_NMEAS_AO_GP107_ID,  //InstrId=0xB6//$
        LW_ISM_CHAIN_G0_0_ISM_NMEAS_AO_GP107_WIDTH,  //Size=154(in bits)//$
        LW_ISM_CHAIN_G0_0_ISM_NMEAS_AO_GP107_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[5].ISMs.reserve(1);
        GP107SpeedoChains[5].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_NMEAS_AO_GP107_ISM_NMEAS3_ISM_NMEAS_AO_0_G0_0GPYP0PESGPY0GPC0GPC_LOGICGPCPWRC_GPYG0XBG_GPCCLK_NOBG)); //$= 36

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_0_ISM_ROSC_BIN_AGING_GP107_ID,  //InstrId=0xB8//$
        LW_ISM_CHAIN_G0_0_ISM_ROSC_BIN_AGING_GP107_WIDTH,  //Size=270(in bits)//$
        LW_ISM_CHAIN_G0_0_ISM_ROSC_BIN_AGING_GP107_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[6].ISMs.reserve(3);
        GP107SpeedoChains[6].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_G0_0GPY0STPC0GPYT0TX1GPY0TPC0ISM_BINC_GPYT0TX1)); //$= 13
        GP107SpeedoChains[6].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_G0_0GPY0STPC1GPYT0TX1GPY0TPC0ISM_BINC_GPYT0TX1)); //$= 99
        GP107SpeedoChains[6].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_G0_0GPY0STPC2GPYT0TX1GPY0TPC0ISM_BINC_GPYT0TX1)); //$= 185

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_0_ISM_TSOSC_A2_GP107_ID,  //InstrId=0xBB//$
        LW_ISM_CHAIN_G0_0_ISM_TSOSC_A2_GP107_WIDTH,  //Size=180(in bits)//$
        LW_ISM_CHAIN_G0_0_ISM_TSOSC_A2_GP107_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[7].ISMs.reserve(3);
        GP107SpeedoChains[7].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_TSOSC_a2,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_TSOSC_A2_GP107_ISM_TSOSC_A2_0_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_TSOSCC_GPYSM0SMIO)); //$= 11
        GP107SpeedoChains[7].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_TSOSC_a2,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_TSOSC_A2_GP107_ISM_TSOSC_A2_0_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_TSOSCC_GPYSM0SMIO)); //$= 67
        GP107SpeedoChains[7].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_TSOSC_a2,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_ISM_TSOSC_A2_GP107_ISM_TSOSC_A2_0_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_TSOSCC_GPYSM0SMIO)); //$= 123

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ID,  //InstrId=0xB1//$
        LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_WIDTH,  //Size=714(in bits)//$
        LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[8].ISMs.reserve(6);
        GP107SpeedoChains[8].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 5
        GP107SpeedoChains[8].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 120
        GP107SpeedoChains[8].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 239
        GP107SpeedoChains[8].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 354
        GP107SpeedoChains[8].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 473
        GP107SpeedoChains[8].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 588

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ID,  //InstrId=0xB2//$
        LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_WIDTH,  //Size=714(in bits)//$
        LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[9].ISMs.reserve(6);
        GP107SpeedoChains[9].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 5
        GP107SpeedoChains[9].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_0GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 120
        GP107SpeedoChains[9].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 239
        GP107SpeedoChains[9].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_0GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 354
        GP107SpeedoChains[9].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 473
        GP107SpeedoChains[9].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_0_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_0GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 588

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ID,  //InstrId=0xB5//$
        LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_WIDTH,  //Size=1512(in bits)//$
        LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_CHIPLET_SEL,  //Chiplet=5//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[10].ISMs.reserve(30);
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_1GPY0STPC0GPYT0PEGPY0TPC0ISM_OTHERC_GPYT0PE_GPCCLK_NOBG__)); //$= 2
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_1ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 53
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_1ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 103
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_0ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 154
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_0ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 204
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_ALLC_GPYSM0SMIO_GPCCLK_NOBG__)); //$= 254
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_1GPY0STPC0GPYT0TX0GPY0TPC0ISM_OTHERC_GPYT0TX0_GPCCLK_NOBG__)); //$= 304
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPY0STPC0GPYT0TX1GPY0TPC0ISM_OTHERC_GPYT0TX1_GPCCLK_NOBG__)); //$= 354
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_1GPY0STPC1GPYT0PEGPY0TPC0ISM_OTHERC_GPYT0PE_GPCCLK_NOBG__)); //$= 404
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_1ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 455
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_1ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 505
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_0ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 556
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_0ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 606
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_ALLC_GPYSM0SMIO_GPCCLK_NOBG__)); //$= 656
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_1GPY0STPC1GPYT0TX0GPY0TPC0ISM_OTHERC_GPYT0TX0_GPCCLK_NOBG__)); //$= 706
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPY0STPC1GPYT0TX1GPY0TPC0ISM_OTHERC_GPYT0TX1_GPCCLK_NOBG__)); //$= 756
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_1GPY0STPC2GPYT0PEGPY0TPC0ISM_OTHERC_GPYT0PE_GPCCLK_NOBG__)); //$= 806
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_1ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 857
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_1ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 907
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQA_0ISM_ALLC_GPYSM0SDLQA_1_GPCCLK_NOBG__)); //$= 958
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SDLQB_0ISM_ALLC_GPYSM0SDLQB_1_GPCCLK_NOBG__)); //$= 1008
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_ALLC_GPYSM0SMIO_GPCCLK_NOBG__)); //$= 1058
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_1GPY0STPC2GPYT0TX0GPY0TPC0ISM_OTHERC_GPYT0TX0_GPCCLK_NOBG__)); //$= 1108
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPY0STPC2GPYT0TX1GPY0TPC0ISM_OTHERC_GPYT0TX1_GPCCLK_NOBG__)); //$= 1158
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_G0_1GPYG0SCGPY0GPC0ISM_ALLC_GPYG0SC_GPCCLK_NOBG__)); //$= 1208
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_G0_1GPYG0ZFGPY0GPC0ISM_ALLC_GPYG0ZF_GPCCLK_NOBG__)); //$= 1258
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPYP0PESGPY0PPC0ISM_ALLC_GPYP0PES_GPCCLK_NOBG__)); //$= 1308
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_G0_1GPYG0GPGPY0GPC0ISM_ALLC_GPYG0GP_GPCCLK_NOEG__)); //$= 1358
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_G0_1GPYG0ROGPY0GPC0ISM_ALLC_GPYG0RO_GPCCLK_NOBG__)); //$= 1408
        GP107SpeedoChains[10].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_G0_1GPYG0XBGGPY0GPC0ISM_ALLC_GPYG0XBG_GPCCLK_NOEGXBARCLK_NOBG)); //$= 1458

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_1_ISM_NMEAS_AO_GP107_ID,  //InstrId=0xB6//$
        LW_ISM_CHAIN_G0_1_ISM_NMEAS_AO_GP107_WIDTH,  //Size=154(in bits)//$
        LW_ISM_CHAIN_G0_1_ISM_NMEAS_AO_GP107_CHIPLET_SEL,  //Chiplet=5//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[11].ISMs.reserve(1);
        GP107SpeedoChains[11].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_NMEAS_AO_GP107_ISM_NMEAS3_ISM_NMEAS_AO_0_G0_1GPYP0PESGPY0GPC0GPC_LOGICGPCPWRC_GPYG0XBG_GPCCLK_NOBG)); //$= 34

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_1_ISM_ROSC_BIN_AGING_GP107_ID,  //InstrId=0xB8//$
        LW_ISM_CHAIN_G0_1_ISM_ROSC_BIN_AGING_GP107_WIDTH,  //Size=270(in bits)//$
        LW_ISM_CHAIN_G0_1_ISM_ROSC_BIN_AGING_GP107_CHIPLET_SEL,  //Chiplet=5//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[12].ISMs.reserve(3);
        GP107SpeedoChains[12].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_G0_1GPY0STPC0GPYT0TX1GPY0TPC0ISM_BINC_GPYT0TX1)); //$= 11
        GP107SpeedoChains[12].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_G0_1GPY0STPC1GPYT0TX1GPY0TPC0ISM_BINC_GPYT0TX1)); //$= 97
        GP107SpeedoChains[12].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_G0_1GPY0STPC2GPYT0TX1GPY0TPC0ISM_BINC_GPYT0TX1)); //$= 183

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_1_ISM_TSOSC_A2_GP107_ID,  //InstrId=0xBB//$
        LW_ISM_CHAIN_G0_1_ISM_TSOSC_A2_GP107_WIDTH,  //Size=180(in bits)//$
        LW_ISM_CHAIN_G0_1_ISM_TSOSC_A2_GP107_CHIPLET_SEL,  //Chiplet=5//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[13].ISMs.reserve(3);
        GP107SpeedoChains[13].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_TSOSC_a2,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_TSOSC_A2_GP107_ISM_TSOSC_A2_0_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_TSOSCC_GPYSM0SMIO)); //$= 9
        GP107SpeedoChains[13].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_TSOSC_a2,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_TSOSC_A2_GP107_ISM_TSOSC_A2_0_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_TSOSCC_GPYSM0SMIO)); //$= 65
        GP107SpeedoChains[13].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_TSOSC_a2,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_ISM_TSOSC_A2_GP107_ISM_TSOSC_A2_0_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SMIOISM_TSOSCC_GPYSM0SMIO)); //$= 121

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ID,  //InstrId=0xB1//$
        LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_WIDTH,  //Size=714(in bits)//$
        LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_CHIPLET_SEL,  //Chiplet=5//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[14].ISMs.reserve(6);
        GP107SpeedoChains[14].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 3
        GP107SpeedoChains[14].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 118
        GP107SpeedoChains[14].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 237
        GP107SpeedoChains[14].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 352
        GP107SpeedoChains[14].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 471
        GP107SpeedoChains[14].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_GP107_ISM_NMEAS3_ISM_NMEAS_0_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 586

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ID,  //InstrId=0xB2//$
        LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_WIDTH,  //Size=714(in bits)//$
        LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_CHIPLET_SEL,  //Chiplet=5//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[15].ISMs.reserve(6);
        GP107SpeedoChains[15].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 3
        GP107SpeedoChains[15].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_1GPY0STPC0GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 118
        GP107SpeedoChains[15].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 237
        GP107SpeedoChains[15].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_1GPY0STPC1GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 352
        GP107SpeedoChains[15].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLBSMMU_COREU_SCTL_P1C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 471
        GP107SpeedoChains[15].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_G0_1_NONAO_ISM_NMEAS_SRAM_GP107_ISM_NMEAS3_ISM_NMEAS_SRAM_0_G0_1GPY0STPC2GPY0TPC0TPC0SMMMIOGPYSM0SCTLASMMU_COREU_SCTL_P0C_GPYSM0SCTLA_GPCCLK_NOBG)); //$= 586

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_AGING_GP107_ID,  //InstrId=0xB4//$
        LW_ISM_CHAIN_SX0_0_ISM_AGING_GP107_WIDTH,  //Size=84(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_AGING_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[16].ISMs.reserve(1);
        GP107SpeedoChains[16].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_aging,                    Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_AGING_GP107_ISM_AGING_0_SX0_0GPYS0CE0SYSISM_AGINGC_GPYS0CE0_SYSCLK_NOEG)); //$= 29

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_CTRL3_GP107_ID,  //InstrId=0xB3//$
        LW_ISM_CHAIN_SX0_0_ISM_CTRL3_GP107_WIDTH,  //Size=101(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_CTRL3_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[17].ISMs.reserve(1);
        GP107SpeedoChains[17].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ctrl_v3,                  Ism::IsmFlags::PRIMARY, LW_ISM_CHAIN_SX0_0_ISM_CTRL3_GP107_GPYS0CE0_LW_ISM)); //$= 29

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ID,  //InstrId=0xB5//$
        LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_WIDTH,  //Size=1207(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[18].ISMs.reserve(24);
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_SX0_0GPYS0HBSYSISM_LEFTC_GPYS0HB_SYSCLK_NOEGHOSTCLK_NOBG)); //$= 6
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_SX0_0GPYS0XPSYSISM_LEFTC_GPYS0XP_HOSTCLK_NOBGPEX_PAD_TCLKOUT_IN_ISM)); //$= 56
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_6_SX0_0GPYS0MSE01SYSISM_LEFTC_GPYS0MSE01_SYSCLK_NOEGLWDCLK_NOBG_LWENC0)); //$= 106
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_8_SX0_0GPYS0MSE03SYSISM_LEFTC_GPYS0MSE03_SYSCLK_NOEGLWDCLK_NOBG_LWENC0)); //$= 156
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_7_SX0_0GPYS0MSE02SYSISM_LEFTC_GPYS0MSE02_SYSCLK_NOEGLWDCLK_NOBG_LWENC0)); //$= 206
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_5_SX0_0GPYS0MSE00SYSISM_LEFTC_GPYS0MSE00_SYSCLK_NOEGLWDCLK_NOBG_LWENC0)); //$= 256
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_3_SX0_0GPYS0XVSYSISM_LEFTC_GPYS0XV_HOSTCLK_NOBGXCLK_NOBG)); //$= 306
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_SX0_0GPYS0FESYSISM_RIGHTC_GPYS0FE_SYSCLK_NOEG__)); //$= 356
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_SX0_0GPYS0PDSYSISM_LEFTC_GPYS0PD_SYSCLK_NOEG__)); //$= 406
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_9_SX0_0GPYS0MSD0SYSISM_LEFTC_GPYS0MSD0_SYSCLK_NOEGLWDCLK_NOBG_LWDEC)); //$= 456
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_5_SX0_0GPYS0DI3SYSISM_RIGHTC_GPYS0DI3_SYSCLK_NOEGHOSTCLK)); //$= 506
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_10_SX0_0GPYS0MSD1SYSISM_LEFTC_GPYS0MSD1_SYSCLK_NOEGLWDCLK_NOBG_LWDEC)); //$= 556
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_SX0_0GPYS0NESYSISM_RIGHTC_GPYS0NE_SYSCLK_NOEG__)); //$= 606
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_0_SX0_0GPYX0XXBARISM_OTHERC_GPYX0X_XBARCLK_NOBGSYSCLK_NOEG)); //$= 656
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_2_SX0_0GPYS0NISYSISM_RIGHTC_GPYS0NI_SYSCLK_NOEGHOSTCLK)); //$= 706
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_12_SX0_0GPYS0MSD3SYSISM_LEFTC_GPYS0MSD3_SYSCLK_NOEGLWDCLK_NOBG_LWDEC)); //$= 756
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_11_SX0_0GPYS0MSD2SYSISM_LEFTC_GPYS0MSD2_SYSCLK_NOEGLWDCLK_NOBG_LWDEC)); //$= 806
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_4_SX0_0GPYS0DHSYSISM_RIGHTC_GPYS0DH_SYSCLK_NOEGHUBCLK_NOBG)); //$= 856
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_9_SX0_0GPYS0DI1SYSISM_RIGHTC_GPYS0DI1_DISPCLK__)); //$= 906
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_8_SX0_0GPYS0DI2SYSISM_RIGHTC_GPYS0DI2_DAC1_CLKDISPCLK)); //$= 956
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_7_SX0_0GPYS0DVSYSISM_RIGHTC_GPYS0DV_SYSCLK_NOEGDISPCLK)); //$= 1006
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_6_SX0_0GPYS0DSSYSISM_RIGHTC_GPYS0DS_SYSCLK_NOEG__)); //$= 1056
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_v2,             Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_V2_1_SX0_0GPYS0PWSYSISM_LEFTC_GPYS0PW_SYSCLK_NOEGPWRCLK_NOBG)); //$= 1106
        GP107SpeedoChains[18].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk_dbg_v2,         Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_MINI_2CLK_GP107_ISM_MINI_2CLK_DBG_V2_3_SX0_0GPYS0CE0SYSISM_RIGHTC_GPYS0CE0_SYSCLK_NOEGSYSCLK_NOEG)); //$= 1156

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_NMEAS_AO_GP107_ID,  //InstrId=0xB6//$
        LW_ISM_CHAIN_SX0_0_ISM_NMEAS_AO_GP107_WIDTH,  //Size=254(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_NMEAS_AO_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[19].ISMs.reserve(2);
        GP107SpeedoChains[19].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_NMEAS_AO_GP107_ISM_NMEAS3_ISM_NMEAS_AO_0_SX0_0GPYS0FESYSISM_NMC_GPYS0FE_SYSCLK_NOEG)); //$= 13
        GP107SpeedoChains[19].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_NMEAS_v3,                 Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_NMEAS_AO_GP107_ISM_NMEAS3_ISM_NMEAS_AO_0_SX0_0GPYS0DI1SYSISM_NM1C_GPYS0DI1_DISPCLK)); //$= 136

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_AGING_GP107_ID,  //InstrId=0xB8//$
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_AGING_GP107_WIDTH,  //Size=182(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_AGING_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[20].ISMs.reserve(2);
        GP107SpeedoChains[20].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_SX0_0GPYS0CE0SYSISM_BIN0C_GPYS0CE0)); //$= 29
        GP107SpeedoChains[20].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_AGING_GP107_ISM_ROSC_BIN_AGING_0_SX0_0GPYS0CE0SYSISM_BIN1C_GPYS0CE0)); //$= 105

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_METAL_GP107_ID,  //InstrId=0xB9//$
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_METAL_GP107_WIDTH,  //Size=74(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_METAL_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[21].ISMs.reserve(1);
        GP107SpeedoChains[21].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_bin_metal,           Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_ROSC_BIN_METAL_GP107_ISM_ROSC_BIN_METAL_0_SX0_0GPYS0MSE03SYSISM_BIN_METALC_GPYS0MSE03)); //$= 9

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_COMP_GP107_ID,  //InstrId=0xBA//$
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_COMP_GP107_WIDTH,  //Size=77(in bits)//$
        LW_ISM_CHAIN_SX0_0_ISM_ROSC_COMP_GP107_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[22].ISMs.reserve(1);
        GP107SpeedoChains[22].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_ROSC_comp,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_SX0_0_ISM_ROSC_COMP_GP107_ISM_ROSC_COMP_0_SX0_0GPYS0DVSYSISM_COMPC_GPYS0DV)); //$= 26

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_ID,  //InstrId=0xAF//$
        LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_WIDTH,  //Size=573(in bits)//$
        LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_CHIPLET_SEL,  //Chiplet=6//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[23].ISMs.reserve(16);
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE0C_BYTE_BR4CLKFB2FBIO_M)); //$= 2
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE7C_BYTE_BR4CLKFB2FBIO_M)); //$= 37
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE3C_BYTE_BR4CLKFB2FBIO_M)); //$= 72
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE2C_BYTE_BR4CLKFB2FBIO_M)); //$= 107
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE1C_BYTE_BR4CLKFB2FBIO_M)); //$= 142
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE5C_BYTE_BR4CLKFB2FBIO_M)); //$= 177
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE4C_BYTE_BR4CLKFB2FBIO_M)); //$= 212
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOALS_BYTE6C_BYTE_BR4CLKFB2FBIO_M)); //$= 247
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE7C_BYTE_BR4CLKFB2FBIO_M)); //$= 284
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE2C_BYTE_BR4CLKFB2FBIO_M)); //$= 319
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE4C_BYTE_BR4CLKFB2FBIO_M)); //$= 354
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE0C_BYTE_BR4CLKFB2FBIO_M)); //$= 389
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE6C_BYTE_BR4CLKFB2FBIO_M)); //$= 424
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE1C_BYTE_BR4CLKFB2FBIO_M)); //$= 459
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE5C_BYTE_BR4CLKFB2FBIO_M)); //$= 494
        GP107SpeedoChains[23].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_BYTE_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_BYTE_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOBLS_BYTE3C_BYTE_BR4CLKFB2FBIO_M)); //$= 529

    GP107SpeedoChains.push_back(GpuIsm::IsmChain(
        LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_ID,  //InstrId=0xB0//$
        LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_WIDTH,  //Size=153(in bits)//$
        LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_CHIPLET_SEL,  //Chiplet=6//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        GP107SpeedoChains[24].ISMs.reserve(4);
        GP107SpeedoChains[24].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_CMD_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOA_CMD_SUBP1C_CMD_BR4CLKFB2FBIO_M)); //$= 2
        GP107SpeedoChains[24].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_CMD_0_T0_0GPYPAD0FBA0TOP_PADSU_FBAFBIOA_CMD_SUBP0C_CMD_BR4CLKFB2FBIO_M)); //$= 37
        GP107SpeedoChains[24].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_CMD_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOB_CMD_SUBP1C_CMD_BR4CLKFB2FBIO_M)); //$= 74
        GP107SpeedoChains[24].ISMs.push_back(GpuIsm::IsmRef(Ism::LW_ISM_MINI_2clk,                Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_T0_0_ISM_CHAIN_FBIO_MINI_CMD_GP107_MINI_2CLK_ISM_CHAIN_ISM_MINI_CMD_0_T0_0GPYPAD0FBB0TOP_PADSU_FBBFBIOB_CMD_SUBP0C_CMD_BR4CLKFB2FBIO_M)); //$= 109

}
