/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */
#include "lwswitch/svnp01/dev_ism.h"
    //--------------------------------------------------------------------------
    // 2021-07-23 13:35:39.616947
    // This table was auto generated by:/sw/dev/gpu_drv/chips_a/diag/mods/gpu/ism/parse_dev_ism.py
    // Source file:/sw/dev/gpu_drv/chips_a/drivers/common/inc/hwref/lwswitch/svnp01/dev_ism.h
    // Do not modify contents
    //--------------------------------------------------------------------------
    //ISM Chains:3
    //Max ISMs in a single chain:    1
    //LW_ISM_MINI_1clk_no_ext_ro_dbg:0
    //LW_ISM_MINI_1clk_no_ext_ro:0
    //LW_ISM_MINI_1clk_dbg:0
    //LW_ISM_MINI_1clk:0
    //LW_ISM_MINI_2clk_no_ext_ro:0
    //LW_ISM_MINI_2clk_dbg_v3:0
    //LW_ISM_MINI_2clk_dbg_v2:0
    //LW_ISM_MINI_2clk_dbg:0
    //LW_ISM_MINI_2clk_v2:0
    //LW_ISM_MINI_2clk:0
    //LW_ISM_ROSC_bin_metal:0
    //LW_ISM_ROSC_bin_aging_v1:3
    //LW_ISM_ROSC_bin_aging:0
    //LW_ISM_ROSC_bin_v3:0
    //LW_ISM_ROSC_bin_v2:0
    //LW_ISM_ROSC_bin_v1:0
    //LW_ISM_ROSC_bin:0
    //LW_ISM_ROSC_comp_v1:0
    //LW_ISM_ROSC_comp:0
    //LW_ISM_VNSENSE_ddly:0
    //LW_ISM_TSOSC_a4:0
    //LW_ISM_TSOSC_a3:0
    //LW_ISM_TSOSC_a2:0
    //LW_ISM_TSOSC_a:0
    //LW_ISM_NMEAS_lite_v9:0
    //LW_ISM_NMEAS_lite_v8:0
    //LW_ISM_NMEAS_lite_v7:0
    //LW_ISM_NMEAS_lite_v6:0
    //LW_ISM_NMEAS_lite_v5:0
    //LW_ISM_NMEAS_lite_v4:0
    //LW_ISM_NMEAS_lite_v3:0
    //LW_ISM_NMEAS_lite_v2:0
    //LW_ISM_NMEAS_lite:0
    //LW_ISM_NMEAS_v4:0
    //LW_ISM_NMEAS_v3:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_HOLD:0
    //LW_ISM_aging_v4:0
    //LW_ISM_aging_v3:0
    //LW_ISM_aging_v2:0
    //LW_ISM_aging_v1:0
    //LW_ISM_aging:0
    //LW_ISM_cpm_v5:0
    //LW_ISM_cpm_v4:0
    //LW_ISM_cpm_v3:0
    //LW_ISM_cpm_v2:0
    //LW_ISM_cpm_v1:0
    //LW_ISM_cpm:0
    //LW_ISM_imon:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_NMEAS_v2:0
    //LW_ISM_ctrl_v4:0
    //LW_ISM_ctrl_v3:0
    //LW_ISM_ctrl_v2:0
    //LW_ISM_ctrl:0
    //--------------------------------------------------------------------------
    // SVNP01 ISM TABLE
    //--------------------------------------------------------------------------
vector<LwSwitchIsm::IsmChain> SVNP01SpeedoChains;
void InitializeSVNP01SpeedoChains()
{
    SVNP01SpeedoChains.clear();
    SVNP01SpeedoChains.reserve(3);
    SVNP01SpeedoChains.push_back(LwSwitchIsm::IsmChain(
        LW_ISM_CHAIN_P0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_ID,  //InstrId=0xB8//$
        LW_ISM_CHAIN_P0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_WIDTH,  //Size=104(in bits)//$
        LW_ISM_CHAIN_P0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_CHIPLET_SEL,  //Chiplet=2//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        SVNP01SpeedoChains[0].ISMs.reserve(1);
        SVNP01SpeedoChains[0].ISMs.push_back(LwSwitchIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging_v1,        Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_P0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_ISM_ROSC_BIN_AGING_0_P0_0SVAP0QLNK0BISM_BINC_SVAP0QLNK0B)); //$= 4

    SVNP01SpeedoChains.push_back(LwSwitchIsm::IsmChain(
        LW_ISM_CHAIN_P0_1_ISM_ROSC_BIN_AGING_V1_SVNP01_ID,  //InstrId=0xB8//$
        LW_ISM_CHAIN_P0_1_ISM_ROSC_BIN_AGING_V1_SVNP01_WIDTH,  //Size=104(in bits)//$
        LW_ISM_CHAIN_P0_1_ISM_ROSC_BIN_AGING_V1_SVNP01_CHIPLET_SEL,  //Chiplet=3//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        SVNP01SpeedoChains[1].ISMs.reserve(1);
        SVNP01SpeedoChains[1].ISMs.push_back(LwSwitchIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging_v1,        Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_P0_1_ISM_ROSC_BIN_AGING_V1_SVNP01_ISM_ROSC_BIN_AGING_0_P0_1SVAP0QLNK0BISM_BINC_SVAP0QLNK0B)); //$= 3

    SVNP01SpeedoChains.push_back(LwSwitchIsm::IsmChain(
        LW_ISM_CHAIN_S0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_ID,  //InstrId=0xB8//$
        LW_ISM_CHAIN_S0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_WIDTH,  //Size=103(in bits)//$
        LW_ISM_CHAIN_S0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_CHIPLET_SEL,  //Chiplet=1//$
        ~0, //Sfe=undefined
        ~0, //VstCtrl=undefined
        ~0, //VstData=undefined
        Ism::NORMAL_CHAIN));  //Flags
        // ISMs in the chain (type, flags, startBit)
        SVNP01SpeedoChains[2].ISMs.reserve(1);
        SVNP01SpeedoChains[2].ISMs.push_back(LwSwitchIsm::IsmRef(Ism::LW_ISM_ROSC_bin_aging_v1,        Ism::IsmFlags::FLAGS_NONE, LW_ISM_CHAIN_S0_0_ISM_ROSC_BIN_AGING_V1_SVNP01_ISM_ROSC_BIN_AGING_0_S0_0SVAS0XPXVISM_BINC_SVAS0XPXV)); //$= 7

}
