#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2021 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

# Add AD102 ROMs
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_simgddr6.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emugddr6.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_p-states_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate_short-gpioinit_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_simgddr6x.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_ecc_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_p8-imp.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_nafll.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_cml.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_cml_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_cml_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_cml_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_cml_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emugddr6_dispmacro.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_miata.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_simgddr6_miata.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_simgddr6_dispmacro.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_ecc_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_nodisplay_mem-16gb_perf.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_dcb-ultimate_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_dcb-ultimate_short-gpioinit_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dispmacro_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dispmacro_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emugddr6_miata.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_p-states_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_p-states_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_p-states_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_p-states_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emugddr6_clk40.zbx
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_clk40.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_clk40_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_clk40_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_clk40_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_clk40_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_p-states_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_clk40_nodisplay_mem-16gb_initial_bringup.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_p-states.frts

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_si_clocks.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_si_clocks_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_dcb-ultimate_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_si_clocks.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_dcb-ultimate_short-gpioinit_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_si_clocks_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_si_clocks_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_si_clocks_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_si_clocks_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_si_clocks.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_si_clocks_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_si_clocks_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_si_clocks_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_dcb-ultimate-qt.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_si_clocks_dcb-ultimate-qt_short-gpioinit.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_si_clocks_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_si_clocks_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_p-states_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_si_clocks_dcb-ultimate-qt_short-gpioinit.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_p-states_nodisplay_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_p-states_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_p-states_dcb-ultimate.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_cmos_dcb-ultimate_short-gpioinit.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_dcb-ultimate_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_p-states_dcb-ultimate-qt_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6x_cmos_p-states_dcb-ultimate_short-gpioinit.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate_short-gpioinit.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_dcb-ultimate_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml_nodisplay_mem-16gb_1gb_bar1.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml_dcb-ultimate-qt_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate_short-gpioinit_deviceid-ad106.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate_short-gpioinit_deviceid-ad104.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_nodisplay_mem-16gb_deviceid-ad107.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate_mem-16gb_deviceid-ad103.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate_mem-16gb_deviceid-ad104.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate_mem-16gb_deviceid-ad107.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_nodisplay_mem-16gb_deviceid-ad103.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_nodisplay_mem-16gb_deviceid-ad106.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_nodisplay_deviceid-ad103.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_dcb-ultimate_mem-16gb_deviceid-ad106.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate_short-gpioinit_deviceid-ad107.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_dcb-ultimate_short-gpioinit_deviceid-ad103.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_nodisplay_deviceid-ad107.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_nodisplay_mem-16gb_deviceid-ad104.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_nodisplay_deviceid-ad106.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_nodisplay_deviceid-ad104.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_deviceid-ad103.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_deviceid-ad104.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_deviceid-ad106.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_sim_gddr6_deviceid-ad107.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_cml_nodisplay_mem-16gb_2gb_bar1.rom

internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_dcb-primary-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ad102_emu_gddr6_miata_dcb-primary-dp.rom
