#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2018 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_ecc-fmodel_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/g000_simhbm.zbx

internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm_ecc-fmodel_nodisplay_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5x.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5x_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5x_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr5_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr6_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_gddr6_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm3.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm3_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm3_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/g000_simhbm3.zbx

internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm3_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/g000_sim_hbm3_nodisplay.rom
