#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2021 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

# Add GA10f ROMs
internal_release_files$(ONLY_PC) += sim/resources/ga10f_sim_0fb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga10f_sim0fb.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga10f_emu_0fb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga10f_emu0fb.zbx
