#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2018 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

# Add GA100 ROMs
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_simhbm.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emuhbm.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_ecc_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_ecc-fmodel_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_ecc_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_p-states_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_nafll.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_nafll_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_nafll_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_nafll_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_nafll_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_nafll_ecc_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_hbm2e.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_hbm2e_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_hbm2e.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_hbm2e_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_4h.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_4h_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_4h_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_4h_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_deviceid-gh100.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_deviceid-gh100_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_deviceid-gh100_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_deviceid-gh100_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_deviceid-gh100_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_deviceid-gh100_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_initial_bringup.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_initial_bringup.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_p-states_initial_bringup_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_emu_hbm_initial_bringup_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_initial_bringup.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_p-states_initial_bringup.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_initial_bringup_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga100_sim_hbm_p-states_initial_bringup_no_ifr.rom
