#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2018 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

# Add GA102 ROMs
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr6.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_cmos_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_dp-ifpf.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_dp-ifpf_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_hdmi-ifpf.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_hdmi-ifpf_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr5.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_nodisplay_fmodel_no_meminit_delays_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_cmos_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr5x.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr5_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_nodisplay_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_nodisplay_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_dcb-ultimate_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_dcb-ultimate_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emugddr5.zbx
internal_release_files$(ONLY_PC) += sim/resources/ga102_emugddr6.zbx
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p-states.frts

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_mem-16gb_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5x_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr5_dcb-ultimate_mem-16gb_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpga_sddr3_nopll_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpga_sddr3_nopll_dldvi_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpga_sddr3_nopll_dp-mst_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpga_sddr3_nopll_dualsst_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpga_sddr3_nopll_head0_tmds.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpga_sddr3_nopll_head0_tmds_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_dcb-ultimate_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_dcb-ultimate_p8-imp.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_dcb-ultimate_p8-imp_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_short-gpioinit_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_short-gpioinit_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate_short-gpioinit_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga103_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga104_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga106_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_deviceid-ga107_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_nodisplay_fmodel_no_meminit_delays_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr6x.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_imp.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_imp_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_imp_p8-imp.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_imp_p8-imp_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_mem-16gb_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_ecc_nodisplay_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_mem-16gb_perf.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_mem-16gb_perf_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p8-imp.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_cmos_p8-imp_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_nafll.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_nafll_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_dcb-ultimate-qt_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_dcb-ultimate-qt_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_nodisplay_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_cml_nodisplay_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga107_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga106_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_deviceid-ga104_dcb-ultimate.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emugddr6_dispmacro.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_miata.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_miata_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr6_miata.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_dispmacro.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr6_dispmacro.zbx
internal_release_files$(ONLY_PC) += sim/resources/ga102f_fpgasddr3nopll_dispmacro.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_ecc_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_ecc_nodisplay_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_nodisplay_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_nodisplay_mem-16gb_perf.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_nodisplay_mem-16gb_perf_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_short-gpioinit.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_short-gpioinit_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_short-gpioinit_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate_short-gpioinit_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga103_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga104_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga106_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_ecc-fmodel_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_deviceid-ga107_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_tmds-ab_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_tmds-ab_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_tmds-ab.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_tmds-ab_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_tmds-ab_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_tmds-ab_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate-qt_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_nodisplay_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_nodisplay_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate-qt_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dcb-ultimate-qt_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate-qt.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_dcb-ultimate-qt_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate-qt_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_dispmacro_dcb-ultimate-qt_mem-16gb_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt-dp_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt-dp_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt-hdmi_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dispmacro_dcb-ultimate-qt-hdmi_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emugddr6_miata.zbx

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_mem-16gb_deviceid-ga104.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_dcb-ultimate-qt_mem-16gb_deviceid-ga104_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_mem-16gb_deviceid-ga104.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_nodisplay_mem-16gb_deviceid-ga104_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_p-states_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_p-states_nodisplay_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_p-states_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_dcb-ultimate-qt-dp_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_dcb-ultimate-qt-hdmi_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_miata_p-states_dcb-ultimate-qt-dp_mem-16gb.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emugddr6_clk40.zbx
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_dcb-ultimate_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_dcb-ultimate_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_mem-16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_mem-16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_simgddr6_clk40.zbx
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_clk40.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_clk40_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6_p-states_clk40_nodisplay.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/ga102_sim_gddr6x_cmos_p-states_nodisplay_fmodel_no_meminit_delays.rom

internal_release_files$(ONLY_PC) += sim/resources/ga102_emu_gddr6_p-states_clk40_nodisplay_mem-16gb_initial_bringup.rom
