#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2018 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

# Add GH100 ROMs
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_ecc-fmodel_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_ecc_no_ifr.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emuhbm.zbx

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_nafll.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_nafll_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_nafll_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_p-states_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_si_clocks.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_si_clocks_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_si_clocks_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm3.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm3_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm3_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm3_p-states_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3_ecc-fmodel.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_simhbm3.zbx

internal_release_files$(ONLY_PC) += sim/resources/gh100_emuhbm3.zbx

internal_release_files$(ONLY_PC) += sim/resources/gh100_riscvsimhbm.zbx

internal_release_files$(ONLY_PC) += sim/resources/gh100_simhbm_riscv.zbx

internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_riscv.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm_riscv_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_riscv.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_riscv_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_riscv_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emuhbm_riscv.zbx

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3_si_clocks.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3_si_clocks_ecc-fmodel.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3_si_clocks_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_emuhbm3_riscv.zbx
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm3_riscv.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_emu_hbm3_riscv_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm_p-states_ecc.rom

internal_release_files$(ONLY_PC) += sim/resources/gh100_sim_hbm3_p-states.rom
