#
# LWIDIA_COPYRIGHT_BEGIN
#
# Copyright 2018 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# LWIDIA_COPYRIGHT_END
#

# Note: This file is included in makeroms.inc

# TU117 roms
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emugddr6.zbx

internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_simgddr6.zbx

internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_simgddr5.zbx

internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_ecc-fmodel_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_simgddr5x.zbx

internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nafll_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr5x_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_dcb-ultimate_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_dcb-ultimate_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_ecc.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_ecc_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_ecc_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_ecc_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_nodisplay_g6_emu_16gb.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_nodisplay_g6_emu_16gb_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emu_gddr6_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_dcb-ultimate.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_fmodel_no_meminit_delays_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_nodisplay_fmodel_no_meminit_delays.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_nodisplay_fmodel_no_meminit_delays_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_cmos_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_dp-ifpf.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_dp-ifpf_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_cmos_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr5x_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_p-states.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_p-states_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_cmos_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_dcb-ultimate_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_ecc-fmodel_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_ecc_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_ecc_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_p-states_nodisplay.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6_p-states_nodisplay_no_ifr.rom
internal_release_files$(ONLY_PC) += sim/resources/tu117_emugddr5.zbx
internal_release_files$(ONLY_PC) += sim/resources/tu117_emugddr5x.zbx
internal_release_files$(ONLY_PC) += sim/resources/tu117_sim_gddr6.frts