//
// memory_enum_types.h
// DO NOT EDIT, generated by ness version 1.0, backend=c_struct
//
// Command: ../../lwtools/ness/bin/run_ispec_backend c_struct ../../defs/fermi/gf100/fermi.specdb defs.touch-c_struct1
#if !defined(_memory_enum_types_H_)
#define _memory_enum_types_H_

// ack_t enum values
#define ack_t_ENUM_DECL enum ack_t {ACK_NONE_REQUIRED = 0, ACK_GLOBALLY = 1, ACK_INTRANODE = 2};
#define  ENUM_ack_t_ACK_NONE_REQUIRED 0
#define  ENUM_ack_t_ACK_GLOBALLY 1
#define  ENUM_ack_t_ACK_INTRANODE 2
// aperture_t enum values
#define aperture_t_ENUM_DECL enum aperture_t {APERTURE_LOCAL_MEM = 0, APERTURE_P2P = 1, APERTURE_SYS_MEM_COHERENT = 2, APERTURE_SYS_MEM_NONCOHERENT = 3};
#define  ENUM_aperture_t_APERTURE_LOCAL_MEM 0
#define  ENUM_aperture_t_APERTURE_P2P 1
#define  ENUM_aperture_t_APERTURE_SYS_MEM_COHERENT 2
#define  ENUM_aperture_t_APERTURE_SYS_MEM_NONCOHERENT 3
// comp_stat_t enum values
#define comp_stat_t_ENUM_DECL enum comp_stat_t {COMP_STAT_UNCOMPRESSED = 0, COMP_STAT_COMPRESSED_4_TO_1 = 1, COMP_STAT_COMPRESSED_8_TO_1 = 2};
#define  ENUM_comp_stat_t_COMP_STAT_UNCOMPRESSED 0
#define  ENUM_comp_stat_t_COMP_STAT_COMPRESSED_4_TO_1 1
#define  ENUM_comp_stat_t_COMP_STAT_COMPRESSED_8_TO_1 2
// cwr_t enum values
#define cwr_t_ENUM_DECL enum cwr_t {CWR_NORMAL = 0, CWR_ATOM_NEW = 1, CWR_ATOM_OLD_FIRST = 2, CWR_ATOM_OLD = 3, CWR_ATOM_OLD_LAST = 4, CWR_ATOM_OLD_FIRST_AND_LAST = 5, CWR_MEMBAR = 6};
#define  ENUM_cwr_t_CWR_NORMAL 0
#define  ENUM_cwr_t_CWR_ATOM_NEW 1
#define  ENUM_cwr_t_CWR_ATOM_OLD_FIRST 2
#define  ENUM_cwr_t_CWR_ATOM_OLD 3
#define  ENUM_cwr_t_CWR_ATOM_OLD_LAST 4
#define  ENUM_cwr_t_CWR_ATOM_OLD_FIRST_AND_LAST 5
#define  ENUM_cwr_t_CWR_MEMBAR 6
// fb_diso_pix_fmt_t enum values
#define fb_diso_pix_fmt_t_ENUM_DECL enum fb_diso_pix_fmt_t {FB_DISO_PIX_FMT_FP16_GAIN_OFF = 0, FB_DISO_PIX_FMT_FP16_MANT_EXP = 1, FB_DISO_PIX_FMT_V8 = 2, FB_DISO_PIX_FMT_V16 = 3, FB_DISO_PIX_FMT_V16_E32 = 4, FB_DISO_PIX_FMT_V32 = 5, FB_DISO_PIX_FMT_V32_A8 = 6, FB_DISO_PIX_FMT_RES = 7};
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_FP16_GAIN_OFF 0
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_FP16_MANT_EXP 1
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_V8 2
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_V16 3
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_V16_E32 4
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_V32 5
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_V32_A8 6
#define  ENUM_fb_diso_pix_fmt_t_FB_DISO_PIX_FMT_RES 7
// fb_subkind_t enum values
#define fb_subkind_t_ENUM_DECL enum fb_subkind_t {FB_SUBKIND_GENERIC = 0, FB_SUBKIND_Z = 1, FB_SUBKIND_STENCIL = 2, FB_SUBKIND_VC = 3};
#define  ENUM_fb_subkind_t_FB_SUBKIND_GENERIC 0
#define  ENUM_fb_subkind_t_FB_SUBKIND_Z 1
#define  ENUM_fb_subkind_t_FB_SUBKIND_STENCIL 2
#define  ENUM_fb_subkind_t_FB_SUBKIND_VC 3
// fb_vc_t enum values
#define fb_vc_t_ENUM_DECL enum fb_vc_t {FB_VC_ISO = 0, FB_VC_EVERYTHING_ELSE = 1};
#define  ENUM_fb_vc_t_FB_VC_ISO 0
#define  ENUM_fb_vc_t_FB_VC_EVERYTHING_ELSE 1
// fbp2xx_cmd_vc_t enum values
#define fbp2xx_cmd_vc_t_ENUM_DECL enum fbp2xx_cmd_vc_t {VC_NON_BLOCKING = 0, VC_NISO_NB = 1, VC_NISO_B = 2};
#define  ENUM_fbp2xx_cmd_vc_t_VC_NON_BLOCKING 0
#define  ENUM_fbp2xx_cmd_vc_t_VC_NISO_NB 1
#define  ENUM_fbp2xx_cmd_vc_t_VC_NISO_B 2
// fbp2xx_data_vc_t enum values
#define fbp2xx_data_vc_t_ENUM_DECL enum fbp2xx_data_vc_t {VC_NON_BLOCKING = 0, VC_NISO_NB = 1, VC_NISO_B = 2, VC_ISO = 3};
#define  ENUM_fbp2xx_data_vc_t_VC_NON_BLOCKING 0
#define  ENUM_fbp2xx_data_vc_t_VC_NISO_NB 1
#define  ENUM_fbp2xx_data_vc_t_VC_NISO_B 2
#define  ENUM_fbp2xx_data_vc_t_VC_ISO 3
// fbp_unit_id_t enum values
#define fbp_unit_id_t_ENUM_DECL enum fbp_unit_id_t {UNIT_CROP = 0, UNIT_ZROP = 1, UNIT_L2 = 2, UNIT_FB = 3};
#define  ENUM_fbp_unit_id_t_UNIT_CROP 0
#define  ENUM_fbp_unit_id_t_UNIT_ZROP 1
#define  ENUM_fbp_unit_id_t_UNIT_L2 2
#define  ENUM_fbp_unit_id_t_UNIT_FB 3
// fos_t enum values
#define fos_t_ENUM_DECL enum fos_t {FB_DISO_AA_NONE_int = 0, FB_DISO_AA_4X_int = 1, FB_DISO_AA_8X_int = 2, FB_DISO_AA_GAMMA_4X_int = 3, FB_DISO_AA_GAMMA_8X_int = 4, FB_DISO_AA_RES_int = 7};
#define  ENUM_fos_t_FB_DISO_AA_NONE_int 0
#define  ENUM_fos_t_FB_DISO_AA_4X_int 1
#define  ENUM_fos_t_FB_DISO_AA_8X_int 2
#define  ENUM_fos_t_FB_DISO_AA_GAMMA_4X_int 3
#define  ENUM_fos_t_FB_DISO_AA_GAMMA_8X_int 4
#define  ENUM_fos_t_FB_DISO_AA_RES_int 7
// gop_t enum values
#define gop_t_ENUM_DECL enum gop_t {ATOMIC_IMIN = 0, ATOMIC_IMAX = 1, ATOMIC_IAND = 3, ATOMIC_IOR = 4, ATOMIC_IXOR = 2, ATOMIC_IADD = 5, ATOMIC_INC = 6, ATOMIC_DEC = 7, ATOMIC_CAS = 8, ATOMIC_EXCH = 9, ATOMIC_FADD = 10, ATOMIC_FMIN = 11, ATOMIC_FMAX = 12, ATOMIC_FMUL = 13, ATOMIC_IMUL = 14, ATOMIC_NOP_GLD_GST = 15};
#define  ENUM_gop_t_ATOMIC_IMIN 0
#define  ENUM_gop_t_ATOMIC_IMAX 1
#define  ENUM_gop_t_ATOMIC_IAND 3
#define  ENUM_gop_t_ATOMIC_IOR 4
#define  ENUM_gop_t_ATOMIC_IXOR 2
#define  ENUM_gop_t_ATOMIC_IADD 5
#define  ENUM_gop_t_ATOMIC_INC 6
#define  ENUM_gop_t_ATOMIC_DEC 7
#define  ENUM_gop_t_ATOMIC_CAS 8
#define  ENUM_gop_t_ATOMIC_EXCH 9
#define  ENUM_gop_t_ATOMIC_FADD 10
#define  ENUM_gop_t_ATOMIC_FMIN 11
#define  ENUM_gop_t_ATOMIC_FMAX 12
#define  ENUM_gop_t_ATOMIC_FMUL 13
#define  ENUM_gop_t_ATOMIC_IMUL 14
#define  ENUM_gop_t_ATOMIC_NOP_GLD_GST 15
// gpc2xx_cmd_vc_t enum values
#define gpc2xx_cmd_vc_t_ENUM_DECL enum gpc2xx_cmd_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1};
#define  ENUM_gpc2xx_cmd_vc_t_VC_NON_BLOCKING 0
#define  ENUM_gpc2xx_cmd_vc_t_VC_BLOCKING 1
// gpc2xx_data_vc_t enum values
#define gpc2xx_data_vc_t_ENUM_DECL enum gpc2xx_data_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1};
#define  ENUM_gpc2xx_data_vc_t_VC_NON_BLOCKING 0
#define  ENUM_gpc2xx_data_vc_t_VC_BLOCKING 1
// gpc2xx_vc_t enum values
#define gpc2xx_vc_t_ENUM_DECL enum gpc2xx_vc_t {GPC_VC_NON_BLOCKING = 0, GPC_VC_BLOCKING = 1};
#define  ENUM_gpc2xx_vc_t_GPC_VC_NON_BLOCKING 0
#define  ENUM_gpc2xx_vc_t_GPC_VC_BLOCKING 1
// gpc_cmd_dst_unit_id_t enum values
#define gpc_cmd_dst_unit_id_t_ENUM_DECL enum gpc_cmd_dst_unit_id_t {GPC_CMD_DST_UNIT_PROP = 0, GPC_CMD_DST_UNIT_LTP_UTLB_0 = 1, GPC_CMD_DST_UNIT_LTP_UTLB_1 = 2, GPC_CMD_DST_UNIT_LTP_UTLB_2 = 3, GPC_CMD_DST_UNIT_LTP_UTLB_3 = 4, GPC_CMD_DST_UNIT_RGG_UTLB = 5};
#define  ENUM_gpc_cmd_dst_unit_id_t_GPC_CMD_DST_UNIT_PROP 0
#define  ENUM_gpc_cmd_dst_unit_id_t_GPC_CMD_DST_UNIT_LTP_UTLB_0 1
#define  ENUM_gpc_cmd_dst_unit_id_t_GPC_CMD_DST_UNIT_LTP_UTLB_1 2
#define  ENUM_gpc_cmd_dst_unit_id_t_GPC_CMD_DST_UNIT_LTP_UTLB_2 3
#define  ENUM_gpc_cmd_dst_unit_id_t_GPC_CMD_DST_UNIT_LTP_UTLB_3 4
#define  ENUM_gpc_cmd_dst_unit_id_t_GPC_CMD_DST_UNIT_RGG_UTLB 5
// gpc_data_dst_unit_id_t enum values
#define gpc_data_dst_unit_id_t_ENUM_DECL enum gpc_data_dst_unit_id_t {GPC_DATA_DST_UNIT_L1_0 = 0, GPC_DATA_DST_UNIT_T1_0 = 1, GPC_DATA_DST_UNIT_PE_0 = 2, GPC_DATA_DST_UNIT_L1_1 = 3, GPC_DATA_DST_UNIT_T1_1 = 4, GPC_DATA_DST_UNIT_PE_1 = 5, GPC_DATA_DST_UNIT_L1_2 = 6, GPC_DATA_DST_UNIT_T1_2 = 7, GPC_DATA_DST_UNIT_PE_2 = 8, GPC_DATA_DST_UNIT_L1_3 = 9, GPC_DATA_DST_UNIT_T1_3 = 10, GPC_DATA_DST_UNIT_PE_3 = 11, GPC_DATA_DST_UNIT_RAST = 12, GPC_DATA_DST_UNIT_GCC = 13, GPC_DATA_DST_UNIT_GPCCS = 14, GPC_DATA_DST_UNIT_GPM = 15};
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_L1_0 0
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_T1_0 1
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_PE_0 2
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_L1_1 3
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_T1_1 4
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_PE_1 5
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_L1_2 6
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_T1_2 7
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_PE_2 8
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_L1_3 9
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_T1_3 10
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_PE_3 11
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_RAST 12
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_GCC 13
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_GPCCS 14
#define  ENUM_gpc_data_dst_unit_id_t_GPC_DATA_DST_UNIT_GPM 15
// gpc_unit_id_t enum values
#define gpc_unit_id_t_ENUM_DECL enum gpc_unit_id_t {UNIT_L1_0 = 0, UNIT_T1_0 = 1, UNIT_PE_0 = 2, UNIT_L1_1 = 3, UNIT_T1_1 = 4, UNIT_PE_1 = 5, UNIT_L1_2 = 6, UNIT_T1_2 = 7, UNIT_PE_2 = 8, UNIT_L1_3 = 9, UNIT_T1_3 = 10, UNIT_PE_3 = 11, UNIT_RAST = 12, UNIT_GCC = 13, UNIT_GPCCS = 14, UNIT_PROP_0 = 15, UNIT_PROP_1 = 16, UNIT_PROP_2 = 17, UNIT_PROP_3 = 18, UNIT_GPM = 19, UNIT_LTP_UTLB_0 = 20, UNIT_LTP_UTLB_1 = 21, UNIT_LTP_UTLB_2 = 22, UNIT_LTP_UTLB_3 = 23, UNIT_RGG_UTLB = 24};
#define  ENUM_gpc_unit_id_t_UNIT_L1_0 0
#define  ENUM_gpc_unit_id_t_UNIT_T1_0 1
#define  ENUM_gpc_unit_id_t_UNIT_PE_0 2
#define  ENUM_gpc_unit_id_t_UNIT_L1_1 3
#define  ENUM_gpc_unit_id_t_UNIT_T1_1 4
#define  ENUM_gpc_unit_id_t_UNIT_PE_1 5
#define  ENUM_gpc_unit_id_t_UNIT_L1_2 6
#define  ENUM_gpc_unit_id_t_UNIT_T1_2 7
#define  ENUM_gpc_unit_id_t_UNIT_PE_2 8
#define  ENUM_gpc_unit_id_t_UNIT_L1_3 9
#define  ENUM_gpc_unit_id_t_UNIT_T1_3 10
#define  ENUM_gpc_unit_id_t_UNIT_PE_3 11
#define  ENUM_gpc_unit_id_t_UNIT_RAST 12
#define  ENUM_gpc_unit_id_t_UNIT_GCC 13
#define  ENUM_gpc_unit_id_t_UNIT_GPCCS 14
#define  ENUM_gpc_unit_id_t_UNIT_PROP_0 15
#define  ENUM_gpc_unit_id_t_UNIT_PROP_1 16
#define  ENUM_gpc_unit_id_t_UNIT_PROP_2 17
#define  ENUM_gpc_unit_id_t_UNIT_PROP_3 18
#define  ENUM_gpc_unit_id_t_UNIT_GPM 19
#define  ENUM_gpc_unit_id_t_UNIT_LTP_UTLB_0 20
#define  ENUM_gpc_unit_id_t_UNIT_LTP_UTLB_1 21
#define  ENUM_gpc_unit_id_t_UNIT_LTP_UTLB_2 22
#define  ENUM_gpc_unit_id_t_UNIT_LTP_UTLB_3 23
#define  ENUM_gpc_unit_id_t_UNIT_RGG_UTLB 24
// hub2xx_cmd_vc_t enum values
#define hub2xx_cmd_vc_t_ENUM_DECL enum hub2xx_cmd_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1, VC_NISO_NB = 2, VC_NISO_B = 3, VC_ISO = 4};
#define  ENUM_hub2xx_cmd_vc_t_VC_NON_BLOCKING 0
#define  ENUM_hub2xx_cmd_vc_t_VC_BLOCKING 1
#define  ENUM_hub2xx_cmd_vc_t_VC_NISO_NB 2
#define  ENUM_hub2xx_cmd_vc_t_VC_NISO_B 3
#define  ENUM_hub2xx_cmd_vc_t_VC_ISO 4
// hub2xx_data_vc_t enum values
#define hub2xx_data_vc_t_ENUM_DECL enum hub2xx_data_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1, VC_NISO_NB = 2, VC_NISO_B = 3};
#define  ENUM_hub2xx_data_vc_t_VC_NON_BLOCKING 0
#define  ENUM_hub2xx_data_vc_t_VC_BLOCKING 1
#define  ENUM_hub2xx_data_vc_t_VC_NISO_NB 2
#define  ENUM_hub2xx_data_vc_t_VC_NISO_B 3
// hub_unit_id_t enum values
#define hub_unit_id_t_ENUM_DECL enum hub_unit_id_t {UNIT_CE0 = 1, UNIT_CE1 = 2, UNIT_DNISO = 3, UNIT_FE = 4, UNIT_FECS = 5, UNIT_HOST = 6, UNIT_HOST_CPU = 7, UNIT_HOST_CPU_NB = 8, UNIT_ISO = 9, UNIT_MMU = 10, UNIT_MSPDEC = 11, UNIT_MSPPP = 12, UNIT_MSVLD = 13, UNIT_NISO = 14, UNIT_P2P = 15, UNIT_PD = 16, UNIT_PERF = 17, UNIT_PMU = 18, UNIT_RASTERTWOD = 19, UNIT_SCC = 20, UNIT_SCC_NB = 21, UNIT_SEC = 22, UNIT_SSYNC = 23, UNIT_VIP = 24, UNIT_XV = 25, UNIT_MMU_NB = 26};
#define  ENUM_hub_unit_id_t_UNIT_CE0 1
#define  ENUM_hub_unit_id_t_UNIT_CE1 2
#define  ENUM_hub_unit_id_t_UNIT_DNISO 3
#define  ENUM_hub_unit_id_t_UNIT_FE 4
#define  ENUM_hub_unit_id_t_UNIT_FECS 5
#define  ENUM_hub_unit_id_t_UNIT_HOST 6
#define  ENUM_hub_unit_id_t_UNIT_HOST_CPU 7
#define  ENUM_hub_unit_id_t_UNIT_HOST_CPU_NB 8
#define  ENUM_hub_unit_id_t_UNIT_ISO 9
#define  ENUM_hub_unit_id_t_UNIT_MMU 10
#define  ENUM_hub_unit_id_t_UNIT_MSPDEC 11
#define  ENUM_hub_unit_id_t_UNIT_MSPPP 12
#define  ENUM_hub_unit_id_t_UNIT_MSVLD 13
#define  ENUM_hub_unit_id_t_UNIT_NISO 14
#define  ENUM_hub_unit_id_t_UNIT_P2P 15
#define  ENUM_hub_unit_id_t_UNIT_PD 16
#define  ENUM_hub_unit_id_t_UNIT_PERF 17
#define  ENUM_hub_unit_id_t_UNIT_PMU 18
#define  ENUM_hub_unit_id_t_UNIT_RASTERTWOD 19
#define  ENUM_hub_unit_id_t_UNIT_SCC 20
#define  ENUM_hub_unit_id_t_UNIT_SCC_NB 21
#define  ENUM_hub_unit_id_t_UNIT_SEC 22
#define  ENUM_hub_unit_id_t_UNIT_SSYNC 23
#define  ENUM_hub_unit_id_t_UNIT_VIP 24
#define  ENUM_hub_unit_id_t_UNIT_XV 25
#define  ENUM_hub_unit_id_t_UNIT_MMU_NB 26
// ltc_class_t enum values
#define ltc_class_t_ENUM_DECL enum ltc_class_t {L2_EVICT_FIRST = 0, L2_EVICT_NORMAL = 1, L2_EVICT_LAST = 2};
#define  ENUM_ltc_class_t_L2_EVICT_FIRST 0
#define  ENUM_ltc_class_t_L2_EVICT_NORMAL 1
#define  ENUM_ltc_class_t_L2_EVICT_LAST 2
// ltc_cmgmt_t enum values
#define ltc_cmgmt_t_ENUM_DECL enum ltc_cmgmt_t {CMGMT_ILWALIDATE = 0, CMGMT_CLEAN_REQUEST = 1};
#define  ENUM_ltc_cmgmt_t_CMGMT_ILWALIDATE 0
#define  ENUM_ltc_cmgmt_t_CMGMT_CLEAN_REQUEST 1
// ltc_priority_t enum values
#define ltc_priority_t_ENUM_DECL enum ltc_priority_t {L2_PRIORITY_REQ_NORMAL = 0, L2_PRIORITY_REQ_URGENT = 1};
#define  ENUM_ltc_priority_t_L2_PRIORITY_REQ_NORMAL 0
#define  ENUM_ltc_priority_t_L2_PRIORITY_REQ_URGENT 1
// mmu_big_page_size_t enum values
#define mmu_big_page_size_t_ENUM_DECL enum mmu_big_page_size_t {BIG_PAGE_SIZE_64K = 0, BIG_PAGE_SIZE_128K = 1};
#define  ENUM_mmu_big_page_size_t_BIG_PAGE_SIZE_64K 0
#define  ENUM_mmu_big_page_size_t_BIG_PAGE_SIZE_128K 1
// mmu_page_size_t enum values
#define mmu_page_size_t_ENUM_DECL enum mmu_page_size_t {PAGE_SIZE_BIG = 0, PAGE_SIZE_SMALL = 1};
#define  ENUM_mmu_page_size_t_PAGE_SIZE_BIG 0
#define  ENUM_mmu_page_size_t_PAGE_SIZE_SMALL 1
// node_id_t enum values
#define node_id_t_ENUM_DECL enum node_id_t {NODE_GPC_0 = 0, NODE_FBP_0 = 1, NODE_GPC_1 = 2, NODE_FBP_1 = 3, NODE_GPC_2 = 4, NODE_FBP_2 = 5, NODE_GPC_3 = 6, NODE_FBP_3 = 7, NODE_GPC_4 = 8, NODE_FBP_4 = 9, NODE_GPC_5 = 10, NODE_FBP_5 = 11, NODE_GPC_6 = 12, NODE_FBP_6 = 13, NODE_GPC_7 = 14, NODE_FBP_7 = 15, NODE_HUB = 16};
#define  ENUM_node_id_t_NODE_GPC_0 0
#define  ENUM_node_id_t_NODE_FBP_0 1
#define  ENUM_node_id_t_NODE_GPC_1 2
#define  ENUM_node_id_t_NODE_FBP_1 3
#define  ENUM_node_id_t_NODE_GPC_2 4
#define  ENUM_node_id_t_NODE_FBP_2 5
#define  ENUM_node_id_t_NODE_GPC_3 6
#define  ENUM_node_id_t_NODE_FBP_3 7
#define  ENUM_node_id_t_NODE_GPC_4 8
#define  ENUM_node_id_t_NODE_FBP_4 9
#define  ENUM_node_id_t_NODE_GPC_5 10
#define  ENUM_node_id_t_NODE_FBP_5 11
#define  ENUM_node_id_t_NODE_GPC_6 12
#define  ENUM_node_id_t_NODE_FBP_6 13
#define  ENUM_node_id_t_NODE_GPC_7 14
#define  ENUM_node_id_t_NODE_FBP_7 15
#define  ENUM_node_id_t_NODE_HUB 16
// op_sign_t enum values
#define op_sign_t_ENUM_DECL enum op_sign_t {OP_SIGNED = 0, OP_UNSIGNED = 1};
#define  ENUM_op_sign_t_OP_SIGNED 0
#define  ENUM_op_sign_t_OP_UNSIGNED 1
// op_sz_t enum values
#define op_sz_t_ENUM_DECL enum op_sz_t {OP_SZ_8 = 0, OP_SZ_16 = 1, OP_SZ_32 = 2, OP_SZ_64 = 3, OP_SZ_128 = 4};
#define  ENUM_op_sz_t_OP_SZ_8 0
#define  ENUM_op_sz_t_OP_SZ_16 1
#define  ENUM_op_sz_t_OP_SZ_32 2
#define  ENUM_op_sz_t_OP_SZ_64 3
#define  ENUM_op_sz_t_OP_SZ_128 4
// port_id_t enum values
#define port_id_t_ENUM_DECL enum port_id_t {PORT0 = 0, PORT1 = 1, PORT2 = 2, PORT3 = 3};
#define  ENUM_port_id_t_PORT0 0
#define  ENUM_port_id_t_PORT1 1
#define  ENUM_port_id_t_PORT2 2
#define  ENUM_port_id_t_PORT3 3
// req_type_encode_t enum values
#define req_type_encode_t_ENUM_DECL enum req_type_encode_t {WRITE_1_DATA = 1, WRITE_2_DATA = 2, WRITE_3_DATA = 3, WRITE_4_DATA = 4, READ_DATA = 5, READ_MESSAGE = 6, MESSAGE = 7, EMPTY = 0};
#define  ENUM_req_type_encode_t_WRITE_1_DATA 1
#define  ENUM_req_type_encode_t_WRITE_2_DATA 2
#define  ENUM_req_type_encode_t_WRITE_3_DATA 3
#define  ENUM_req_type_encode_t_WRITE_4_DATA 4
#define  ENUM_req_type_encode_t_READ_DATA 5
#define  ENUM_req_type_encode_t_READ_MESSAGE 6
#define  ENUM_req_type_encode_t_MESSAGE 7
#define  ENUM_req_type_encode_t_EMPTY 0
// vc_t enum values
#define vc_t_ENUM_DECL enum vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1, VC_NISO_NB = 2, VC_NISO_B = 3, VC_ISO = 4};
#define  ENUM_vc_t_VC_NON_BLOCKING 0
#define  ENUM_vc_t_VC_BLOCKING 1
#define  ENUM_vc_t_VC_NISO_NB 2
#define  ENUM_vc_t_VC_NISO_B 3
#define  ENUM_vc_t_VC_ISO 4
// vol_t enum values
#define vol_t_ENUM_DECL enum vol_t {VOL_NORMAL = 0, VOL_VOLATILE = 1};
#define  ENUM_vol_t_VOL_NORMAL 0
#define  ENUM_vol_t_VOL_VOLATILE 1
// xx2fbp_cmd_vc_t enum values
#define xx2fbp_cmd_vc_t_ENUM_DECL enum xx2fbp_cmd_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1, VC_NISO_NB = 2, VC_NISO_B = 3, VC_ISO = 4};
#define  ENUM_xx2fbp_cmd_vc_t_VC_NON_BLOCKING 0
#define  ENUM_xx2fbp_cmd_vc_t_VC_BLOCKING 1
#define  ENUM_xx2fbp_cmd_vc_t_VC_NISO_NB 2
#define  ENUM_xx2fbp_cmd_vc_t_VC_NISO_B 3
#define  ENUM_xx2fbp_cmd_vc_t_VC_ISO 4
// xx2fbp_data_vc_t enum values
#define xx2fbp_data_vc_t_ENUM_DECL enum xx2fbp_data_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1, VC_NISO_NB = 2, VC_NISO_B = 3};
#define  ENUM_xx2fbp_data_vc_t_VC_NON_BLOCKING 0
#define  ENUM_xx2fbp_data_vc_t_VC_BLOCKING 1
#define  ENUM_xx2fbp_data_vc_t_VC_NISO_NB 2
#define  ENUM_xx2fbp_data_vc_t_VC_NISO_B 3
// xx2hub_cmd_vc_t enum values
#define xx2hub_cmd_vc_t_ENUM_DECL enum xx2hub_cmd_vc_t {VC_NON_BLOCKING = 0, VC_BLOCKING = 1, VC_NISO_NB = 2, VC_NISO_B = 3};
#define  ENUM_xx2hub_cmd_vc_t_VC_NON_BLOCKING 0
#define  ENUM_xx2hub_cmd_vc_t_VC_BLOCKING 1
#define  ENUM_xx2hub_cmd_vc_t_VC_NISO_NB 2
#define  ENUM_xx2hub_cmd_vc_t_VC_NISO_B 3
// xx2hub_data_vc_t enum values
#define xx2hub_data_vc_t_ENUM_DECL enum xx2hub_data_vc_t {VC_NON_BLOCKING = 0, VC_NISO_NB = 1, VC_NISO_B = 2, VC_ISO = 3};
#define  ENUM_xx2hub_data_vc_t_VC_NON_BLOCKING 0
#define  ENUM_xx2hub_data_vc_t_VC_NISO_NB 1
#define  ENUM_xx2hub_data_vc_t_VC_NISO_B 2
#define  ENUM_xx2hub_data_vc_t_VC_ISO 3
#endif // !defined(_memory_enum_types_H_)
