/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 2014-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */
#include "host_test_util.h"

#include "class/cla0b5.h" // KEPLER_DMA_COPY_A
#include "class/clb0b5.h" // MAXWELL_DMA_COPY_A
#include "class/clc0b5.h" // PASCAL_DMA_COPY_A
#include "class/clc1b5.h" // PASCAL_DMA_COPY_B
#include "class/clc3b5.h" // VOLTA_DMA_COPY_A
#include "class/clc5b5.h" // TURING_DMA_COPY_A
#include "class/clc6b5.h" // AMPERE_DMA_COPY_A
#include "class/clc7b5.h" // AMPERE_DMA_COPY_B
#include "class/clc8b5.h" // HOPPER_DMA_COPY_A
#include "class/clc9b5.h" // BLACKWELL_DMA_COPY_A

#define HOST_TEST_FIELD(copyclass, field) \
        (copyclass == KEPLER_DMA_COPY_A)     ? LWA0B5##field : \
        (copyclass == MAXWELL_DMA_COPY_A)    ? LWB0B5##field : \
        (copyclass == PASCAL_DMA_COPY_A)     ? LWC0B5##field : \
        (copyclass == PASCAL_DMA_COPY_B)     ? LWC1B5##field : \
        (copyclass == VOLTA_DMA_COPY_A)      ? LWC3B5##field : \
        (copyclass == TURING_DMA_COPY_A)     ? LWC5B5##field : \
        (copyclass == AMPERE_DMA_COPY_A)     ? LWC6B5##field : \
        (copyclass == AMPERE_DMA_COPY_B)     ? LWC7B5##field : \
        (copyclass == HOPPER_DMA_COPY_A)     ? LWC8B5##field : \
        (copyclass == BLACKWELL_DMA_COPY_A)  ? LWC9B5##field : \
                                               LWC9B5##field
                                          

host_test_util::host_test_util(UINT32 copyclass):
    copyClassToUse(copyclass)
{}

UINT32 host_test_util::host_test_dma_method(uint payloadSize64b) {
    UINT32 method = 0;
    switch(copyClassToUse) {
        case KEPLER_DMA_COPY_A:
            method = DRF_NUM(A0B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWA0B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWA0B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWA0B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWA0B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWA0B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWA0B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWA0B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWA0B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _BYPASS_L2,              LWA0B5_LAUNCH_DMA_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _SRC_TYPE,               LWA0B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _DST_TYPE,               LWA0B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWA0B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(A0B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWA0B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case MAXWELL_DMA_COPY_A:
            method = DRF_NUM(B0B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWB0B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWB0B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWB0B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWB0B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWB0B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWB0B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWB0B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWB0B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _BYPASS_L2,              LWB0B5_LAUNCH_DMA_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _SRC_TYPE,               LWB0B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _DST_TYPE,               LWB0B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWB0B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(B0B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWB0B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case PASCAL_DMA_COPY_A:
            method = DRF_NUM(C0B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC0B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC0B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC0B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC0B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC0B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC0B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC0B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC0B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _SRC_BYPASS_L2,          LWC0B5_LAUNCH_DMA_SRC_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _DST_BYPASS_L2,          LWC0B5_LAUNCH_DMA_DST_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _SRC_TYPE,               LWC0B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _DST_TYPE,               LWC0B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC0B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C0B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC0B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case PASCAL_DMA_COPY_B:
            method = DRF_NUM(C1B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC1B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC1B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC1B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC1B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC1B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC1B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC1B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC1B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _SRC_BYPASS_L2,          LWC1B5_LAUNCH_DMA_SRC_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _DST_BYPASS_L2,          LWC1B5_LAUNCH_DMA_DST_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _SRC_TYPE,               LWC1B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _DST_TYPE,               LWC1B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC1B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C1B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC1B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case VOLTA_DMA_COPY_A:
            method = DRF_NUM(C3B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC3B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC3B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC3B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC3B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC3B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC3B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC3B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC3B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _SRC_BYPASS_L2,          LWC3B5_LAUNCH_DMA_SRC_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _DST_BYPASS_L2,          LWC3B5_LAUNCH_DMA_DST_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _SRC_TYPE,               LWC3B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _DST_TYPE,               LWC3B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC3B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C3B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC3B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case TURING_DMA_COPY_A:
            method = DRF_NUM(C5B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC5B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC5B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC5B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC5B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC5B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC5B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC5B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC5B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _SRC_BYPASS_L2,          LWC5B5_LAUNCH_DMA_SRC_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _DST_BYPASS_L2,          LWC5B5_LAUNCH_DMA_DST_BYPASS_L2_USE_PTE_SETTING) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _SRC_TYPE,               LWC5B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _DST_TYPE,               LWC5B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC5B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C5B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC5B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case AMPERE_DMA_COPY_A:
            method = DRF_NUM(C6B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC6B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC6B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC6B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC6B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC6B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC6B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC6B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC6B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _SRC_TYPE,               LWC6B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _DST_TYPE,               LWC6B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC6B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C6B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC6B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;
        case AMPERE_DMA_COPY_B:
            method = DRF_NUM(C7B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC7B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC7B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC7B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC7B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC7B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC7B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC7B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC7B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _SRC_TYPE,               LWC7B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _DST_TYPE,               LWC7B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC7B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC7B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED) |
                     DRF_NUM(C7B5, _LAUNCH_DMA, _SEMAPHORE_PAYLOAD_SIZE, payloadSize64b);
        break; 
        case HOPPER_DMA_COPY_A:
        case BLACKWELL_DMA_COPY_A:
            method = DRF_NUM(C8B5, _LAUNCH_DMA, _DATA_TRANSFER_TYPE,     LWC8B5_LAUNCH_DMA_DATA_TRANSFER_TYPE_NON_PIPELINED) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _FLUSH_ENABLE,           LWC8B5_LAUNCH_DMA_FLUSH_ENABLE_TRUE) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _SEMAPHORE_TYPE,         LWC8B5_LAUNCH_DMA_SEMAPHORE_TYPE_RELEASE_ONE_WORD_SEMAPHORE) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _INTERRUPT_TYPE,         LWC8B5_LAUNCH_DMA_INTERRUPT_TYPE_NONE) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _SRC_MEMORY_LAYOUT,      LWC8B5_LAUNCH_DMA_SRC_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _DST_MEMORY_LAYOUT,      LWC8B5_LAUNCH_DMA_DST_MEMORY_LAYOUT_PITCH) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _MULTI_LINE_ENABLE,      LWC8B5_LAUNCH_DMA_MULTI_LINE_ENABLE_TRUE) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _REMAP_ENABLE,           LWC8B5_LAUNCH_DMA_REMAP_ENABLE_FALSE) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _SRC_TYPE,               LWC8B5_LAUNCH_DMA_SRC_TYPE_VIRTUAL) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _DST_TYPE,               LWC8B5_LAUNCH_DMA_DST_TYPE_VIRTUAL) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_ENABLE,    LWC8B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_ENABLE_FALSE) |
                     DRF_NUM(C8B5, _LAUNCH_DMA, _SEMAPHORE_REDUCTION_SIGN,   LWC8B5_LAUNCH_DMA_SEMAPHORE_REDUCTION_SIGN_SIGNED);
        break;

        default:
            ErrPrintf("Unsupported copyClass, returning 0 for method\n");
        break;
    }

    return method;
}

UINT32 host_test_util::host_test_field(host_test_field_t field) {
    switch(field) {
        case CE_METHOD_OFFSET_IN_UPPER:
            return HOST_TEST_FIELD(copyClassToUse, _OFFSET_IN_UPPER);
        break;
        case CE_METHOD_OFFSET_OUT_UPPER:
            return HOST_TEST_FIELD(copyClassToUse, _OFFSET_OUT_UPPER);
        break;
        case CE_METHOD_PITCH_IN:
            return HOST_TEST_FIELD(copyClassToUse, _PITCH_IN);
        break;
        case CE_METHOD_PITCH_OUT:
            return HOST_TEST_FIELD(copyClassToUse, _PITCH_OUT);
        break;
        case CE_METHOD_LINE_LENGTH_IN:
            return HOST_TEST_FIELD(copyClassToUse, _LINE_LENGTH_IN);
        break;
        case CE_METHOD_LINE_COUNT:
            return HOST_TEST_FIELD(copyClassToUse, _LINE_COUNT);
        break;
        case CE_METHOD_SET_SEMAPHORE_A:
            return HOST_TEST_FIELD(copyClassToUse, _SET_SEMAPHORE_A);
        break;
        case CE_METHOD_LAUNCH_DMA:
            return HOST_TEST_FIELD(copyClassToUse, _LAUNCH_DMA);
        break;
        default:
            ErrPrintf("Unsupported field, returning 0 for method\n");
            return 0;
        break;
    }
}
