@startuml
title Setting Change Sequencer Info
RPC -> PERF : RPC
activate PERF
    PERF -> PERF : processRpc()
    activate PERF
        PERF -> ChangeSeq : setInfo()
        activate ChangeSeq
            ChangeSeq -> ChangeSeq : setTypeInfo()
            activate ChangeSeq
                return status
            return status
        return status
    return status
@enduml
