/*
 * LWIDIA_COPYRIGHT_BEGIN
 *
 * Copyright 1999-2021 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * LWIDIA_COPYRIGHT_END
 */

//------------------------------------------------------------------------------
//-----------------------------------------------------------------------------

/******************************************************************************

CHRISTIAN GREEN'S MINI-RANT ON ADDING ERROR CODES

There have been some checkins to this file that are guaranteed to cause
confusion at some point in the future.  The goals of adding error codes
are as follows:

1.  Try to use existing error codes when possible, and

2.  Check in error codes in such a way that the same error in different
    branches will have the same error number.

Here's what NOT to do:

A.  DON'T create a new error code that is very similar to another error code.
    Don't create the error "AZALIA_COULD_NOT_SET_STATE_ON_FUNCTION_ENTRY"
    when the error "COULD_NOT_SET_STATE" already exists.

B.  DON'T make a separate spot in this file for error codes of a specific
    type.  DON'T put in a comment that says "// Only Azalia code below this
    line" and then add a bunch of errors there.  That will not make it
    possible to do #2 above.

C.  DON'T mis-integrate your code and put it in the wrong section of this
    file.  A file that was originally integrated from lwr65 should be below
    the "// LWR65-and-up-only errors below this line." message and above
    the "// LWR70-and-up-only errors below this line."  This ensures directive
    #2.  Only errors added in main should go at the end of the file.

D.  DON'T mis-order existing error codes between different trees.

If you don't get this, please come and talk to me and I will explain it.

******************************************************************************/

/*
 * errors.h should only be included by rc.h/cpp and errormap.h/cpp
 * Other code that wishes to access errors should include rc.h and/or
 * errormap.h.
 */
#ifndef DEFINE_RETURN_CODES
    #error errors.h should only be included by selected files.  You probably want to include rc.h or errormap.h instead.
#endif
#undef DEFINE_RETURN_CODES

#undef DEFINE_UNUSED_RC
#define DEFINE_UNUSED_RC( errno )                              \
   DEFINE_RC(errno, UNUSED_ERROR_##errno, "Unused error code "#errno)

DEFINE_RC(0, OK, "ok")
DEFINE_RC(1, EXIT_OK, "exit")
DEFINE_RC(2, SOFTWARE_ERROR, "software error ")
DEFINE_RC(3, UNSUPPORTED_FUNCTION, "function is not supported")
DEFINE_RC(4, DID_NOT_INSTALL_SINGLETON, "did not install singleton")
DEFINE_RC(5, BAD_COMMAND_LINE_ARGUMENT, "bad command line argument")
DEFINE_RC(6, ON_ENTRY_FAILED, "on entry failed")
DEFINE_RC(7, BAD_HELP_STRING, "bad help string")
DEFINE_RC(8, BAD_PARAMETER, "bad parameter passed to function")
DEFINE_RC(9, CANNOT_ALLOCATE_MEMORY, "cannot allocate memory")
DEFINE_RC(10, CANNOT_OPEN_FILE, "cannot open file")
DEFINE_RC(11, FILE_DOES_NOT_EXIST, "file does not exist")
DEFINE_RC(12, FILE_READ_ERROR, "failed while reading a file")
DEFINE_RC(13, CANNOT_LOG_METHOD, "cannot log method")
DEFINE_RC(14, BANDWIDTH_OUT_OF_RANGE, "bandwidth out of range")
DEFINE_RC(15, C2C_BUS_ERROR, "C2C bus error")
DEFINE_RC(16, USER_ABORTED_SCRIPT, "user aborted the script")
DEFINE_RC(17, COULD_NOT_CREATE_JAVASCRIPT_ENGINE, "could not create JavaScript engine")
DEFINE_RC(18, COULD_NOT_CREATE_JS_METHOD, "could not create a JavaScript method")
DEFINE_RC(19, COULD_NOT_CREATE_JS_OBJECT, "could not create a JavaScript object")
DEFINE_RC(20, COULD_NOT_INITIALIZE_JS_STANDARD_CLASSES, "could not initialize the JavaScript standard classes")
DEFINE_RC(21, SCRIPT_FAILED_TO_EXELWTE, "script failed to execute")
DEFINE_UNUSED_RC(22) // reserved for now, because it's still used in r384
DEFINE_RC(23, COULD_NOT_COMPILE_FILE, "could not compile file")
DEFINE_UNUSED_RC(24)
DEFINE_RC(25, CANNOT_COLWERT_JSVAL_TO_INTEGER, "cannot colwert jsval to an integer")
DEFINE_RC(26, CANNOT_COLWERT_BOOLEAN_TO_JSVAL, "cannot colwert boolean to a jsval")
DEFINE_RC(27, CANNOT_COLWERT_JSVAL_TO_BOOLEAN, "cannot colwert jsval to a boolean")
DEFINE_RC(28, CANNOT_COLWERT_JSVAL_TO_FLOAT, "cannot colwert jsval to a float")
DEFINE_RC(29, CANNOT_COLWERT_FLOAT_TO_JSVAL, "cannot colwert float to a jsval")
DEFINE_RC(30, CANNOT_COLWERT_JSVAL_TO_STRING, "cannot colwert jsval to a string")
DEFINE_RC(31, CANNOT_COLWERT_STRING_TO_JSVAL, "cannot colwert string to a jsval")
DEFINE_RC(32, CANNOT_COLWERT_JSVAL_TO_ARRAY, "cannot colwert jsval to an array")
DEFINE_RC(33, CANNOT_COLWERT_ARRAY_TO_JSVAL, "cannot colwert array to a jsval")
DEFINE_RC(34, CANNOT_COLWERT_JSVAL_TO_OJBECT, "cannot colwert jsval to an object")
DEFINE_RC(35, CANNOT_COLWERT_JSVAL_TO_FUNCTION, "cannot colwert jsval to a function")
DEFINE_RC(36, ILWALID_OBJECT_PROPERTY, "invalid object property")
DEFINE_RC(37, CANNOT_ENUMERATE_OBJECT, "cannot enumerate object")
DEFINE_RC(38, CANNOT_GET_ELEMENT, "cannot get element")
DEFINE_RC(39, CANNOT_SET_ELEMENT, "cannot set element")
DEFINE_RC(40, BAD_FORMAT_SPECIFICAION, "bad format specification")
DEFINE_RC(41, CANNOT_HOOK_INTERRUPT, "cannot hook interrupt")
DEFINE_RC(42, DID_NOT_INITIALIZE_RM, "did not initialize resource manager")
DEFINE_UNUSED_RC(43)
DEFINE_UNUSED_RC(44)
DEFINE_UNUSED_RC(45)
DEFINE_RC(46, LWRM_ILWALID_BASE, "LWRM invalid base")
DEFINE_RC(47, LWRM_ILWALID_CLASS, "LWRM invalid class")
DEFINE_RC(48, LWRM_ILWALID_CLIENT, "LWRM invalid client")
DEFINE_RC(49, LWRM_ILWALID_DEVICE, "LWRM invalid device")
DEFINE_RC(50, LWRM_ILWALID_EVENT, "LWRM invalid event")
DEFINE_RC(51, LWRM_ILWALID_FLAGS, "LWRM invalid flags")
DEFINE_RC(52, LWRM_ILWALID_INDEX, "LWRM invalid index")
DEFINE_RC(53, LWRM_ILWALID_LIMIT, "LWRM invalid limit")
DEFINE_RC(54, LWRM_ILWALID_OBJECT_BUFFER, "LWRM invalid object buffer")
DEFINE_RC(55, LWRM_ILWALID_OBJECT_ERROR, "LWRM invalid object error")
DEFINE_RC(56, LWRM_ILWALID_OBJECT_NEW, "LWRM invalid object new")
DEFINE_RC(57, LWRM_ILWALID_OBJECT_OLD, "LWRM invalid object old")
DEFINE_RC(58, LWRM_ILWALID_OBJECT_PARENT, "LWRM invalid object parent")
DEFINE_RC(59, LWRM_ILWALID_OFFSET, "LWRM invalid offset")
DEFINE_RC(60, LWRM_ILWALID_PARAM_STRUCT, "LWRM invalid param struct")
DEFINE_RC(61, LWRM_INSUFFICIENT_RESOURCES, "LWRM insufficient resources")
DEFINE_RC(62, LWRM_ILWALID_FUNCTION, "LWRM invalid function")
DEFINE_RC(63, LWRM_ILWALID_OWNER, "LWRM invalid owner")
DEFINE_RC(64, LWRM_ILWALID_HEAP, "LWRM invalid heap")
DEFINE_RC(65, LWRM_MULTIPLE_MEMORY_TYPES, "LWRM multiple memory types")
DEFINE_UNUSED_RC(66)
DEFINE_UNUSED_RC(67)
DEFINE_RC(68, LWRM_OPERATING_SYSTEM, "LWRM operating system error")
DEFINE_RC(69, LWRM_PROTECTION_FAULT, "LWRM protection fault")
DEFINE_RC(70, LWRM_DUAL_LINK_INUSE, "LWRM dual link in use")
DEFINE_RC(71, LWRM_GPU_NOT_FULL_POWER, "LWRM gpu not full power")
DEFINE_RC(72, LWRM_ILWALID_DMA_SPECIFIER, "LWRM invalid dma specifier")
DEFINE_UNUSED_RC(73)
DEFINE_RC(74, LWRM_ERROR, "LWRM generic error")
DEFINE_RC(75, LWRM_IRQ_NOT_FIRING, "LWRM irq not firing")
DEFINE_RC(76, PREPROCESS_ERROR, "error oclwrred while preprocessing file")
DEFINE_RC(77, TIMEOUT_ERROR, "timeout error")
DEFINE_RC(78, UNSUPPORTED_DEPTH, "unsupported depth")
DEFINE_UNUSED_RC(79)
DEFINE_RC(80, UNSUPPORTED_COLORFORMAT, "unsupported color format")
DEFINE_UNUSED_RC(81)
DEFINE_RC(82, GOLDEN_VALUE_NOT_FOUND, "stored CRC/Checksum not found")
DEFINE_RC(83, GOLDEN_VALUE_MISCOMPARE, "CRC/Checksum miscompare")
DEFINE_RC(84, CANNOT_PARSE_FILE, "file parse error")
DEFINE_RC(85, BAD_PICK_ITEMS, "syntax error in FancyPicker configuration")
DEFINE_RC(86, ILWALID_FILE_FORMAT, "incorrect file format")
DEFINE_RC(87, FILE_WRITE_ERROR, "failed while writing a file")
DEFINE_RC(88, FAILED_TO_COPY_MEMORY, "failed to copy memory")
DEFINE_RC(89, BAD_TRACE_DATA, "bad data in trace file or unsupported trace file feature")
DEFINE_RC(90, BAD_3D_CLASS, "unsupported 3D primitive class")
DEFINE_UNUSED_RC(91)
DEFINE_RC(92, CANNOT_DISABLE_USER_INTERFACE, "cannot disable user interface")
DEFINE_RC(93, CANNOT_ENABLE_USER_INTERFACE, "cannot enable user interface")
DEFINE_RC(94, BAD_MEMLOC, "memory location must be one of Memory::Fb, Memory::Coherent or Memory::NonCoherent")
DEFINE_RC(95, GOLDEN_VALUE_MISCOMPARE_Z, "golden value miscompare in Z buffer")
DEFINE_RC(96, TEST_CONFIGURATION_ILWALID_CHANNEL_TYPE, "test configuration has invalid channel type, try TestConfiguration.DmaChannel")
DEFINE_RC(97, UNEXPECTED_INTERRUPTS, "unexpected device interrupts")
DEFINE_UNUSED_RC(98)
DEFINE_RC(99, MODS_GL_BAD_GLERROR, "unknown GL error")
DEFINE_RC(100, MODS_GL_ILWALID_ENUM, "OpenGL error ILWALID_ENUM")
DEFINE_RC(101, MODS_GL_ILWALID_VALUE, "OpenGL error ILWALID_VALUE")
DEFINE_RC(102, MODS_GL_ILWALID_OPERATION, "OpenGL error ILWALID_OPERATION")
DEFINE_RC(103, MODS_GL_STACK_OVERFLOW, "OpenGL error STACK_OVERFLOW")
DEFINE_RC(104, MODS_GL_STACK_UNDERFLOW, "OpenGL error STACK_UNDERFLOW")
DEFINE_RC(105, MODS_GL_OUT_OF_MEMORY, "OpenGL error OUT_OF_MEMORY")
DEFINE_RC(106, MODS_GL_TABLE_TOO_LARGE, "OpenGL error TABLE_TOO_LARGE")
DEFINE_RC(107, MODS_GLU_ILWALID_ENUM, "OpenGL util error ILWALID_ENUM")
DEFINE_RC(108, MODS_GLU_ILWALID_VALUE, "OpenGL util error ILWALID_VALUE")
DEFINE_RC(109, MODS_GLU_OUT_OF_MEMORY, "OpenGL util error OUT_OF_MEMORY")
DEFINE_RC(110, MODS_GLU_ILWALID_OPERATION, "OpenGL util error ILWALID_OPERATION")
DEFINE_RC(111, MODS_GLU_NURBS_ERROR, "OpenGL util error NURBS_ERROR(n)")
DEFINE_RC(112, MODS_GLU_TESS_ERROR, "OpenGL util error TESS_ERROR(n)")
DEFINE_RC(113, MODS_GLU_TESS_MISSING_BEGIN_POLYGON, "OpenGL util error TESS_MISSING_BEGIN_POLYGON")
DEFINE_RC(114, MODS_GLU_TESS_MISSING_BEGIN_CONTOUR, "OpenGL util error TESS_MISSING_BEGIN_CONTOUR")
DEFINE_RC(115, MODS_GLU_TESS_MISSING_END_POLYGON, "OpenGL util error TESS_MISSING_END_POLYGON")
DEFINE_RC(116, MODS_GLU_TESS_MISSING_END_CONTOUR, "OpenGL util error TESS_MISSING_END_CONTOUR")
DEFINE_RC(117, MODS_GLU_TESS_COORD_TOO_LARGE, "OpenGL util error TESS_COORD_TOO_LARGE")
DEFINE_RC(118, MODS_GLU_TESS_NEED_COMBINE_CALLBACK, "OpenGL util error TESS_NEED_COMBINE_CALLBACK")
DEFINE_UNUSED_RC(119)
DEFINE_UNUSED_RC(120)
DEFINE_RC(121, FUSE_VALUE_OUT_OF_RANGE, "This GPU has an invalid configuration") // purposefully vague, we don't want lwstomers to know about fuses
DEFINE_RC(122, ILWALID_ENCRYPTION_KEY, "Invalid encryption key")
DEFINE_UNUSED_RC(123) // reserved for now, because it's still used in r384
DEFINE_RC(124, ILWALID_INFO_ROM, "Invalid InfoROM")
DEFINE_RC(125, NO_DISPLAY_DEVICE_CONNECTED, "No display device is connected")
DEFINE_RC(126, CRC_CAPTURE_FAILED, "CRC capture failed")
DEFINE_RC(127, VBIOS_CERT_ERROR, "Vbios Certificate Error")
DEFINE_RC(128, ILWALID_INPUT, "Invalid input")
DEFINE_RC(129, ILWALID_DRIVER_INPUT, "Invalid input (driver level)")
DEFINE_RC(130, ILWALID_TEST_INPUT, "Invalid input (test level)")
DEFINE_UNUSED_RC(131)
DEFINE_RC(132, UNEXPECTED_ROBUST_CHANNEL_ERR, "Robust channel Unexpected Error")
DEFINE_RC(133, HDCP_ERROR, "HDCP did not operate properly")
DEFINE_RC(134, EDC_ERROR, "EDC detected a memory-bus error")
DEFINE_RC(135, ENCRYPT_DECRYPT_FAILED, "Encryption and/or decryption of data failed")
DEFINE_RC(136, SYSPOWER_STATE_CHANGE_ERROR, "Request for Power state change failed.")
DEFINE_UNUSED_RC(137)
DEFINE_RC(138, REGISTER_READ_WRITE_FAILED, "A read/write to a register failed.")
DEFINE_RC(139, THERMAL_SENSOR_ERROR, "Acceptable temperature limits exceeded or the thermal sensor is broken or miscalibrated")
DEFINE_RC(140, LWLINK_BUS_ERROR, "LwLink bus error")
DEFINE_RC(141, ONLY_OBSOLETE_DEVICES_FOUND, "The only devices found in the system are obsolete")
DEFINE_RC(142, MODE_IS_NOT_POSSIBLE, "Display mode is not possible")
DEFINE_RC(143, PCIE_BUS_ERROR, "PCI Express bus error")
DEFINE_RC(144, LWDA_ERROR, "LWCA error")
DEFINE_RC(145, LWDA_INIT_FAILED, "lwInit failed")
DEFINE_RC(146, LWDA_DEVICE_GET_FAILED, "lwDeviceGet failed")
DEFINE_RC(147, LWDA_CONTEXT_CREATE_FAILED, "lwCtxCreate failed")
DEFINE_RC(148, LWDA_NO_BINARY, "Could not find a lwbin or fatbinary")
DEFINE_RC(149, SPECIFIC_TEST_NOT_RUN, "A specific test was requested to run, but was skipped.")
DEFINE_RC(150, NO_TESTS_RUN, "No tests were run.")
DEFINE_RC(151, PRIMARY_SURFACE_IN_USE, "Primary surface already in use")
DEFINE_UNUSED_RC(152)
DEFINE_RC(153, DISPLAY_IN_USE, "Display HW in use by another test")
DEFINE_RC(154, GPU_COMPUTE_MISCOMPARE, "compute test failed")
DEFINE_RC(155, EXCEEDED_EXPECTED_THRESHOLD, "Test exceeded the expected threshold")
DEFINE_RC(156, EXCEEDED_MEMORY_LEAK_THRESHOLD, "Test exceeded the maximum number of allowed memory leaks")
DEFINE_UNUSED_RC(157)
DEFINE_RC(158, CRC_VALUES_NOT_UNIQUE, "CRC values are not unique")
DEFINE_RC(159, LWRM_STATUS_ERROR_NOT_READY, "LWRM display is not ready.")
DEFINE_RC(160, RESOURCE_IN_USE, "Resource is reserved by another thread or test")
DEFINE_RC(161, LWRM_STATUS_ERROR_ILWALID_ADDRESS, "LWRM invalid address.")
DEFINE_UNUSED_RC(162)
DEFINE_UNUSED_RC(163)
DEFINE_UNUSED_RC(164)
DEFINE_RC(165, ECC_CORRECTABLE_ERROR, "ECC detected a correctable error")
DEFINE_RC(166, ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error")
DEFINE_RC(167, GFW_BOOT_FAILURE, "GFW boot reported a failure")
DEFINE_UNUSED_RC(168)
DEFINE_RC(169, REGISTRY_KEY_NOT_FOUND, "registry key not found")
DEFINE_RC(170, REGISTRY_ERROR, "registry error")
DEFINE_RC(171, INCORRECT_ROM_VERSION, "incorrect rom version")
DEFINE_RC(172, GOLDEN_BAD_PIXEL, "golden check found bad pixel, continuing")
DEFINE_UNUSED_RC(173)
DEFINE_RC(174, GOLDEN_ERROR_RATE, "golden value miscompare")
DEFINE_UNUSED_RC(175)
DEFINE_UNUSED_RC(176)
DEFINE_RC(177, ILWALID_IRQ, "invalid IRQ")
DEFINE_RC(178, ILWALID_LW_BASE_ADDRESS, "invalid LW base address")
DEFINE_RC(179, ILWALID_LW_SIZE, "invalid LW size")
DEFINE_UNUSED_RC(180)
DEFINE_UNUSED_RC(181)
DEFINE_RC(182, CANNOT_SET_STATE, "cannot set state")
DEFINE_UNUSED_RC(183)
DEFINE_UNUSED_RC(184)
DEFINE_RC(185, CANNOT_SET_PIXEL_CLOCK, "cannot set pixel clock")
DEFINE_RC(186, CANNOT_SET_MEMORY_CLOCK, "cannot set memory clock")
DEFINE_RC(187, CANNOT_SET_GRAPHICS_CLOCK, "cannot set graphics clock")
DEFINE_RC(188, BAD_DAC, "bad dac")
DEFINE_RC(189, ILWALID_CHANNEL, "invalid channel")
DEFINE_UNUSED_RC(190)
DEFINE_RC(191, BAD_FORMAT, "bad format")
DEFINE_UNUSED_RC(192)
DEFINE_RC(193, ILWALID_RAM_AMOUNT, "invalid ram amount")
DEFINE_RC(194, BAD_MEMORY, "bad memory")
DEFINE_RC(195, SRIOV_REQUEST_FAILED, "VF to PF request failed")
DEFINE_RC(196, SRIOV_VF_MODS_FAILURE, "VF mods reported failure")
DEFINE_RC(197, LWLINK_INIT_ERROR, "Lwlink Init Error")
DEFINE_RC(198, LWLINK_MINION_ERROR, "Lwlink Minion Error")
DEFINE_RC(199, LWLINK_CLOCK_ERROR, "Lwlink Clock Error")
DEFINE_RC(200, LWLINK_TRAINING_ERROR, "Lwlink Training Error")
DEFINE_RC(201, LWLINK_CONFIGURATION_ERROR, "Lwlink Configuration Error")
DEFINE_RC(202, ILWALID_TOPOLOGY, "Invalid LwLink Topology")
DEFINE_RC(203, OPTICAL_LANE_FAILURE, "Optical lane failure")
DEFINE_RC(204, LWLINK_IOBIST_ERROR, "LwLink IOBIST failure")
DEFINE_UNUSED_RC(205)
DEFINE_UNUSED_RC(206)
DEFINE_UNUSED_RC(207)
DEFINE_UNUSED_RC(208)
DEFINE_UNUSED_RC(209)
DEFINE_UNUSED_RC(210)
DEFINE_UNUSED_RC(211)
DEFINE_UNUSED_RC(212)
DEFINE_UNUSED_RC(213)
DEFINE_UNUSED_RC(214)
DEFINE_RC(215, BUFFER_ALLOCATION_ERROR, "could not allocate a buffer")
DEFINE_RC(216, DEVICE_NOT_FOUND, "Could not find the specified device")
DEFINE_RC(217, PCI_BIOS_NOT_PRESENT, "pci bios is not present")
DEFINE_RC(218, PCI_FUNCTION_NOT_SUPPORTED, "pci function is not supported")
DEFINE_RC(219, PCI_ILWALID_VENDOR_IDENTIFICATION, "pci invalid vendor identification")
DEFINE_RC(220, PCI_DEVICE_NOT_FOUND, "pci device not found")
DEFINE_RC(221, PCI_ILWALID_REGISTER_NUMBER, "pci invalid register number")
DEFINE_RC(222, CPUID_NOT_SUPPORTED, "cpuid instruction is not supported")
DEFINE_UNUSED_RC(223)
DEFINE_RC(224, CPU_NOT_SUPPORTED, "cpu is not supported")
DEFINE_RC(225, ILWALID_REGISTER_NUMBER, "invalid register number")
DEFINE_RC(226, ILWALID_ADDRESS, "invalid address")
DEFINE_RC(227, COULD_NOT_MAP_PHYSICAL_ADDRESS, "could not map physical address")
DEFINE_UNUSED_RC(228) // reserved for now, because it's still used in r384
DEFINE_RC(229, WAS_NOT_INITIALIZED, "hardware was not initialized")
DEFINE_UNUSED_RC(230)
DEFINE_UNUSED_RC(231)
DEFINE_RC(232, WRONG_BIOS, "wrong bios")
DEFINE_RC(233, BAD_LWIDIA_CHIP, "bad LWPU chip")
DEFINE_RC(234, SERIAL_COMMUNICATION_ERROR, "error oclwrred while reading or writing serial data")
DEFINE_UNUSED_RC(235)
DEFINE_RC(236, MEM_TO_MEM_RESULT_NOT_MATCH, "the expected value and the destination memory value do not match")
DEFINE_RC(237, SET_MODE_FAILED, "unable to set mode")
DEFINE_RC(238, MODE_NOT_FOUND, "specified video mode not found in mode timings table")
DEFINE_RC(239, ILWALID_DISPLAY_TYPE, "invalid display type")
DEFINE_RC(240, HW_ERROR, "Unexpected result from HW")
DEFINE_RC(241, ILWALID_HEAD, "invalid head")
DEFINE_UNUSED_RC(242)
DEFINE_UNUSED_RC(243)
DEFINE_RC(244, UNSUPPORTED_HARDWARE_FEATURE, "feature is not supported in the hardware")
DEFINE_UNUSED_RC(245)
DEFINE_UNUSED_RC(246)
DEFINE_RC(247, UNDEFINED_JS_METHOD, "Javascript method is not defined")
DEFINE_RC(248, SOR_CRC_MISCOMPARE, "Bad SOR - CRC miscompare")
DEFINE_UNUSED_RC(249)
DEFINE_UNUSED_RC(250)
DEFINE_UNUSED_RC(251)
DEFINE_RC(252, CANNOT_ENABLE_IO_MEM_SPACE, "CANNOT enable Io or Mem Space.")
DEFINE_RC(253, CANNOT_ENABLE_BUS_MASTER, "CANNOT enable Bus Master.")
DEFINE_RC(254, MEMORY_SIZE_ERROR, "MemSize detected an invalid framebuffer size.")
DEFINE_UNUSED_RC(255)
DEFINE_UNUSED_RC(256)
DEFINE_RC(257, STATUS_INCOMPLETE, "Experiment not completed yet")
DEFINE_UNUSED_RC(258)
DEFINE_RC(259, GOLDEN_NAME_TOO_LONG, "Golden testname or recname too long.")
DEFINE_RC(260, CODEC_NOT_READY, "CODEC NOT ready.")
DEFINE_UNUSED_RC(261)
DEFINE_RC(262, DEV_OVEN_COMMUNICATION_ERROR, "oven communication error")
DEFINE_RC(263, ERROR_SETTING_TEMPERATURE, "couldn't reach target temperature")
DEFINE_RC(264, DEV_OVEN_ILWALID_TEMPERATURE, "temperature value not valid")
DEFINE_RC(265, DEV_OVEN_MODBUS_CRC_ERROR, "CRC error while communicating with oven")
DEFINE_RC(266, DEV_OVEN_NOT_INITIALIZED, "must first initialize oven")
DEFINE_RC(267, PMU_DEVICE_FAIL, "PMU device failure, operation attempted failed")
DEFINE_RC(268, ILWALID_DEVICE_BAR, "Invalid Bar(s) assigned to device")
DEFINE_RC(269, SUB_DEVICE_EMPTY, "No Sub Devices found")
DEFINE_RC(270, TOO_LOUD, "Acoustic test failed, noise too high")
DEFINE_RC(271, SUB_DEVICE_ILWALID_INDEX, "Sub Device Index Invalid")
DEFINE_RC(272, UNEXPECTED_RESULT, "Read parameter differs from expected")
DEFINE_RC(273, CLOCKS_TOO_LOW, "Clock speed below specified limit")
DEFINE_UNUSED_RC(274)
DEFINE_RC(275, OUT_OF_HW_RSC, "HW entries have run out")
DEFINE_RC(276, HW_STATUS_ERROR, "HW reports wrong status")
DEFINE_RC(277, CMD_STATUS_ERROR, "Error bit set in status register after command was issued")
DEFINE_RC(278, CMD_INTERRUPT_ERROR , "Interrupt status differs from expected")
DEFINE_RC(279, DISPLAY_NO_FREE_HEAD, "No free head available")
DEFINE_RC(280, POWER_TOO_HIGH, "Power above specified limit")
DEFINE_RC(281, TEMP_TOO_HIGH, "Temperature above specified limit")
DEFINE_RC(282, UNEXPECTED_TEST_PERFORMANCE, "Performance varies from expected value")
DEFINE_UNUSED_RC(283)
DEFINE_RC(284, UNSUPPORTED_SYSTEM_CONFIG, "unsupported system configuration")
DEFINE_RC(285, LWRM_BUFFER_TOO_SMALL, "LWRM buffer too small")
DEFINE_RC(286, LWRM_RESET_REQUIRED, "LWRM reset required")
DEFINE_RC(287, LWRM_ILWALID_REQUEST, "LWRM invalid request")
DEFINE_RC(288, POWER_TOO_LOW, "Power is below specified limit")
DEFINE_RC(289, DISPLAY_UNDERFLOW, "Display underflow detected")
DEFINE_RC(290, HBM_REPAIR_IMPOSSIBLE, "Impossible to repair memory")
DEFINE_RC(291, HBM_BAD_ROWS_FOUND, "Found bad rows during Mbist")
DEFINE_RC(292, HBM_SPARE_ROWS_NOT_AVAILABLE, "No spare rows available")
DEFINE_RC(293, DATA_TOO_LARGE, "Data too large.")
DEFINE_UNUSED_RC(294)
DEFINE_UNUSED_RC(295)
DEFINE_UNUSED_RC(296)
DEFINE_RC(297, NO_LOOP_IN_PROGRESS, "No loop to stop.")
DEFINE_RC(298, USB_PORT_NOT_CONNECTED, "Usb port not connected to any device")
DEFINE_RC(299, USBTEST_CONFIG_FAIL, "Usb Test Fail at configuration")
DEFINE_RC(300, AUDIOTEST_FAIL, "AUDIO Test Fail")
DEFINE_UNUSED_RC(301)
DEFINE_UNUSED_RC(302)
DEFINE_UNUSED_RC(303)
DEFINE_UNUSED_RC(304)
DEFINE_UNUSED_RC(305)
DEFINE_RC(306, ISM_EXPERIMENT_INCOMPLETE, "Ism experiment is not complete")
DEFINE_RC(307, ISM_TIMEOUT, "Timed out waiting for MINI Isms to complete")
DEFINE_RC(308, INFOROM_NOT_FOUND, "InfoROM not found")
DEFINE_RC(309, UNEXPECTED_TEST_COVERAGE, "Coverage value varies from expected value")
DEFINE_RC(310, COVERAGE_OBJECT_NOT_FOUND, "Coverage object was not found")
DEFINE_RC(311, LWLINK_TOPOLOGY_MISMATCH, "LwLink discovered topology does not match required topology")
DEFINE_RC(312, BAD_PICKER_INDEX, "bad index into FancyPicker array")
DEFINE_RC(313, HBM_SPARE_LANES_NOT_AVAILABLE, "No spare lanes available")
DEFINE_RC(314, LWLINK_DEVICE_ERROR, "LwLink device error")
DEFINE_RC(315, PRIV_LEVEL_VIOLATION, "Priv level violation oclwred")
DEFINE_RC(316, FB_ECC_CORRECTABLE_ERROR, "ECC detected a correctable error in FB")
DEFINE_RC(317, FB_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in FB")
DEFINE_RC(318, L2_ECC_CORRECTABLE_ERROR, "ECC detected a correctable error in L2")
DEFINE_RC(319, L2_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in L2")
DEFINE_RC(320, SM_ECC_CORRECTABLE_ERROR, "ECC detected a correctable error in SM")
DEFINE_RC(321, SM_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in SM")
DEFINE_RC(322, BAD_HBM_FUSE_DATA, "bad HBM Fuse Data")
DEFINE_RC(323, REPAIR_INSUFFICIENT, "Full function not restored by repair")
DEFINE_RC(324, GCC_ECC_CORRECTABLE_ERROR, "ECC detected an correctable error in GCC")
DEFINE_RC(325, GCC_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in GCC")
DEFINE_RC(326, GENERIC_I2C_ERROR, "Generic I2C error")
DEFINE_RC(327, HSHUB_ECC_CORRECTABLE_ERROR, "ECC detected an correctable error in HSHUB")
DEFINE_RC(328, HSHUB_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in HSHUB")
DEFINE_RC(329, PCIE_ECC_CORRECTABLE_ERROR, "ECC detected an correctable error in PCIE")
DEFINE_RC(330, PCIE_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in PCIE")
DEFINE_RC(331, UNSUPPORTED_FSAA_MODE, "Hardware does not support this FSAA mode")
DEFINE_RC(332, CANNOT_MEET_WAVEFORM, "Cannot pulse fast enough to aclwrately make a waveform")
DEFINE_RC(333, GPCMMU_ECC_CORRECTABLE_ERROR, "ECC detected an correctable error in GPCMMU")
DEFINE_RC(334, GPCMMU_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in GPCMMU")
DEFINE_RC(335, HUBMMU_ECC_CORRECTABLE_ERROR, "ECC detected an correctable error in HUBMMU")
DEFINE_RC(336, HUBMMU_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in HUBMMU")
DEFINE_RC(337, POOL_NOT_ENOUGH_MEMORY, "Pool CANNOT allocate anymore memory")
DEFINE_UNUSED_RC(338)
DEFINE_UNUSED_RC(339)
DEFINE_UNUSED_RC(340)
DEFINE_RC(341, BUFFER_MISMATCH, "Buffer mismatch")
DEFINE_UNUSED_RC(342)
DEFINE_RC(343, ILWALID_HULK_LICENSE, "HULK license invalid")
DEFINE_RC(344, HULK_LICENSE_REQUIRED, "HULK license is required")
DEFINE_RC(345, FALCON_ECC_CORRECTABLE_ERROR, "ECC detected a correctable error in FALCON")
DEFINE_RC(346, FALCON_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in FALCON")
DEFINE_UNUSED_RC(347)
DEFINE_UNUSED_RC(348)
DEFINE_RC(349, GOLDEN_FILE_MISMATCH, "Out of date golden file.")
DEFINE_RC(350, INCORRECT_CHIP_REVISION, "incorrect chip revision")
DEFINE_RC(351, WRONG_MEMORY_STRAP_VALUE, "memory not strapped correctly")
DEFINE_UNUSED_RC(352)
DEFINE_RC(353, CTXSW_ECC_CORRECTABLE_ERROR, "ECC detected a correctable error in CTXSW")
DEFINE_RC(354, CTXSW_ECC_UNCORRECTABLE_ERROR, "ECC detected an uncorrectable error in CTXSW")
DEFINE_UNUSED_RC(355)
DEFINE_UNUSED_RC(356)
DEFINE_UNUSED_RC(357)
DEFINE_UNUSED_RC(358)
DEFINE_RC(359, DUPLICATE_BOARD_DESCRIPTION, "Each board description must be unique")
DEFINE_UNUSED_RC(360)
DEFINE_RC(361, UNKNOWN_BOARD_DESCRIPTION, "Board does not match any known board description")
DEFINE_RC(362, BLACKLIST_FAILURE, "Blacklisting failed")
DEFINE_RC(363, ROW_REMAP_FAILURE, "Row remapping failed")
DEFINE_UNUSED_RC(364)
DEFINE_UNUSED_RC(365)
DEFINE_UNUSED_RC(366)
DEFINE_UNUSED_RC(367)
DEFINE_UNUSED_RC(368)
DEFINE_UNUSED_RC(369)
DEFINE_RC(370, BAD_STEREO_CONNECTOR, "bad stereo glasses connector")
DEFINE_UNUSED_RC(371)
DEFINE_UNUSED_RC(372)
DEFINE_UNUSED_RC(373)
DEFINE_RC(374, USB_NOT_HIGH_SPEED_DEVICE_CONNECTED, "Not High Speed Device connected to Usb2 port")
DEFINE_RC(375, MODS_VK_NOT_READY,                   "Vulkan not ready")
DEFINE_RC(376, MODS_VK_TIMEOUT,                     "Vulkan time out")
DEFINE_RC(377, MODS_VK_EVENT_SET,                   "Vulkan event set")
DEFINE_RC(378, MODS_VK_EVENT_RESET,                 "Vulkan event reset")
DEFINE_RC(379, MODS_VK_INCOMPLETE,                  "Vulkan Incomplete")
DEFINE_RC(380, MODS_VK_ERROR_OUT_OF_HOST_MEMORY,    "Vulkan out of host memory")
DEFINE_RC(381, MODS_VK_ERROR_OUT_OF_DEVICE_MEMORY,  "Vulkan out of device memory")
DEFINE_RC(382, MODS_VK_ERROR_INITIALIZATION_FAILED, "Vulkan init failed")
DEFINE_RC(383, MODS_VK_ERROR_DEVICE_LOST,           "Vulkan device lost")
DEFINE_RC(384, MODS_VK_ERROR_MEMORY_MAP_FAILED,     "Vulkan memory map failed")
DEFINE_RC(385, MODS_VK_ERROR_LAYER_NOT_PRESENT,     "Vulkan layer not present")
DEFINE_RC(386, MODS_VK_ERROR_EXTENSION_NOT_PRESENT, "Vulkan extension not present")
DEFINE_RC(387, MODS_VK_ERROR_FEATURE_NOT_PRESENT,   "Vulkan feature not present")
DEFINE_RC(388, MODS_VK_ERROR_INCOMPATIBLE_DRIVER,   "Vulkan Incompatible driver")
DEFINE_RC(389, MODS_VK_ERROR_TOO_MANY_OBJECTS,      "Vulkan Too many objects")
DEFINE_RC(390, MODS_VK_ERROR_FORMAT_NOT_SUPPORTED,  "Vulkan Format not supported")
DEFINE_RC(391, MODS_VK_ERROR_FRAGMENTED_POOL,       "Vulkan fragmented pool")
DEFINE_RC(392, MODS_VK_ERROR_SURFACE_LOST_KHR,      "Vulkan surface lost")
DEFINE_RC(393, MODS_VK_ERROR_NATIVE_WINDOW_IN_USE_KHR,  "Vulkan native window in use KHR")
DEFINE_RC(394, MODS_VK_SUBOPTIMAL_KHR,                  "Vulkan suboptimal KHR")
DEFINE_RC(395, MODS_VK_ERROR_OUT_OF_DATE_KHR,           "Vulkan out of date")
DEFINE_RC(396, MODS_VK_ERROR_INCOMPATIBLE_DISPLAY_KHR,  "Vulkan incompatible display")
DEFINE_RC(397, MODS_VK_ERROR_VALIDATION_FAILED_EXT,     "Vulkan validation failed")
DEFINE_RC(398, MODS_VK_ERROR_ILWALID_SHADER_LW,         "Vulkan invalid shader")
DEFINE_RC(399, MODS_VK_ERROR_OUT_OF_POOL_MEMORY_KHR,    "Vulkan out of pool memory")
DEFINE_RC(400, MODS_VK_ERROR_ILWALID_EXTERNAL_HANDLE_KHR, "Vulkan invalid external handle KHR")
DEFINE_RC(401, MODS_VK_GENERIC_ERROR,                     "Vulkan Generic Error")
DEFINE_UNUSED_RC(402)
DEFINE_UNUSED_RC(403)
DEFINE_UNUSED_RC(404)
DEFINE_UNUSED_RC(405)
DEFINE_UNUSED_RC(406)
DEFINE_UNUSED_RC(407)
DEFINE_UNUSED_RC(408)
DEFINE_UNUSED_RC(409)
DEFINE_UNUSED_RC(410)
DEFINE_UNUSED_RC(411)
DEFINE_UNUSED_RC(412)
DEFINE_UNUSED_RC(413)
DEFINE_UNUSED_RC(414)
DEFINE_UNUSED_RC(415)
DEFINE_UNUSED_RC(416)
DEFINE_RC(417, NETWORK_NOT_INITIALIZED, "Network is not initialized.")
DEFINE_RC(418, NETWORK_CANNOT_CREATE_SOCKET, "Network cannot create socket.")
DEFINE_RC(419, NETWORK_CANNOT_BIND, "Network socket cannot bind to the specified port.")
DEFINE_RC(420, NETWORK_CANNOT_CONNECT, "Network socket cannot connect to peer.")
DEFINE_RC(421, NETWORK_NOT_CONNECTED, "Network socket is not connected.")
DEFINE_RC(422, NETWORK_ALREADY_CONNECTED, "Network socket is already connected.")
DEFINE_RC(423, NETWORK_READ_ERROR, "Network read error.")
DEFINE_RC(424, NETWORK_WRITE_ERROR, "Network write error.")
DEFINE_RC(425, NETWORK_CANNOT_DETERMINE_ADDRESS, "Network cannot determine host address.")
DEFINE_RC(426, NETWORK_ERROR, "A network error has oclwrred.")
DEFINE_UNUSED_RC(427)
DEFINE_RC(428, VECTORDATA_SIZE_MISMATCH, "Data vector size mismatch expected.")
DEFINE_RC(429, VECTORDATA_VALUE_MISMATCH, "Data vector value miscompare with expected.")
DEFINE_UNUSED_RC(430)
DEFINE_UNUSED_RC(431)
DEFINE_UNUSED_RC(432)
DEFINE_UNUSED_RC(433)
DEFINE_UNUSED_RC(434)
DEFINE_UNUSED_RC(435)
DEFINE_UNUSED_RC(436)
DEFINE_UNUSED_RC(437)
DEFINE_UNUSED_RC(438)
DEFINE_UNUSED_RC(439)
DEFINE_UNUSED_RC(440)
DEFINE_UNUSED_RC(441)
DEFINE_RC(442, POR_SUBBIN_ERROR, "Could not find a compatible POR sub-bin")
DEFINE_RC(443, KAPPA_BINNING_ERROR, "Kappa binning failed")
DEFINE_RC(444, THERMAL_RESISTANCE_TOO_LOW, "Thermal resistance is too low")
DEFINE_RC(445, THERMAL_RESISTANCE_TOO_HIGH, "Thermal resistance is too high")
DEFINE_RC(446, INCORRECT_MODE, "incorrect mode")
DEFINE_UNUSED_RC(447)
DEFINE_RC(448, FILE_2BIG, "File size would become larger than the implementation can support.")
DEFINE_RC(449, FILE_ACCES, "File exists but cannot be accessed with given flags.")
DEFINE_RC(450, FILE_AGAIN, "File write followed a nonblocked write before the latter was complete.")
DEFINE_RC(451, FILE_BADF, "File argument isn't valid file descriptor  or isn't open for writing.")
DEFINE_RC(452, FILE_BUSY, "File device or resource is busy.")
DEFINE_RC(453, FILE_CHILD, "No child process.")
DEFINE_RC(454, FILE_DEADLK, "File deadlock.")
DEFINE_RC(455, FILE_EXIST, "File open with O_CREAT and O_EXCL set but the file already exists.")
DEFINE_RC(456, FILE_FAULT, "File bad address.")
DEFINE_RC(457, FILE_FBIG, "File is too large.")
DEFINE_RC(458, FILE_INTR, "File operation was interrupted by a signal.")
DEFINE_RC(459, FILE_ILWAL, "File argument not valid.")
DEFINE_RC(460, FILE_IO, "File I/O error")
DEFINE_RC(461, FILE_ISDIR, "The open operation was interrupted by a signal.")
DEFINE_RC(462, FILE_MFILE, "The process has too many files open.")
DEFINE_RC(463, FILE_MLINK, "Too many file links.")
DEFINE_RC(464, FILE_NAMETOOLONG, "Filename is too long.")
DEFINE_RC(465, FILE_NFILE, "The system has too many files open.")
DEFINE_RC(466, FILE_NODEV, "No such device in file operation.")
DEFINE_UNUSED_RC(467) // reserved for now, still used in older branches
DEFINE_RC(468, FILE_NOEXEC, "Exec() format error in file operation.")
DEFINE_RC(469, FILE_NOLCK, "The system has run out of file lock resources.")
DEFINE_RC(470, FILE_NOMEM, "Not enough memory for file operation.")
DEFINE_RC(471, FILE_NOSPC, "Not enough disk space left.")
DEFINE_RC(472, FILE_NOSYS, "File function not implemented.")
DEFINE_RC(473, FILE_NOTDIR, "File argument is not a directory.")
DEFINE_RC(474, FILE_NOTEMPTY, "Directory isn't empty.")
DEFINE_RC(475, FILE_NOTTY, "Inappropriate I/O control operation.")
DEFINE_RC(476, FILE_NXIO, "No such device or address in file operation.")
DEFINE_RC(477, FILE_PERM, "File operation not permitted.")
DEFINE_RC(478, FILE_PIPE, "Write to pipe or FIFO that isn't open for reading by any process")
DEFINE_RC(479, FILE_ROFS, "File on read-only file system and invalid flags are set.")
DEFINE_RC(480, FILE_SPIPE, "Illegal file seek.")
DEFINE_RC(481, FILE_SRCH, "Invalid process during file operation.")
DEFINE_RC(482, FILE_XDEV, "Invalid cross-device link during file operation.")
DEFINE_RC(483, FILE_UNKNOWN_ERROR, "Unknown file error.")
DEFINE_RC(484, GOLDEN_VALUE_MISCOMPARE_SD2, "golden value miscompare on 2nd GPU")
DEFINE_RC(485, GOLDEN_VALUE_MISCOMPARE_Z_SD2, "golden value miscompare in Z buffer on 2nd GPU")
DEFINE_RC(486, NOTIFIER_TIMEOUT, "timeout waiting for notifier from GPU")
DEFINE_RC(487, NOTIFIER_TIMEOUT_SD2, "timeout waiting for notifier from 2nd GPU")
DEFINE_UNUSED_RC(488)
DEFINE_RC(489, MARGINAL_MEMORY_OR_FBI, "the memory or frame buffer interface is marginal")
DEFINE_UNUSED_RC(490)
DEFINE_UNUSED_RC(491)
DEFINE_UNUSED_RC(492)
DEFINE_UNUSED_RC(493)
DEFINE_UNUSED_RC(494)
DEFINE_UNUSED_RC(495)
DEFINE_RC(496, ILWALID_DISPLAY_MASK, "invalid display mask")
DEFINE_RC(497, FAILED_TO_GET_IMAGE_OFFSET, "failed to get image offset")
DEFINE_RC(498, ILWALID_DEVICE_ID, "Invalid device Id")
DEFINE_UNUSED_RC(499)
DEFINE_RC(500, ILWALID_TEST_ARRAY, "A problem has been detected in the array of tests")
DEFINE_UNUSED_RC(501)
DEFINE_RC(502, MFGTEST_ILWALID_TEST_NUMBER, "Invalid Mfgtest test number")
DEFINE_RC(503, MFGTEST_ILWALID_TEST_MODE, "Invalid Mfgtest test mode")
DEFINE_RC(504, BOOT_STRAP_ERROR, "Invalid boot strap value")
DEFINE_RC(505, MEMORY_ADDRESS_TRAINING_FAILURE, "Memory address training failed")
DEFINE_RC(506, MEMORY_DQ_READ_TRAINING_FAILURE, "Memory DQ read training failed")
DEFINE_RC(507, MEMORY_DQ_WRITE_TRAINING_FAILURE, "Memory DQ write training failed")
DEFINE_RC(508, ILWALID_CHIP_VERSION, "Invalid Chip Version")
DEFINE_RC(509, NOT_LW_DEVICE, "Not an LW Device")
DEFINE_RC(510, TEST_CANNOT_RUN, "Test Cannot run on this CheetAh Chip Version")
DEFINE_RC(511, SIM_IFACE_NOT_FOUND, "Required chip library interface not found")
DEFINE_UNUSED_RC(512)
DEFINE_UNUSED_RC(513)
DEFINE_UNUSED_RC(514)
DEFINE_UNUSED_RC(515)
DEFINE_UNUSED_RC(516)
DEFINE_UNUSED_RC(517)
DEFINE_UNUSED_RC(518)
DEFINE_UNUSED_RC(519)
DEFINE_UNUSED_RC(520)
DEFINE_UNUSED_RC(521)
DEFINE_UNUSED_RC(522)
DEFINE_UNUSED_RC(523)
DEFINE_UNUSED_RC(524)
DEFINE_UNUSED_RC(525)
DEFINE_UNUSED_RC(526)
DEFINE_UNUSED_RC(527)
DEFINE_UNUSED_RC(528)
DEFINE_UNUSED_RC(529)
DEFINE_UNUSED_RC(530)
DEFINE_RC(531, USB_ILWALID_DEVICE, "Usb invalid device.")

DEFINE_RC(532, LWRM_NOT_FOUND, "LWRM not found")
DEFINE_RC(533, LWRM_INITIALIZATION_PARTIAL_FAILURE, "LWRM initialization partial failure")
DEFINE_RC(534, LWRM_INITIALIZATION_TOTAL_FAILURE, "LWRM initialization total failure")
DEFINE_RC(535, LWRM_PCI_ERROR, "LWRM PCI error")
DEFINE_RC(536, LWRM_UNBOUND_DEVICE, "LWRM unbound device")
DEFINE_RC(537, LWRM_IO_ERROR, "LWRM IO error")
DEFINE_RC(538, LWRM_GPU_IS_LOST, "LWRM gpu has been lost")
DEFINE_RC(539, LWRM_FLCN_ERROR, "LWRM Generic falcon error")
DEFINE_RC(540, LWRM_FATAL_ERROR, "LWRM Fatal error: encountered unrecoverable HW state")
DEFINE_RC(541, LWRM_MEMORY_ERROR, "LWRM Detected memory error")
DEFINE_RC(542, LWRM_ILWALID_VBIOS, "LWRM VBIOS invalid or rejected")
DEFINE_RC(543, LWRM_RISCV_ERROR, "LWRM Generic RISCV error")
DEFINE_UNUSED_RC(544)
DEFINE_UNUSED_RC(545)
DEFINE_UNUSED_RC(546)

DEFINE_RC(547, ILWALID_CPU_FREQUENCY, "Invalid CPU Frequency measured.")
DEFINE_UNUSED_RC(548)
DEFINE_UNUSED_RC(549)
DEFINE_UNUSED_RC(550)
DEFINE_UNUSED_RC(551)
DEFINE_UNUSED_RC(552)
DEFINE_UNUSED_RC(553)
DEFINE_RC(554, RM_RCH_FIFO_ERROR_FIFO_METHOD, "Graphics fifo method error.")
DEFINE_RC(555, RM_RCH_FIFO_ERROR_SW_METHOD, "GPU channel fifo software method error.")
DEFINE_RC(556, RM_RCH_FIFO_ERROR_UNK_METHOD, "GPU channel fifo unknown method error.")
DEFINE_RC(557, RM_RCH_FIFO_ERROR_CHANNEL_BUSY, "GPU channel fifo channel busy error.")
DEFINE_RC(558, RM_RCH_FIFO_ERROR_RUNOUT_OVERFLOW, "GPU channel fifo runout overflow error.")
DEFINE_RC(559, RM_RCH_FIFO_ERROR_PARSE_ERR, "GPU channel fifo parse error.")
DEFINE_RC(560, RM_RCH_FIFO_ERROR_PTE_ERR, "GPU channel fifo PTE error.")
DEFINE_RC(561, RM_RCH_FIFO_ERROR_IDLE_TIMEOUT, "GPU channel fifo idle timeout error.")
DEFINE_RC(562, RM_RCH_GR_ERROR_INSTANCE, "GPU channel instance lookup failure.")
DEFINE_RC(563, RM_RCH_GR_ERROR_SINGLE_STEP, "GPU channel debug single-step.")
DEFINE_RC(564, RM_RCH_GR_ERROR_MISSING_HW, "GPU channel missing hardware error.")
DEFINE_RC(565, RM_RCH_GR_ERROR_SW_METHOD, "GPU channel software method.")
DEFINE_RC(566, RM_RCH_GR_ERROR_SW_NOTIFY, "GPU channel software notify.")
DEFINE_RC(567, RM_RCH_FAKE_ERROR, "GPU channel fake error.")
DEFINE_RC(568, RM_RCH_SCANLINE_TIMEOUT, "GPU channel scan line timeout error.")
DEFINE_RC(569, RM_RCH_VBLANK_CALLBACK_TIMEOUT, "GPU channel vblank callback error.")
DEFINE_RC(570, RM_RCH_PARAMETER_ERROR, "GPU channel software method parameter error.")
DEFINE_UNUSED_RC(571)
DEFINE_UNUSED_RC(572)
DEFINE_UNUSED_RC(573)
DEFINE_UNUSED_RC(574)
DEFINE_RC(575, I2C_DEVICE_NOT_FOUND, "I2C device not found")
DEFINE_UNUSED_RC(576)
DEFINE_RC(577, I2C_COULD_NOT_ACQUIRE_PORT, "Could not acquire I2C port.")
DEFINE_RC(578, I2CTEST_SCL_PULLUP_MISSING, "I2C SCL pull-up resistor missing.")
DEFINE_UNUSED_RC(579)
DEFINE_RC(580, AUXILIARY_POWER_UNCONNECTED, "The auxiliary power connector is not plugged in.")
DEFINE_RC(581, CANNOT_GENERATE_GOLDENS, "can not generate golden values using an external release")
DEFINE_RC(582, GPU_STRESS_TEST_FAILED, "gpu stress test found pixel miscompares")
DEFINE_RC(583, THERMAL_OVERTEMP, "thermal sensor reports overheating")
DEFINE_UNUSED_RC(584)
DEFINE_UNUSED_RC(585)
DEFINE_UNUSED_RC(586)
DEFINE_UNUSED_RC(587)
DEFINE_RC(588, ILWALID_EDID, "invalid EDID")
DEFINE_UNUSED_RC(589)
DEFINE_UNUSED_RC(590)
DEFINE_UNUSED_RC(591)
DEFINE_UNUSED_RC(592)
DEFINE_UNUSED_RC(593)
DEFINE_UNUSED_RC(594)
DEFINE_UNUSED_RC(595)
DEFINE_UNUSED_RC(596)
DEFINE_RC(597, LWRM_NOT_SUPPORTED, "LWRM not supported")
DEFINE_RC(598, LWRM_NOT_IMPLEMENTED, "LWRM function not implemented")
DEFINE_RC(599, FAN_NOT_WORKING, "fan does not seem to cool the chip")
DEFINE_UNUSED_RC(600)
DEFINE_UNUSED_RC(601)
DEFINE_RC(602, LWRM_ILWALID_CHANNEL, "LWRM bad channel")
DEFINE_RC(603, LWRM_TIMEOUT, "LWRM timeout")
DEFINE_UNUSED_RC(604)
DEFINE_RC(605, INCORRECT_FREQUENCY, "the frequency is incorrect")
DEFINE_RC(606, CORE_GRAPHICS_CALL_HUNG, "API call never returned")
DEFINE_UNUSED_RC(607)
DEFINE_RC(608, IRQ_STUCK_ASSERTED, "Interrupt request line stuck asserted")
DEFINE_RC(609, IRQ_CANNOT_ASSERT, "Interrupt request mechanism does not work")

DEFINE_UNUSED_RC(610)
DEFINE_UNUSED_RC(611)

DEFINE_RC(612, TEGRA_CFG_ILWALID_VALUE, "Invalid value for CheetAh configuration variable(s).")
DEFINE_UNUSED_RC(613)

DEFINE_RC(614, GOLDEN_EXTRA_MISCOMPARE, "Extra golden code miscompare")
DEFINE_RC(615, GOLDEN_EXTRA_MISCOMPARE_SD2, "Extra golden code miscompare on 2nd GPU")
DEFINE_UNUSED_RC(616)
DEFINE_UNUSED_RC(617)
DEFINE_UNUSED_RC(618)
DEFINE_UNUSED_RC(619)
DEFINE_RC(620, DLL_LOAD_FAILED, "DLL could not be loaded.")
DEFINE_UNUSED_RC(621)
DEFINE_UNUSED_RC(622)
DEFINE_UNUSED_RC(623)
DEFINE_UNUSED_RC(624)
DEFINE_UNUSED_RC(625)
DEFINE_UNUSED_RC(626)
DEFINE_RC(627, MODE_NOT_SUPPORTED, "Supplied mode not supported by the display.")
DEFINE_RC(628, INSUFFICIENT_FB_BAR_MEMORY, "The framebuffer base address register is too small")
DEFINE_RC(629, MEMORY_LEAK, "Memory leak detected.")
DEFINE_UNUSED_RC(630)
DEFINE_UNUSED_RC(631)
DEFINE_UNUSED_RC(632)
DEFINE_RC(633, MEM_ACCESS_READ_PROTECTION_VIOLATION, "Write access to read-only page.")
DEFINE_UNUSED_RC(634)
DEFINE_UNUSED_RC(635)
DEFINE_RC(636, COULD_NOT_CREATE_JS_PROPERTY, "could not create a JavaScript property")
DEFINE_RC(637, ILWALID_CLOCK_DOMAIN, "Invalid clock domain specified")
DEFINE_UNUSED_RC(638)
DEFINE_UNUSED_RC(639)
DEFINE_UNUSED_RC(640)
DEFINE_UNUSED_RC(641)
DEFINE_UNUSED_RC(642)
DEFINE_RC(643, ILWALID_VOLTAGE_DOMAIN, "Invalid voltage domain specified")
DEFINE_UNUSED_RC(644)
DEFINE_UNUSED_RC(645)
DEFINE_UNUSED_RC(646)
DEFINE_UNUSED_RC(647)
DEFINE_UNUSED_RC(648)
DEFINE_UNUSED_RC(649)

DEFINE_UNUSED_RC(650)
DEFINE_RC(651, BAD_LINK_WIDTH, "GPU did not get the expected number of lanes")
DEFINE_UNUSED_RC(652)
DEFINE_UNUSED_RC(653)
DEFINE_UNUSED_RC(654)
DEFINE_RC(655, LWRM_ILWALID_PARAMETER, "lwrm invalid parameter")
DEFINE_RC(656, LWRM_TOO_MANY_PRIMARIES, "lwrm too many primaries")
DEFINE_RC(657, INCORRECT_L2SLICES, "wrong number of L2 slices detected")
DEFINE_RC(658, MEMORY_SIZE_MISMATCH, "memory size mismatch expected")
DEFINE_RC(659, INCORRECT_LTC, "wrong number of ltc units")
DEFINE_RC(660, INCORRECT_FRAMEBUFFERS, "wrong number of framebuffer units detected")
DEFINE_RC(661, MEMFRAG_SIZE_MISMATCH, "memory fragment size mismatch expected")
DEFINE_RC(662, INCORRECT_TPC, "wrong number of tpc units detected")
DEFINE_RC(663, INCORRECT_PES, "wrong number of pes units detected")
DEFINE_RC(664, INCORRECT_GPC, "wrong number of gpc units detected")
DEFINE_RC(665, INCORRECT_PCIX_LANES, "wrong number of PCI express lanes detected")
DEFINE_RC(666, INCORRECT_FEATURE_SET, "incorrect feature set for this SKU")
DEFINE_UNUSED_RC(667)
DEFINE_RC(668, CANNOT_MEET_FS_REQUIREMENTS, "could not meet floorsweeping requirements")
DEFINE_RC(669, FS_SANITY_FAILURE, "could not determine source of floorsweeping failure")
DEFINE_UNUSED_RC(670)
DEFINE_RC(671, L2_CACHE_ERROR, "Error testing L2 cache")
DEFINE_RC(672, SW_FUSING_ERROR, "SW fusing error")
DEFINE_RC(673, LWRM_NOTHING_TO_DO, "LWRM nothing to do")
DEFINE_RC(674, LWRM_OBJECT_NOT_FOUND, "LWRM object not found")
DEFINE_RC(675, LWRM_MORE_PROCESSING_REQUIRED, "LWRM gpu is still busy or possibly hung")
DEFINE_RC(676, LWRM_CARD_NOT_PRESENT, "LWRM card not present")
DEFINE_RC(677, LWRM_IN_USE, "LWRM in use")
DEFINE_RC(678, LWRM_ILWALID_ACCESS_TYPE, "LWRM invalid access type")
DEFINE_RC(679, LWRM_ILWALID_ARGUMENT, "LWRM invalid argument")
DEFINE_UNUSED_RC(680)
DEFINE_RC(681, LWRM_ILWALID_COMMAND, "LWRM invalid command")
DEFINE_RC(682, LWRM_ILWALID_DATA, "LWRM invalid data")
DEFINE_UNUSED_RC(683)
DEFINE_RC(684, LWRM_ILWALID_METHOD, "LWRM invalid method")
DEFINE_RC(685, LWRM_ILWALID_POINTER, "LWRM invalid pointer")
DEFINE_UNUSED_RC(686)
DEFINE_RC(687, LWRM_ILWALID_REGISTRY_KEY, "LWRM invalid registry key")
DEFINE_RC(688, LWRM_ILWALID_STATE, "LWRM invalid state or config")
DEFINE_RC(689, LWRM_ILWALID_STRING_LENGTH, "LWRM invalid string length")
DEFINE_RC(690, LWRM_FB_TRAINING_FAILED, "LWRM FB Training Failed")
DEFINE_RC(691, METHOD_COUNT_TOO_LARGE, "method count too large")
DEFINE_RC(692, PUSHBUFFER_TOO_SMALL, "pushbuffer too small")
DEFINE_UNUSED_RC(693)
DEFINE_UNUSED_RC(694)
DEFINE_UNUSED_RC(695)
DEFINE_UNUSED_RC(696)
DEFINE_UNUSED_RC(697)
DEFINE_UNUSED_RC(698)
DEFINE_UNUSED_RC(699)
DEFINE_UNUSED_RC(700)
DEFINE_UNUSED_RC(701)
DEFINE_UNUSED_RC(702)
DEFINE_UNUSED_RC(703)
DEFINE_RC(704, CANNOT_UNHOOK_ISR, "Unhook ISR failed")
DEFINE_UNUSED_RC(705)
DEFINE_UNUSED_RC(706)
DEFINE_UNUSED_RC(707)
DEFINE_UNUSED_RC(708)
DEFINE_RC(709, UNSUPPORTED_DEVICE, "selected device is not supported")
DEFINE_UNUSED_RC(710)
DEFINE_RC(711, PCI_CAP_MSI_NOT_SUPPORTED, "Msi is not supported for this device")
DEFINE_UNUSED_RC(712) // reserved for now, because it's still used in r384
DEFINE_RC(713, PCI_MSI_CANNOT_ENABLE, "Cannot enable Msi in Pci Cfg Space")
DEFINE_UNUSED_RC(714) // reserved for now, because it's still used in r384
DEFINE_RC(715, PCI_MSI_CANNOT_DISABLE, "Cannot disable Msi in Pci Cfg Space")
DEFINE_RC(716, PCI_CAP_NOT_SUPPORTED, "Given Cap. is not supported for this device")
DEFINE_UNUSED_RC(717)
DEFINE_UNUSED_RC(718)
DEFINE_RC(719, PARAMETER_MISMATCH, "Read parameter differs from expected")
DEFINE_UNUSED_RC(720)
DEFINE_UNUSED_RC(721)

// LWR65-and-up-only errors below this line.
DEFINE_UNUSED_RC(722)

// LWR70-and-up-only errors below this line.
DEFINE_RC(723, AZA_CODEC_ERROR, "Codec error detected")
DEFINE_RC(724, AZA_STREAM_ERROR, "Stream Error Detected")
DEFINE_RC(725, AZA_RING_BUFFER_ERROR, "Ring Buffer Error Detected")
DEFINE_RC(726, AZATEST_FAIL, "Azalia Test failed")
DEFINE_UNUSED_RC(727)
DEFINE_RC(728, AHCI_PORT_ERROR, "Ahci Port Error")
DEFINE_RC(729, ATA_DRIVE_ERROR, "External drive (hardrive, cdRom, est) error")
DEFINE_UNUSED_RC(730)
DEFINE_UNUSED_RC(731)
DEFINE_UNUSED_RC(732)
DEFINE_RC(733, UNSUPPORTED_FUNCTION_BY_EXT_DEV, "External device does not support the function")
DEFINE_RC(734, EXT_DEV_NOT_FOUND, "External device is not found")
DEFINE_RC(735, PCI_HOT_RESET_FAIL, "Failed to perform hot reset")
DEFINE_UNUSED_RC(736)
DEFINE_UNUSED_RC(737)
DEFINE_UNUSED_RC(738)
DEFINE_UNUSED_RC(739)
DEFINE_UNUSED_RC(740)
DEFINE_UNUSED_RC(741)
DEFINE_UNUSED_RC(742)
DEFINE_UNUSED_RC(743)
DEFINE_UNUSED_RC(744)
DEFINE_UNUSED_RC(745)
DEFINE_UNUSED_RC(746)
DEFINE_UNUSED_RC(747)
DEFINE_UNUSED_RC(748)
DEFINE_UNUSED_RC(749)
DEFINE_UNUSED_RC(750)
DEFINE_UNUSED_RC(751)
DEFINE_UNUSED_RC(752)
DEFINE_UNUSED_RC(753)
DEFINE_UNUSED_RC(754)
DEFINE_UNUSED_RC(755)
DEFINE_UNUSED_RC(756)
DEFINE_UNUSED_RC(757)
DEFINE_UNUSED_RC(758)
DEFINE_UNUSED_RC(759)

// This is lwr75+, but I wanted to keep it in numerical order.  We're going
// to reorg all of this soon anyway
// LWR75-and-up-only errors below this line.
DEFINE_RC(760, RM_RCH_BUS_MASTER_TIMEOUT_ERROR, "GPU channel bus master timeout error.")
DEFINE_RC(761, RM_RCH_DISP_MISSED_NOTIFIER, "GPU channel display missed notifier.")
DEFINE_RC(762, RM_RCH_MPEG_ERROR_SW_METHOD, "GPU channel MPEG software method error.")
DEFINE_RC(763, RM_RCH_ME_ERROR_SW_METHOD, "GPU channel ME software method error.")
DEFINE_RC(764, RM_RCH_VP_ERROR_SW_METHOD, "GPU channel VP software method error.")

// Lwr80
DEFINE_UNUSED_RC(765)
DEFINE_UNUSED_RC(766)
DEFINE_UNUSED_RC(767)
DEFINE_UNUSED_RC(768)

DEFINE_UNUSED_RC(769)

DEFINE_UNUSED_RC(770)
DEFINE_RC(771, ILWLIAD_TEST_JS_OBJECT, "Invalid JsObject for test.")
DEFINE_RC(772, TEGRA_TEST_ILWALID_SETUP, "Invalid setup for CheetAh test.")
DEFINE_RC(773, DATA_MISMATCH, "Data/buffer mismatch with expected")
DEFINE_RC(774, TEGRA_TEST_FAIL, "CheetAh test fail")

DEFINE_RC(775, SLI_ERROR, "SLI generic error")
DEFINE_RC(776, ILWALID_ARGUMENT, "Invalid argument.")

DEFINE_RC(777, OVERCLOCK_SETUP_ERROR, "Error configuring overclocking")
DEFINE_RC(778, BOARD_TEST_ERROR, "Error while testing board")
DEFINE_RC(779, VOLTAGE_OUT_OF_RANGE, "Voltage value out of range")
DEFINE_RC(780, EXTERNAL_DEVICE_NOT_FOUND, "Peripheral device not found")
DEFINE_RC(781, SLI_GPU_LINKED, "Gpu is already linked in a SLI device")
DEFINE_RC(782, SLI_NO_VIDLINK, "Video bridge not present")
DEFINE_RC(783, SLI_GPU_MISMATCH, "Mismatched GPUs not valid for SLI device")

// Lwr95
DEFINE_RC(784, RM_RCH_RC_LOGGING_ENABLED, "GPU channel RC Logging Enabled.")
DEFINE_RC(785, RM_RCH_GR_SEMAPHORE_TIMEOUT, "GPU channel Semaphore Timeout.")
DEFINE_RC(786, RM_RCH_GR_ILLEGAL_NOTIFY, "GPU channel Illegal Notify.")
DEFINE_RC(787, RM_RCH_FIFO_ERROR_FBISTATE_TIMEOUT, "GPU channel fifo FBISTATE Timeout Error.")
DEFINE_RC(788, RM_RCH_VP_ERROR, "GPU channel VP: Unknown Error.")
DEFINE_RC(789, RM_RCH_BAD_ADDR_ACCESS, "GPU channel Bad Address Accessed Error.")
DEFINE_RC(790, RM_RCH_VP2_ERROR, "GPU channel VP2: Unknown Error..")
DEFINE_RC(791, RM_RCH_BSP_ERROR, "GPU channel BSP: Unknown Error..")
DEFINE_RC(792, RM_RCH_SEC_ERROR, "SEC Error")
DEFINE_RC(793, RM_RCH_MSVLD_ERROR, "MSVLD Error")
DEFINE_RC(794, RM_RCH_MSPDEC_ERROR, "MSPDEC Error")
DEFINE_RC(795, RM_RCH_MSPPP_ERROR, "MSPPP Error")

DEFINE_RC(796, RM_RCH_FIFO_ERROR_MMU_ERR_FLT, "Fifo: MMU Error")
DEFINE_RC(797, RM_RCH_PBDMA_ERROR, "PBDMA Error")
DEFINE_RC(798, RM_RCH_FECS_ERR_UNIMP_FIRMWARE_METHOD, "FECS Err: Unimpl Firmware Method")
DEFINE_RC(799, RM_RCH_FECS_ERR_WATCHDOG_TIMEOUT, "FECS Err: Watchdog Timeout")
DEFINE_RC(800, RM_RCH_CE0_ERROR, "GPU channel CE0: Unknown Error.")
DEFINE_RC(801, RM_RCH_CE1_ERROR, "GPU channel CE1: Unknown Error.")
DEFINE_RC(802, RM_RCH_VIC_ERROR, "GPU channel VIC: Unknown Error.")
DEFINE_RC(803, RM_RCH_RESETCHANNEL_VERIF_ERROR, "GPU channel: Reset Channel Verif Error.")
DEFINE_RC(804, RM_RCH_GR_FAULT_DURING_CTXSW, "GPU channel GR: Fault During Context Switch.")
DEFINE_RC(805, RM_RCH_PREEMPTIVE_REMOVAL, "OS: Preemptive Channel Removal.")
DEFINE_RC(806, RM_RCH_GPU_TIMEOUT_ERROR, "OS Indicates GPU Has Timed Out.")
DEFINE_RC(807, RM_RCH_CE2_ERROR, "GPU channel CE2: Unknown Error.")
DEFINE_RC(808, RM_RCH_MSENC_ERROR, "GPU channel MSENC: Unknown Error.")
DEFINE_RC(808, RM_RCH_LWENC0_ERROR, "GPU channel LWENC0: Unknown Error.")
DEFINE_RC(809, RM_RCH_LWENC1_ERROR, "GPU channel LWENC1: Unknown Error.")
DEFINE_RC(810, RM_RCH_LWENC2_ERROR, "GPU channel LWENC2: Unknown Error.")
DEFINE_UNUSED_RC(811)
DEFINE_UNUSED_RC(812)
DEFINE_UNUSED_RC(813)
DEFINE_UNUSED_RC(814)
DEFINE_UNUSED_RC(815)
DEFINE_RC(816, PLL_LOCK_FAILED, "PLL could not be locked")
DEFINE_RC(817, BAD_MEMORY_CRITICAL, "Critical Memory failure(used -fail_critical_fb_range)")
DEFINE_RC(818, ASSERT_FAILURE_DETECTED, "Mods detected an assertion failure")
DEFINE_RC(819, RM_RCH_CE3_ERROR, "GPU channel CE3: Unknown Error.")
DEFINE_RC(820, RM_RCH_CE4_ERROR, "GPU channel CE4: Unknown Error.")
DEFINE_RC(821, RM_RCH_CE5_ERROR, "GPU channel CE5: Unknown Error.")

// Errors specific to CheetAh MODS

DEFINE_RC(822, EGL_FAILED, "ELG call failure or unexpected behavior")
DEFINE_RC(823, KD_FAILED,  "KD call failure or unexpected behavior")

// r270_00 and above

DEFINE_RC(824, RM_RCH_GPU_ECC_UNCORRECTABLE, "GPU Uncorrectable ECC Error.")
DEFINE_RC(825, RESET_IN_PROGRESS, "Reset in progress.")

DEFINE_RC(826, RM_RCH_SILENT_RUNNING_CONSTANT_LEVEL_SET_BY_REGISTRY,   "Silent running constant level set by registry")
DEFINE_RC(827, RM_RCH_SILENT_RUNNING_LEVEL_TRANSITION_DUE_TO_RC_ERROR, "Silent running level transition due to RC error")
DEFINE_RC(828, RM_RCH_SILENT_RUNNING_STRESS_TEST_FAILURE,              "Silent running stress test failure")
DEFINE_RC(829, RM_RCH_SILENT_RUNNING_LEVEL_TRANS_DUE_TO_TEMP_RISE,     "Silent running level transition due to temperature rise")
DEFINE_RC(830, RM_RCH_SILENT_RUNNING_TEMP_REDUCED_CLOCKING,            "Silent running clocks reduced due to temperature rise")
DEFINE_RC(831, RM_RCH_SILENT_RUNNING_PWR_REDUCED_CLOCKING,             "Silent running clocks reduced due to power limits")
DEFINE_RC(832, RM_RCH_SILENT_RUNNING_TEMPERATURE_READ_ERROR,           "Silent running temperature read error")
DEFINE_RC(833, RM_RCH_DISPLAY_CHANNEL_EXCEPTION,                       "Display channel exception")
DEFINE_RC(834, RM_RCH_FB_LINK_TRAINING_FAILURE_ERROR,                  "FB link training failure")
DEFINE_RC(835, RM_RCH_FB_MEMORY_ERROR,                                 "FB memory error")
DEFINE_RC(836, RM_RCH_PMU_ERROR,                                       "PMU error")
DEFINE_RC(837, RM_RCH_SEC2_ERROR,                                      "SEC2 error")
DEFINE_RC(838, RM_RCH_PMU_BREAKPOINT,                                  "PMU Breakpoint")
DEFINE_RC(839, RM_RCH_PMU_HALT_ERROR,                                  "PMU Halt error")

// r304_00 and above

DEFINE_RC(840, RM_RCH_INFOROM_DPR_EVENT,                               "Inforom Dynamic Page Retirement Event")
DEFINE_RC(841, RM_RCH_INFOROM_DPR_FAILURE,                             "Inforom Dynamic Page Retirement Failure")
DEFINE_RC(842, RM_RCH_LWDEC0_ERROR,                                    "LWDEC (LWDEC0) error")
DEFINE_RC(843, RM_RCH_FECS_ERR_FIRMWARE_REG_ACCESS_VIOLATION,          "FECS Err: Register Access Violation")
DEFINE_RC(844, RM_RCH_FECS_ERR_FIRMWARE_VERIF_VIOLATION,               "FECS Err: Verif Method Violation")
DEFINE_RC(845, RM_RCH_GR_CLASS_ERROR,                                  "GR Class Error")

// r361_00 and above

DEFINE_RC(846, RM_RCH_LWLINK_ERROR,                                    "LWLINK Error")

// r364_00 and above

DEFINE_RC(847, RM_RCH_CE6_ERROR, "GPU channel CE6: Unknown Error.")
DEFINE_RC(848, RM_RCH_CE7_ERROR, "GPU channel CE7: Unknown Error.")
DEFINE_RC(849, RM_RCH_CE8_ERROR, "GPU channel CE8: Unknown Error.")

DEFINE_RC(850, VF_SWITCH_TOO_SLOW,                                     "Perf Switching Time Higher Than Expected")

DEFINE_RC(851, RM_RCH_VGPU_ERROR,                                      "vGPU device cannot be started")

DEFINE_RC(852, RM_RCH_GPU_HAS_FALLEN_OFF_THE_BUS,                      "GPU has fallen off the bus")
DEFINE_RC(853, RM_RCH_PUSHBUFFER_CRC_MISMATCH,                         "DMA Engine Error (Pushbuffer CRC mismatch)")
DEFINE_RC(854, HW_SLOWDOWN_ERROR,                                      "Unexpected hardware slowdown")
DEFINE_RC(855, AVFS_ADC_CALIBRATION_ERROR,                             "ADC Calibration error")
DEFINE_RC(856, AVFS_FREQUENCY_CONTROLLER_ERROR,                        "Frequency controller error")
DEFINE_RC(857, AVFS_ILWALID_ADC_TYPE,                                  "Invalid ADC type")
DEFINE_RC(858, AVFS_ILWALID_ADC_CAL_TYPE,                              "Invalid ADC calibration type")

DEFINE_RC(859, CANNOT_APPLY_VF_OFFSET,                                 "Overclocking/overvolting error")
DEFINE_RC(860, CLOCKS_TOO_HIGH,                                        "Clock speed above specified limit")
DEFINE_RC(861, RM_RCH_VGA_SUBSYSTEM_ERROR,                             "VGA Subsystem Error")

DEFINE_RC(862, USB_TRANSFER_ERROR,                                     "USB device data transfer error")

DEFINE_RC(863, RM_RCH_LWJPG0_ERROR,                                    "GPU channel LWJPG0: Unknown Error")
DEFINE_RC(864, RM_RCH_LWDEC1_ERROR,                                    "LWDEC1 error")
DEFINE_RC(865, RM_RCH_LWDEC2_ERROR,                                    "LWDEC2 error")
DEFINE_RC(866, RM_RCH_CE9_ERROR,                                       "GPU channel CE9: Unknown Error.")
DEFINE_RC(867, RM_RCH_OFA0_ERROR,                                      "OFA0 Error")

DEFINE_RC(868, RM_LWT_DRIVER_REPORT,                                   "LwTelemetry Driver Reoport")

DEFINE_RC(869, RM_RCH_LWDEC3_ERROR,                                    "LWDEC3 error")
DEFINE_RC(870, RM_RCH_LWDEC4_ERROR,                                    "LWDEC4 error")
DEFINE_RC(871, RM_RCH_LTC_ERROR,                                       "LTC error")
DEFINE_RC(872, CLOCK_MONITOR_FAULT,                                    "Clock monitor fault(s) detected") //$
DEFINE_RC(873, LWRM_INSUFFICIENT_PERMISSIONS,                          "LWRM insufficient permissions") //$

DEFINE_RC(874, RM_RCH_RESERVED,                                        "Reserved")

DEFINE_RC(875, RM_RCH_EXCESSIVE_SBE_INTERRUPTS,                        "Excessive SBE Interrupts")

DEFINE_RC(876, RM_RCH_INFOROM_ERASE_LIMIT_EXCEEDED,                    "Inforom Erase limit exceeded")

DEFINE_RC(877, RM_RCH_CONTAINED_ERROR,                                 "Error containment: Contained error")
DEFINE_RC(878, RM_RCH_UNCONTAINED_ERROR,                               "Error containment: Uncontained error")

DEFINE_RC(879, RM_RCH_LWDEC5_ERROR,                                    "LWDEC5 error")
DEFINE_RC(880, RM_RCH_LWDEC6_ERROR,                                    "LWDEC6 error")
DEFINE_RC(881, RM_RCH_LWDEC7_ERROR,                                    "LWDEC7 error")

DEFINE_RC(882, RM_RCH_LWJPG1_ERROR,                                    "GPU channel LWJPG1: Unknown Error")
DEFINE_RC(883, RM_RCH_LWJPG2_ERROR,                                    "GPU channel LWJPG2: Unknown Error")
DEFINE_RC(884, RM_RCH_LWJPG3_ERROR,                                    "GPU channel LWJPG3: Unknown Error")
DEFINE_RC(885, RM_RCH_LWJPG4_ERROR,                                    "GPU channel LWJPG4: Unknown Error")
DEFINE_RC(886, RM_RCH_LWJPG5_ERROR,                                    "GPU channel LWJPG5: Unknown Error")
DEFINE_RC(887, RM_RCH_LWJPG6_ERROR,                                    "GPU channel LWJPG6: Unknown Error")
DEFINE_RC(888, RM_RCH_LWJPG7_ERROR,                                    "GPU channel LWJPG7: Unknown Error")

DEFINE_RC(889, RM_SMBPBI_TEST_MESSAGE,                                 "SMBPBI test message")
DEFINE_RC(890, RM_SMBPBI_TEST_MESSAGE_SILENT,                          "SMBPBI test message (silent)")

DEFINE_RC(891, RM_DESTINATION_FLA_TRANSLATION_ERROR,                   "Destination Side FLA translation error")
DEFINE_RC(892, RM_RCH_CTXSW_TIMEOUT_ERROR,                             "Context Switch Timeout Error")
DEFINE_RC(893, RM_SEC_FAULT_ERROR,                                     "Security Fault Error")
DEFINE_RC(894, RM_C2C_ERROR,                                           "C2C Error")
DEFINE_UNUSED_RC(895)
DEFINE_UNUSED_RC(896)
DEFINE_UNUSED_RC(897)
DEFINE_UNUSED_RC(898)
DEFINE_UNUSED_RC(899)
DEFINE_UNUSED_RC(900)

// Range reserved for use by external scripts, these aren't emitted by MODS

DEFINE_RC(901, RESD_1, "Reserved RC")
DEFINE_RC(902, RESD_2, "Reserved RC")
DEFINE_RC(903, RESD_3, "Reserved RC")
DEFINE_RC(904, RESD_4, "Reserved RC")
DEFINE_RC(905, RESD_5, "Reserved RC")

// r495_00 and above
DEFINE_RC(906, RM_BUNDLE_ERROR_EVENT,                                  "Bundle Error Event")
DEFINE_RC(907, RM_DISP_SUPERVISOR_ERROR,                               "Display Supervisor Error")
DEFINE_RC(908, RM_DP_LT_FAILURE,                                       "DisplayPort LinkTrain Failure")
DEFINE_RC(909, RM_HEAD_RG_UNDERFLOW,                                   "Head Register Underflow Error")
DEFINE_RC(910, RM_CORE_CHANNEL_REGS,                                   "Core Channel Register Dump")
DEFINE_RC(911, RM_WINDOW_CHANNEL_REGS,                                 "Window Channel Register Dump")
DEFINE_RC(912, RM_LWRSOR_CHANNEL_REGS,                                 "Cursor Channel Register Dump")
DEFINE_RC(913, RM_HEAD_REGS,                                           "Head Register Dump")

// r510_00 and above
DEFINE_RC(914, RM_GSP_RPC_TIMEOUT,                                     "GSP RPC Timeout")
DEFINE_RC(915, RM_GSP_ERROR,                                           "GSP Error")
