// This file is automatically generated by {{$name}} - DO NOT EDIT!
//
// Provides access to {{$ENGINE}} Hal interfaces.
//
// Profile:  {{$PROFILE}}
// Haldef:   {{$DEF_FILE}}
// Template: {{$TEMPLATE_FILE}}
//

#ifndef G_{{$ENGINE}}HAL_H
#define G_{{$ENGINE}}HAL_H

//
// Typedefs for {{$ENGINE}} public object interfaces.
//

{{ OBJECT_INTERFACE_FUNCTION_TYPEDEFS() }}

//
// "struct" to list {{$ENGINE}}'s public interfaces, eg:  p{{$Engine}}->{{$engine}}Init(pGpu, p{{$Engine}})
//

{{ OBJECT_ENGINE_INTERFACE_TYPEDEF() }}


//
// Typedefs for {{$ENGINE}} HAL interfaces.
//

{{ HAL_INTERFACE_FUNCTION_TYPEDEFS() }}

//
// struct to access {{$ENGINE}}'s hal interfaces, eg:  p{{$Engine}}->hal.{{$engine}}ReadFoo(pGpu, p{{$Engine}})
//

{{ HAL_ENGINE_INTERFACE_TYPEDEF() }}

//
// macro defines to directly access {{$ENGINE}}'s hal interfaces,
// eg: #define {{$engine}}ReadFoo_HAL(_pGpu, _p{{$Engine}}) _p{{$Engine}}->hal.{{$engine}}ReadFoo(_pGpu, _p{{$Engine}})
//

{{ HAL_ENGINE_INTERFACE_DIRECT_CALL_DEFS() }}

//
// Inline stub function definitions.
//

{{ HAL_STUBS_INLINE() }}

//
// {{$ENGINE}} PDB properties
//

{{ ENGINE_PROPERTIES_ENUMERATION_LIST() }}

#endif  // G_{{$ENGINE}}HAL_H