/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

#ifndef __t234_dev_fbif_v4_h__
#define __t234_dev_fbif_v4_h__
/* This file is autogenerated.  Do not edit */
#define LW_FALCON_PWR_BASE              0x0010a000
#define LW_FALCON_CE0_BASE              0x00104000
#define LW_FALCON_CE1_BASE              0x00105000
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK                                                      0x00000070     /* RW-4R */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK__DEVICE_MAP                                          LW_PFALCON_FBIF_DEVICE_MAP_GROUP_PLM /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION                                      3:0            /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL                   0x0000000f     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED                   0x0000000f     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_DISABLED                  0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_ONLY_LEVEL3_ENABLED                  0x00000008     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0                               0:0            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE                        0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE                       0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1                               1:1            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE                        0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE                       0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2                               2:2            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE                        0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE                       0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3                               3:3            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE                        0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE                       0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION                                     7:4            /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED                  0x0000000f     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_DISABLED                 0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_ONLY_LEVEL3_ENABLED                 0x00000008     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0                              4:4            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE                       0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE                      0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1                              5:5            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE                       0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE                      0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2                              6:6            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE                       0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE                      0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3                              7:7            /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE                       0x00000001     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE                      0x00000000     /*       */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_VIOLATION                                       8:8            /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR                          0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON                            0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_VIOLATION                                      9:9            /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR                         0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON                           0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL                                  10:10          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED                          0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED                          0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL                                 11:11          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED                         0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED                         0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_ENABLE                                        31:12          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_SOURCES_ENABLED                    0x000fffff     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK                                                           0x00000088     /* RW-4R */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK__DEVICE_MAP                                               LW_PFALCON_FBIF_DEVICE_MAP_GROUP_PLM /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION                                           3:0            /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_DEFAULT_PRIV_LEVEL                        0x0000000f     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_ENABLED                        0x0000000f     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_ALL_LEVELS_DISABLED                       0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_ONLY_LEVEL3_ENABLED                       0x00000008     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0                                    0:0            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_ENABLE                             0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL0_DISABLE                            0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1                                    1:1            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_ENABLE                             0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL1_DISABLE                            0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2                                    2:2            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_ENABLE                             0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL2_DISABLE                            0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3                                    3:3            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_ENABLE                             0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_PROTECTION_LEVEL3_DISABLE                            0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION                                          7:4            /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_ENABLED                       0x0000000f     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_ALL_LEVELS_DISABLED                      0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_ONLY_LEVEL3_ENABLED                      0x00000008     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0                                   4:4            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_ENABLE                            0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL0_DISABLE                           0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1                                   5:5            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_ENABLE                            0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL1_DISABLE                           0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2                                   6:6            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_ENABLE                            0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL2_DISABLE                           0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3                                   7:7            /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_ENABLE                            0x00000001     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_PROTECTION_LEVEL3_DISABLE                           0x00000000     /*       */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_VIOLATION                                            8:8            /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_VIOLATION_REPORT_ERROR                               0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_READ_VIOLATION_SOLDIER_ON                                 0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_VIOLATION                                           9:9            /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_VIOLATION_REPORT_ERROR                              0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_WRITE_VIOLATION_SOLDIER_ON                                0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL                                       10:10          /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_BLOCKED                               0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_READ_CONTROL_LOWERED                               0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL                                      11:11          /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_BLOCKED                              0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_WRITE_CONTROL_LOWERED                              0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_ENABLE                                             31:12          /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_PRIV_LEVEL_MASK_SOURCE_ENABLE_ALL_SOURCES_ENABLED                         0x000fffff     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG(i)                                                                    (0x00000000+(i)*4) /* RW-4A */
#define LW_PFALCON_FBIF_TRANSCFG__SIZE_1                                                               8              /*       */
#define LW_PFALCON_FBIF_TRANSCFG__DEVICE_MAP                                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_MMODE /*       */
#define LW_PFALCON_FBIF_TRANSCFG__PRIV_LEVEL_MASK                                                      0x00000070 /*       */
#define LW_PFALCON_FBIF_TRANSCFG_TARGET                                                                1:0            /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_TARGET_INIT                                                           0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_TARGET_LOCAL_FB                                                       0x00000000     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_TARGET_COHERENT_SYSMEM                                                0x00000001     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_TARGET_NONCOHERENT_SYSMEM                                             0x00000002     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_MEM_TYPE                                                              2:2            /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_MEM_TYPE_INIT                                                         0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_MEM_TYPE_VIRTUAL                                                      0x00000000     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_MEM_TYPE_PHYSICAL                                                     0x00000001     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_WR                                                                5:4            /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_WR_INIT                                                           0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_WR_L2_EVICT_FIRST                                                 0x00000000     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_WR_L2_EVICT_NORMAL                                                0x00000001     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_WR_L2_EVICT_LAST                                                  0x00000002     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_RD                                                                9:8            /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_RD_INIT                                                           0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_RD_L2_EVICT_FIRST                                                 0x00000000     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_RD_L2_EVICT_NORMAL                                                0x00000001     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_L2C_RD_L2_EVICT_LAST                                                  0x00000002     /* R---V */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK0                                                                12:12          /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK0_INIT                                                           0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK0_ENABLE                                                         0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK0_DISABLE                                                        0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK1                                                                13:13          /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK1_INIT                                                           0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK1_ENABLE                                                         0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_WACHK1_DISABLE                                                        0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK0                                                                14:14          /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK0_INIT                                                           0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK0_ENABLE                                                         0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK0_DISABLE                                                        0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK1                                                                15:15          /* RWIVF */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK1_INIT                                                           0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK1_ENABLE                                                         0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_TRANSCFG_RACHK1_DISABLE                                                        0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_INSTBLK                                                                        0x00000020     /* R--4R */
#define LW_PFALCON_FBIF_INSTBLK__DEVICE_MAP                                                            LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_INSTBLK_PTR                                                                    27:0           /* R--VF */
#define LW_PFALCON_FBIF_INSTBLK_TARGET                                                                 29:28          /* R--VF */
#define LW_PFALCON_FBIF_INSTBLK_TARGET_LOCAL_FB                                                        0x00000000     /* R---V */
#define LW_PFALCON_FBIF_INSTBLK_TARGET_COHERENT_SYSMEM                                                 0x00000001     /* R---V */
#define LW_PFALCON_FBIF_INSTBLK_TARGET_NONCOHERENT_SYSMEM                                              0x00000002     /* R---V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO                                                       0x00000090     /* R--4R */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO__DEVICE_MAP                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_GPC                                                   0:0            /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_GPC_INIT                                              0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_PDB                                                   1:1            /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_PDB_INIT                                              0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_TARGET                                                3:2            /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_TARGET_INIT                                           0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_PDB_ADR_LO                                            31:4           /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_LO_PDB_ADR_LO_INIT                                       0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI                                                       0x00000094     /* R--4R */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI__DEVICE_MAP                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_PDB_ADR_HI                                            6:0            /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_PDB_ADR_HI_INIT                                       0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_PAGE_TABLE_LEVEL                                      9:7            /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_PAGE_TABLE_LEVEL_INIT                                 0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_TARGET_AVA                                            10:10          /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_TARGET_AVA_INIT                                       0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_MMU_REPLAY                                            13:11          /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_MMU_REPLAY_INIT                                       0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_CANCEL_TARGET_CLIENT_UNIT_ID                          20:14          /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_CANCEL_TARGET_CLIENT_UNIT_ID_INIT                     0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_CANCEL_TARGET_GPC_ID                                  23:21          /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_CANCEL_TARGET_GPC_ID_INIT                             0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_SYS_MEMBAR                                            24:24          /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_SYS_MEMBAR_INIT                                       0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_ACK_TYPE                                              26:25          /* R-IVF */
#define LW_PFALCON_FBIF_TLB_ILWALIDATE_PARAM1_HI_ACK_TYPE_INIT                                         0x00000000     /* R-I-V */
#define LW_PFALCON_FBIF_CTL                                                                            0x00000024     /* RW-4R */
#define LW_PFALCON_FBIF_CTL__DEVICE_MAP                                                                LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_CTL_FLUSH                                                                      0:0            /* RW-VF */
#define LW_PFALCON_FBIF_CTL_FLUSH_SET                                                                  0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_FLUSH_CLEAR                                                                0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_ILWAL_CONTEXT                                                              2:2            /* RW-VF */
#define LW_PFALCON_FBIF_CTL_ILWAL_CONTEXT_SET                                                          0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_ILWAL_CONTEXT_CLEAR                                                        0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_CLR_BWCOUNT                                                                3:3            /* RW-VF */
#define LW_PFALCON_FBIF_CTL_CLR_BWCOUNT_SET                                                            0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_CLR_BWCOUNT_CLEAR                                                          0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_ENABLE                                                                     4:4            /* RWIVF */
#define LW_PFALCON_FBIF_CTL_ENABLE_INIT                                                                0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CTL_ENABLE_TRUE                                                                0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_ENABLE_FALSE                                                               0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_CLR_IDLEWDERR                                                              5:5            /* RW-VF */
#define LW_PFALCON_FBIF_CTL_CLR_IDLEWDERR_SET                                                          0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_CLR_IDLEWDERR_CLEAR                                                        0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_RESET                                                                      6:6            /* RW-VF */
#define LW_PFALCON_FBIF_CTL_RESET_SET                                                                  0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_RESET_CLEAR                                                                0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_ALLOW_PHYS_NO_CTX                                                          7:7            /* RWIVF */
#define LW_PFALCON_FBIF_CTL_ALLOW_PHYS_NO_CTX_INIT                                                     0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_CTL_ALLOW_PHYS_NO_CTX_DISALLOW                                                 0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_ALLOW_PHYS_NO_CTX_ALLOW                                                    0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_IDLE                                                                       8:8            /* R--VF */
#define LW_PFALCON_FBIF_CTL_IDLE_TRUE                                                                  0x00000001     /* R---V */
#define LW_PFALCON_FBIF_CTL_IDLE_FALSE                                                                 0x00000000     /* R---V */
#define LW_PFALCON_FBIF_CTL_IDLEWDERR                                                                  9:9            /* R--VF */
#define LW_PFALCON_FBIF_CTL_IDLEWDERR_TRUE                                                             0x00000001     /* R---V */
#define LW_PFALCON_FBIF_CTL_IDLEWDERR_FALSE                                                            0x00000000     /* R---V */
#define LW_PFALCON_FBIF_CTL_SRTOUT                                                                     10:10          /* R--VF */
#define LW_PFALCON_FBIF_CTL_SRTOUT_TRUE                                                                0x00000001     /* R---V */
#define LW_PFALCON_FBIF_CTL_SRTOUT_FALSE                                                               0x00000000     /* R---V */
#define LW_PFALCON_FBIF_CTL_CLR_SRTOUT                                                                 11:11          /* RW-VF */
#define LW_PFALCON_FBIF_CTL_CLR_SRTOUT_SET                                                             0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_CTL_CLR_SRTOUT_CLEAR                                                           0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CTL_SRTOVAL                                                                    19:16          /* RWIVF */
#define LW_PFALCON_FBIF_CTL_SRTOVAL_INIT                                                               0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2                                                                           0x00000084     /* RW-4R */
#define LW_PFALCON_FBIF_CTL2__DEVICE_MAP                                                               LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_CTL2__PRIV_LEVEL_MASK                                                          0x00000088 /*       */
#define LW_PFALCON_FBIF_CTL2_NACK_MODE                                                                 0:0            /* RWIVF */
#define LW_PFALCON_FBIF_CTL2_NACK_MODE_INIT                                                            0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_CTL2_NACK_MODE_NACK_AS_ACK                                                     0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_THROTTLE                                                                       0x0000002c     /* RW-4R */
#define LW_PFALCON_FBIF_THROTTLE__DEVICE_MAP                                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_THROTTLE_BUCKET_SIZE                                                           11:0           /* RWIVF */
#define LW_PFALCON_FBIF_THROTTLE_BUCKET_SIZE_INIT                                                      0x00000064     /* RWI-V */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_COUNT                                                            27:16          /* RWIVF */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_COUNT_DISABLE                                                    0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_SIZE                                                             31:30          /* RWIVF */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_SIZE_16B                                                         0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_SIZE_32B                                                         0x00000001     /* RW--V */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_SIZE_64B                                                         0x00000002     /* RWI-V */
#define LW_PFALCON_FBIF_THROTTLE_LEAK_SIZE_128B                                                        0x00000003     /* RW--V */
#define LW_PFALCON_FBIF_REGIONCFG                                                                      0x0000006c     /* RW-4R */
#define LW_PFALCON_FBIF_REGIONCFG__DEVICE_MAP                                                          LW_PFALCON_FBIF_DEVICE_MAP_GROUP_MMODE /*       */
#define LW_PFALCON_FBIF_REGIONCFG__PRIV_LEVEL_MASK                                                     0x00000070 /*       */
#define LW_PFALCON_FBIF_REGIONCFG_T0                                                                   3:0            /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T0_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T1                                                                   7:4            /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T1_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T2                                                                   11:8           /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T2_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T3                                                                   15:12          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T3_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T4                                                                   19:16          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T4_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T5                                                                   23:20          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T5_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T6                                                                   27:24          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T6_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_REGIONCFG_T7                                                                   31:28          /* RWIVF */
#define LW_PFALCON_FBIF_REGIONCFG_T7_INIT                                                              0x00000000     /* RWI-V */
#define LW_PFALCON_FBIF_CG1                                                                            0x00000074     /* RW-4R */
#define LW_PFALCON_FBIF_CG1__DEVICE_MAP                                                                LW_PFALCON_FBIF_DEVICE_MAP_GROUP_MMODE /*       */
#define LW_PFALCON_FBIF_CG1_SLCG                                                                       3:0            /*       */
#define LW_PFALCON_FBIF_CG1_SLCG_ENABLED                                                               0              /*       */
#define LW_PFALCON_FBIF_CG1_SLCG_DISABLED                                                              0xF            /*       */
#define LW_PFALCON_FBIF_CG1_SLCG__PROD                                                                 0x0            /*       */
#define LW_PFALCON_FBIF_CG1_SLCG_MSD0                                                                  0:0            /* RWIVF */
#define LW_PFALCON_FBIF_CG1_SLCG_MSD0_ENABLED                                                          0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CG1_SLCG_MSD0_DISABLED                                                         0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CG1_SLCG_MSD1                                                                  1:1            /* RWIVF */
#define LW_PFALCON_FBIF_CG1_SLCG_MSD1_ENABLED                                                          0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CG1_SLCG_MSD1_DISABLED                                                         0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CG1_SLCG_FB0                                                                   2:2            /* RWIVF */
#define LW_PFALCON_FBIF_CG1_SLCG_FB0_ENABLED                                                           0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CG1_SLCG_FB0_DISABLED                                                          0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_CG1_SLCG_FB1                                                                   3:3            /* RWIVF */
#define LW_PFALCON_FBIF_CG1_SLCG_FB1_ENABLED                                                           0x00000000     /* RW--V */
#define LW_PFALCON_FBIF_CG1_SLCG_FB1_DISABLED                                                          0x00000001     /* RWI-V */
#define LW_PFALCON_FBIF_ACHK_BLK(i)                                                                    (0x00000030+(i)*8) /* RW-4A */
#define LW_PFALCON_FBIF_ACHK_BLK__SIZE_1                                                               2              /*       */
#define LW_PFALCON_FBIF_ACHK_BLK__DEVICE_MAP                                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_ACHK_BLK_ADDR                                                                  31:0           /* RW-VF */
#define LW_PFALCON_FBIF_ACHK_CTL(i)                                                                    (0x00000034+(i)*8) /* RW-4A */
#define LW_PFALCON_FBIF_ACHK_CTL__SIZE_1                                                               2              /*       */
#define LW_PFALCON_FBIF_ACHK_CTL__DEVICE_MAP                                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_ACHK_CTL_SIZE                                                                  4:0            /* RW-VF */
#define LW_PFALCON_FBIF_ACHK_CTL_TYPE                                                                  6:6            /* RW-VF */
#define LW_PFALCON_FBIF_ACHK_CTL_TYPE_INSIDE                                                           0x00000000     /* R---V */
#define LW_PFALCON_FBIF_ACHK_CTL_TYPE_OUTSIDE                                                          0x00000001     /* R---V */
#define LW_PFALCON_FBIF_ACHK_CTL_STATE                                                                 7:7            /* RW-VF */
#define LW_PFALCON_FBIF_ACHK_CTL_STATE_DISABLE                                                         0x00000000     /* R---V */
#define LW_PFALCON_FBIF_ACHK_CTL_STATE_ENABLE                                                          0x00000001     /* R---V */
#define LW_PFALCON_FBIF_ACHK_CTL_COUNT                                                                 31:16          /* RW-VF */
#define LW_PFALCON_FBIF_BW_ALLOC                                                                       0x0000004c     /* RW-4R */
#define LW_PFALCON_FBIF_BW_ALLOC__DEVICE_MAP                                                           LW_PFALCON_FBIF_DEVICE_MAP_GROUP_FBIF /*       */
#define LW_PFALCON_FBIF_BW_ALLOC_VAL                                                                   31:0           /*       */
#define LW_PFALCON_FBIF_BW_ALLOC_INT_RD                                                                7:0            /* RW-VF */
#define LW_PFALCON_FBIF_BW_ALLOC_INT_WR                                                                15:8           /* RW-VF */
#define LW_PFALCON_FBIF_BW_ALLOC_EXT_RD                                                                23:16          /* RW-VF */
#define LW_PFALCON_FBIF_BW_ALLOC_REQ_T                                                                 31:24          /* RW-VF */
#endif // __t234_dev_fbif_v4_h__
