/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2003-2016 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/* This file is autogenerated by ref2h.pl.  Do not edit */
/************************************************************************|
|*                                                                      *|
|*      Copyright (c) 2019 by LWPU Corp. All rights reserved.         *|
|*                                                                      *|
|* This material constitutes the trade secrets and confidential,        *|
|* proprietary information of LWPU, Corp.  This material is not to be *|
|* disclosed, reproduced, copied, or used in any manner not permitted   *|
|* under license from LWPU, Corp.                                     *|
|*                                                                      *|
|************************************************************************/

#ifndef LW_RISCV_ADDRESS_MAP_H_
#define LW_RISCV_ADDRESS_MAP_H_

#define LW_RISCV_AMAP_IROM_START				0x0000000000080000ull
#define LW_RISCV_AMAP_IROM_SIZE 				0x0000000000080000ull
#define LW_RISCV_AMAP_IROM_END  				0x0000000000100000ull
#define LW_RISCV_AMAP_IMEM_START				0x0000000000100000ull
#define LW_RISCV_AMAP_IMEM_SIZE 				0x0000000000080000ull
#define LW_RISCV_AMAP_IMEM_END  				0x0000000000180000ull
#define LW_RISCV_AMAP_DMEM_START				0x0000000000180000ull
#define LW_RISCV_AMAP_DMEM_SIZE 				0x0000000000080000ull
#define LW_RISCV_AMAP_DMEM_END  				0x0000000000200000ull
#define LW_RISCV_AMAP_EMEM_START				0x0000000001200000ull
#define LW_RISCV_AMAP_EMEM_SIZE 				0x0000000000080000ull
#define LW_RISCV_AMAP_EMEM_END  				0x0000000001280000ull
#define LW_RISCV_AMAP_INTIO_START				0x0000000001400000ull
#define LW_RISCV_AMAP_INTIO_SIZE 				0x0000000000200000ull
#define LW_RISCV_AMAP_INTIO_END  				0x0000000001600000ull
#define LW_RISCV_AMAP_EXTMEM1_START				0x0000040000000000ull
#define LW_RISCV_AMAP_EXTMEM1_SIZE 				0x0000040000000000ull
#define LW_RISCV_AMAP_EXTMEM1_END  				0x0000080000000000ull

/**** dGPU naming alias ****/
#define LW_RISCV_AMAP_PRIV_START				LW_RISCV_AMAP_EXTIO1_START
#define LW_RISCV_AMAP_PRIV_SIZE 				LW_RISCV_AMAP_EXTIO1_SIZE
#define LW_RISCV_AMAP_PRIV_END  				LW_RISCV_AMAP_EXTIO1_END
#define LW_RISCV_AMAP_FBGPA_START				LW_RISCV_AMAP_EXTMEM1_START
#define LW_RISCV_AMAP_FBGPA_SIZE 				LW_RISCV_AMAP_EXTMEM1_SIZE
#define LW_RISCV_AMAP_FBGPA_END  				LW_RISCV_AMAP_EXTMEM1_END
#define LW_RISCV_AMAP_SYSGPA_START				LW_RISCV_AMAP_EXTMEM2_START
#define LW_RISCV_AMAP_SYSGPA_SIZE 				LW_RISCV_AMAP_EXTMEM2_SIZE
#define LW_RISCV_AMAP_SYSGPA_END  				LW_RISCV_AMAP_EXTMEM2_END
#define LW_RISCV_AMAP_GVA_START				LW_RISCV_AMAP_EXTMEM3_START
#define LW_RISCV_AMAP_GVA_SIZE 				LW_RISCV_AMAP_EXTMEM3_SIZE
#define LW_RISCV_AMAP_GVA_END  				LW_RISCV_AMAP_EXTMEM3_END

#endif
