/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2014-2022 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/*!
 * @file soe_halgen.c
 *
 * Stubs and hal interface init routines for files generated by rmconfig halgen
 * process.
 */

//
// These defines affect what we see in halgen generated headers.
//
// If SOECFG_ENGINE_SETUP is not already defined, then setup for
// a monolithic hal.
//
// The per-gpu-family hal setups #include this file with the SOECFG
// setup defines already defined to pull in just the interfaces
// needed for that gpu family.
//

#if ! defined(SOECFG_ENGINE_SETUP)

#  define SOECFG_ENGINE_SETUP    1   // pull in per-gpu engine interface's
#  define SOECFG_HAL_SETUP_ALL   1   // monolithic - ALL configured gpus' support in this file
#  define SOECFG_HAL_SUPPORT_ALL 1   // not required, but keeps us honest

#endif  // ! defined SOECFG_ENGINE_SETUP

//
// Pull in generated code to setup each engine's hal interfaces for each gpu.
//
// 'rmsoecmdif.h' must be included here to resolve references to the SOE
// command and message types used by the HAL-interfaces.
//
#include "soesw.h"
#include "rmsoecmdif.h"
#include "unit_dispatch.h"
#include "soe_rttimer.h"
#include "soe_timer.h"
#include "soe_lwlink.h"
#include "spidev.h"
#include "tsec_drv.h"

#include "config/g_hal_private.h"

