// This file is automatically generated by acr-config - DO NOT EDIT!
//
// Private HAL support for ACRLIB.
//
// Profile:  acr_pmu-t186_load
// Haldef:   /home/scratch.dgoyal_gpu/p4/sw/dev/gpu_drv/chips_a/uproc/tegra_acr/src/../config/haldefs/acrlib.def
// Template: templates/gt_eng_private.h
//

#ifndef G_ACRLIB_PRIVATE_H
#define G_ACRLIB_PRIVATE_H

#include "g_acrlib_hal.h"


#if defined(ACRCFG_OBJ_SETUP_ALL)    // for use by hal init only

//
// ACRLIB's object-level interface functions
//


//
// ACRLIB's object-level _STUB and _MISSING interface routines
//



//
// Initialize ACRLIB's object-level interfaces
//
static void
acrlibSetPropertiesSpecial
(
    POBJGPU       pGpu,
    POBJACRLIB    pAcrlib
)
{

}



#endif  // ACRCFG_OBJ_SETUP_ALL

#if defined(ACRCFG_ENGINE_SETUP)    // for use by hal init only

//
// per-GPU functions to setup ACRLIB interface function pointers
//

#if defined(ACRCFG_HAL_SETUP_T186)

static void         acrlibHalIfacesSetup_T186(ACRLIB_HAL_IFACES *pAcrlibHal) 
                        GCC_ATTRIB_SECTION("imem_acr", "acrlibHalIfacesSetup_T186");

static void acrlibHalIfacesSetup_T186(ACRLIB_HAL_IFACES *pAcrlibHal)
{

    // T186's ACRLIB hal interface function pointer block
    static const ACRLIB_HAL_IFACES acrlibHalIfacesInitStruct_T186 =
    {

        0 // avoid empty typedef
    };  // acrlibHalIfacesInitStruct_T186

    // init T186's ACRLIB function ptrs using the init struct above
    *pAcrlibHal = acrlibHalIfacesInitStruct_T186;
}

#endif  // T18X or T186



#endif  // ACRCFG_ENGINE_SETUP

// Were any _MOCK interfaces generated into g_acrlib_private.h ?
#define ACRLIB_MOCK_FUNCTIONS_GENERATED    0


#endif  // G_ACRLIB_PRIVATE_H
