pragma Ada_2012;
pragma Style_Checks (Off);

with Interfaces.C; use Interfaces.C;

package libos_xcsr_h is

   --  unsupported macro: LW_RISCV_CSR_XMPUIDX LW_RISCV_CSR_MMPUIDX
   --  unsupported macro: LW_RISCV_CSR_XMPUVA LW_RISCV_CSR_MMPUVA
   --  unsupported macro: LW_RISCV_CSR_XMPUPA LW_RISCV_CSR_MMPUPA
   --  unsupported macro: LW_RISCV_CSR_XMPURNG LW_RISCV_CSR_MMPURNG
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR LW_RISCV_CSR_MMPUATTR
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_XW LW_RISCV_CSR_MMPUATTR_MW
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_UW LW_RISCV_CSR_MMPUATTR_UW
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_XR LW_RISCV_CSR_MMPUATTR_MR
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_UR LW_RISCV_CSR_MMPUATTR_UR
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_XX LW_RISCV_CSR_MMPUATTR_MX
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_UX LW_RISCV_CSR_MMPUATTR_UX
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_COHERENT LW_RISCV_CSR_MMPUATTR_COHERENT
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_CACHEABLE LW_RISCV_CSR_MMPUATTR_CACHEABLE
   --  unsupported macro: LW_RISCV_CSR_XMPUATTR_WPR LW_RISCV_CSR_MMPUATTR_WPR
   --  unsupported macro: LW_RISCV_CSR_XEPC LW_RISCV_CSR_MEPC
   --  unsupported macro: LW_RISCV_CSR_XTVEC LW_RISCV_CSR_MTVEC
   --  unsupported macro: LW_RISCV_CSR_XCAUSE LW_RISCV_CSR_MCAUSE
   --  unsupported macro: LW_RISCV_LAST_EXCEPTION LW_RISCV_CSR_MCAUSE_EXCODE_SSS
   --  unsupported macro: LW_RISCV_LAST_INTERRUPT LW_RISCV_CSR_MCAUSE_EXCODE_M_EINT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_IACC_FAULT LW_RISCV_CSR_MCAUSE_EXCODE_IACC_FAULT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_IAMA LW_RISCV_CSR_MCAUSE_EXCODE_IAMA
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_ILL LW_RISCV_CSR_MCAUSE_EXCODE_ILL
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_BKPT LW_RISCV_CSR_MCAUSE_EXCODE_BKPT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_LPAGE_FAULT LW_RISCV_CSR_MCAUSE_EXCODE_LPAGE_FAULT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_SPAGE_FAULT LW_RISCV_CSR_MCAUSE_EXCODE_SPAGE_FAULT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_LACC_FAULT LW_RISCV_CSR_MCAUSE_EXCODE_LACC_FAULT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_SACC_FAULT LW_RISCV_CSR_MCAUSE_EXCODE_SACC_FAULT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_LAMA LW_RISCV_CSR_MCAUSE_EXCODE_LAMA
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_SAMA LW_RISCV_CSR_MCAUSE_EXCODE_SAMA
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_X_TINT LW_RISCV_CSR_MCAUSE_EXCODE_M_TINT
   --  unsupported macro: LW_RISCV_CSR_XCAUSE_EXCODE_UCALL LW_RISCV_CSR_MCAUSE_EXCODE_UCALL
   --  unsupported macro: LW_RISCV_CSR_XSTATUS LW_RISCV_CSR_MSTATUS
   --  unsupported macro: LW_RISCV_CSR_XSTATUS_XPP LW_RISCV_CSR_MSTATUS_MPP
   --  unsupported macro: LW_RISCV_CSR_XSTATUS_XPP_USER LW_RISCV_CSR_MSTATUS_MPP_USER
   --  unsupported macro: LW_RISCV_CSR_XSTATUS_XPIE LW_RISCV_CSR_MSTATUS_MPIE
   --  unsupported macro: LW_RISCV_CSR_XSTATUS_XPIE_ENABLE LW_RISCV_CSR_MSTATUS_MPIE_ENABLE
   --  unsupported macro: LW_RISCV_CSR_XCOUNTEREN LW_RISCV_CSR_MUCOUNTEREN
   --  unsupported macro: LW_RISCV_CSR_XCOUNTEREN_TM LW_RISCV_CSR_MUCOUNTEREN_TM
   --  unsupported macro: LW_RISCV_CSR_XCOUNTEREN_CY LW_RISCV_CSR_MUCOUNTEREN_CY
   --  unsupported macro: LW_RISCV_CSR_XIP LW_RISCV_CSR_MIP
   --  unsupported macro: LW_RISCV_CSR_XIE LW_RISCV_CSR_MIE
   --  unsupported macro: LW_RISCV_CSR_XIE_XTIE LW_RISCV_CSR_MIE_MTIE
   --  unsupported macro: LW_RISCV_CSR_XIE_XEIE LW_RISCV_CSR_MIE_MEIE
   --  unsupported macro: LW_RISCV_CSR_XIP_XEIP LW_RISCV_CSR_MIP_MEIP
   --  unsupported macro: LW_RISCV_CSR_XDCACHEOP LW_RISCV_CSR_MDCACHEOP
   --  unsupported macro: LW_RISCV_CSR_XDCACHEOP_MODE LW_RISCV_CSR_MDCACHEOP_MODE
   --  unsupported macro: LW_RISCV_CSR_XDCACHEOP_MODE_ILW_LINE LW_RISCV_CSR_MDCACHEOP_MODE_ILW_LINE
   --  unsupported macro: LW_RISCV_CSR_XDCACHEOP_ADDR_MODE LW_RISCV_CSR_MDCACHEOP_ADDR_MODE
   --  unsupported macro: LW_RISCV_CSR_XDCACHEOP_ADDR_MODE_VA LW_RISCV_CSR_MDCACHEOP_ADDR_MODE_VA
  -- M-mode to S-mode CSR changes
end libos_xcsr_h;
