#
# _LWRM_COPYRIGHT_BEGIN_
#
# Copyright 2017 by LWPU Corporation.  All rights reserved.  All
# information contained herein is proprietary and confidential to LWPU
# Corporation.  Any use, reproduction, or disclosure without the written
# permission of LWPU Corporation is prohibited.
#
# _LWRM_COPYRIGHT_END_
#

#
# Top-level FUB makefile. This makefile is responsible for building the FUB
# binary including projects it depends on (RTOS, bootloader, etc ...) across
# all FUB config-profiles.
#

all: build

###############################################################################
# Serialize per-profile builds (this does not prevent parallel building within
# each profile). It should be possible to remove this line but doing so may not
# translate to any appreciable speedup and it also makes a mess of the output.
# It is also known to crash intermittently.
###############################################################################

.NOTPARALLEL:

###############################################################################
# By default, this makefile will attempt to build all FUBCFG profiles. If this
# behavior is undesired, the user may override it using the following make-var.
# By setting the value to "true" only the default FUBCFG profile will be built
# when this makefile is ilwoked.
###############################################################################

FUBCFG_PROFILE_DEFAULT_ONLY ?= "false"

###############################################################################
# Set FUBCFG_PROFILES to the list of FUBCFG profiles to build. The value is set
# in one of three ways depending on defaults and user-overrides (if any).
#
# 1. Sourcing fub-profiles.mk to get the full list of profiles (default)
# 2. If FUBCFG_PROFILE_DEFAULT_ONLY is defined and set to "true", build only
#    the default FUBCFG profile. See above for more information.
# 3. If FUBCFG_PROFILE is set on the command-line or as an elwvar, build that
#    profile only.
#
# Setting FUBCFG_PROFILES in the shell or on the command-line will override the
# profile(s) returned by the first two options above. FUBCFG_PROFILE trumps 
# everything.
###############################################################################

FUBCFG_PROFILES ?=

ifndef FUBCFG_PROFILE
  ifeq ("$(strip $(FUBCFG_PROFILES))", "")
    ifneq ("$(FUBCFG_PROFILE_DEFAULT_ONLY)","true")
      include $(LW_SOURCE)/uproc/fub/config/fub-profiles.mk
      override FUBCFG_PROFILES = $(FUBCFG_PROFILES_ALL)
    else
      override FUBCFG_PROFILES = fub-lwdec_tu10x_aes
    endif
  endif
else
  FUBCFG_PROFILES = $(FUBCFG_PROFILE)
endif

###############################################################################
# Create submake build/clean/clobber targets for profiles being built.
###############################################################################

PROFILES.build   = $(FUBCFG_PROFILES:=.build)
PROFILES.clean   = $(FUBCFG_PROFILES:=.clean)
PROFILES.clobber = $(FUBCFG_PROFILES:=.clobber)

###############################################################################
# Targets/Rules
###############################################################################

.PHONY: PROFILES.build   build
.PHONY: PROFILES.clean   clean
.PHONY: PROFILES.clobber clobber

build::   $(PROFILES.build)
clean::   $(PROFILES.clean)
clobber:: $(PROFILES.clobber)

$(PROFILES.build):
	$(MAKE) -f make-profile.lwmk FUBCFG_PROFILE=$(basename $@) build

$(PROFILES.clean):
	$(MAKE) -f make-profile.lwmk FUBCFG_PROFILE=$(basename $@) clean

$(PROFILES.clobber):
	$(MAKE) -f make-profile.lwmk FUBCFG_PROFILE=$(basename $@) clobber
