// This file is automatically generated by acr-config - DO NOT EDIT!
//
// Private HAL support for ACRLIB.
//
// Profile:  acr_pmu-t210_load
// Haldef:   /home/project.smadhavan_mobile/p4/sw/rel/gpu_drv/r435/CHIPSSAFETY435_35/uproc/tegra_acr/src/../config/haldefs/acrlib.def
// Template: templates/gt_eng_private.h
//

#ifndef G_ACRLIB_PRIVATE_H
#define G_ACRLIB_PRIVATE_H

#include "g_acrlib_hal.h"


#if defined(ACRCFG_OBJ_SETUP_ALL)    // for use by hal init only

//
// ACRLIB's object-level interface functions
//


//
// ACRLIB's object-level _STUB and _MISSING interface routines
//



#endif  // ACRCFG_OBJ_SETUP_ALL


// Were any _MOCK interfaces generated into g_acrlib_private.h ?
#define ACRLIB_MOCK_FUNCTIONS_GENERATED    0


#endif  // G_ACRLIB_PRIVATE_H
