/* _LWRM_COPYRIGHT_BEGIN_
 *
 * Copyright 2010-2022 by LWPU Corporation.  All rights reserved.  All
 * information contained herein is proprietary and confidential to LWPU
 * Corporation.  Any use, reproduction, or disclosure without the written
 * permission of LWPU Corporation is prohibited.
 *
 * _LWRM_COPYRIGHT_END_
 */

/***************************** HW State Rotuines ***************************\
*                                                                           *
* Module: dpu_halgen.c                                                      *
*       Stubs and hal interface init routines for files generated by        *
*       rmconfig halgen process.                                            *
*                                                                           *
\***************************************************************************/

//
// These defines affect what we see in halgen generated headers.
//
// If DPUCFG_ENGINE_SETUP is not already defined, then setup for
// a monolithic hal.
//
// The per-gpu-family hal setups #include this file with the DPUCFG
// setup defines already defined to pull in just the interfaces
// needed for that gpu family.
//

#if ! defined(DPUCFG_ENGINE_SETUP)

#  define DPUCFG_ENGINE_SETUP    1   // pull in per-gpu engine interface's
#  define DPUCFG_HAL_SETUP_ALL   1   // monolithic - ALL configured gpus' support in this file
#  define DPUCFG_HAL_SUPPORT_ALL 1   // not required, but keeps us honest

#endif  // ! defined DPUCFG_ENGINE_SETUP

//
// Pull in generated code to setup each engine's hal interfaces for each gpu.
//
#include "dpusw.h"
#include "rmdpucmdif.h"
#include "unit_dispatch.h"
#include "dpu_objisohub.h"
#include "dpu_objvrr.h"
#include "config/g_hal_private.h"

